### ISSUE TITLE
Refactor provvis global scope usage

### ISSUE THREAD

**Issue by flekschas** [refinery-platform/refinery-platform#1000]
Commit: 657b619bae3c307aad9d83d501e5098ddedb289c
### Steps to reproduce
1. Go to `provvis-helpers.js` or other provvis files.
### Observed behavior

All helper methods are registered as global function on `window` and indirectly used by other functions across `provvis`. This is problematic as there's no obvious link between components. It's also a general anti-pattern to bloat the global scope as it can easily cause clashes. ESLint also complains because the file contains only unused methods. While this rule can (and needs to) be disabled this will hinder us from finding truly unused code. It furthermore cause issues in other files using those functions because one never knows when a method / var is really missing or just on the global window object. It's also impossible to test those function using Karma.
### Expected behavior

Each method should be registered as a service and be explicitly be injected.

**Comment by flekschas** [comment]
I realized that the provvis is a plain JavaScript application and only two directives are actually part of Angular. In order to avoid a lengthy angularization process we could simply treat the provvis as a third-party dependency and use the directives as a Angular wrapper.
We are currently doing the same with the list graph of the data set exploration visualization and it works fine.

**Comment by flekschas** [comment]
I outsourced and ES6ified _prov-vis_: https://github.com/refinery-platform/provvis

Unfortunately there is more refactoring needed in https://github.com/parklab/refinery-platform/blob/develop/refinery/static/source/js/refinery/contents.js because even though _prov-vis_ exports only three main function, all the other globally exposed modules are directly used too. Ideally all access should go through the top level object, i.e. `provvis`.

**Comment by mccalluc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;5lkdAHMO&#x2F;45-1000"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> 1000</a>
