### ISSUE TITLE
Synonym search sometimes causes weird results

### ISSUE THREAD

**Issue by flekschas** [refinery-platform/refinery-platform#1011]
Commit: e91867d903876ef61bdc9ce7a2c9572d3f5a7d7c
### Steps to reproduce
1. Set up synonym search https://github.com/parklab/refinery-platform/wiki/Manage-Synonyms-for-Search
2. Go to http://192.168.50.50:8000 and search for `zebra`
### Observed behavior

The first two results highlight **assessed** and are related to _mouse_.

![bildschirmfoto 2016-04-15 um 09 20 12](https://cloud.githubusercontent.com/assets/932103/14566751/d54b0ba4-02fe-11e6-97d3-95fcf7f31a37.png)
### Expected behavior

The first two results shouldn't be shown at all as they are totally unrelated.

**Comment by jkmarx** [comment]
<img width="482" alt="screen shot 2018-07-26 at 6 05 32 pm" src="https://user-images.githubusercontent.com/9956764/43291162-84cccbc8-90fe-11e8-9ab5-030a441a238f.png">

Not an issue on beta as of 30567f8a2b1207f2e24fab92a744c151b64f88db
