### ISSUE TITLE
Data set summary panel should contain a list of all direct ontology annotations

### ISSUE THREAD

**Issue by flekschas** [refinery-platform/refinery-platform#1015]
Commit: e91867d903876ef61bdc9ce7a2c9572d3f5a7d7c
### Steps to reproduce
1. Go to http://192.168.50.50:8000 and open the data set summary panel.
### Observed behavior

List of direct ontology annotation terms is shown: negative.
### Expected behavior

List of direct ontology annotation terms is shown: positive.

Ideally the terms should be linked to the terms of the exploration view and either lock them with a click or query for them. A click should simultaneously close the panel.

**Comment by jkmarx** [comment]
With v1.6.9 Explore/Satori has been removed.
