### ISSUE TITLE
Load third-party UI dependencies in static via bower 

### ISSUE THREAD

**Issue by flekschas** [refinery-platform/refinery-platform#1016]
Commit: df3ad330c524a01a68bd534c610a7347d918cfa5
### Steps to reproduce
1. Go to `/refinery/static/source/`
### Observed behavior

You'll find:
- backbone
- bootbox
- d3
- ...
### Expected behavior

Bower should load these dependencies.

**Comment by mccalluc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;F3IzipSa&#x2F;47-1016"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #1016</a>

**Comment by jkmarx** [comment]
This issue will go away with the implementation of the data-set2 browser and the removal of the data set1 browser code.

**Comment by jkmarx** [comment]
With data set 2, most of the libraries will either be no longer used or are being imported via bower.
