### ISSUE TITLE
Find underlying issue behind needing to run specific app's migrations individually

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#1146]
These workarounds were introduced in commits: 0c4cc0610ef1827f2d289207b15f2353559c9e2b & 56418595879050ab997cb4e5aa28702537f70c39
### Steps to reproduce
1. `vagrant provision`
### Observed behavior

If one provisions their instance using one of these commits or later they'll see the extra steps that have been introduced. 
### Expected behavior

We should not need to provide these individual migration steps as they may lead to more issues down the road.

**Comment by mccalluc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;xaTySUG8&#x2F;49-1146"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> 1146</a>

**Comment by scottx611x** [comment]
This has been addressed as of: https://github.com/refinery-platform/refinery-platform/pull/1511
