### ISSUE TITLE
Replace puppetlabs-rabbitmq module with puppet-rabbitmq

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#1185]
This module has been [deprecated](https://forge.puppet.com/puppetlabs/rabbitmq) by its author since September 7, 2017.
The reason given was:
This module has been moved to the care of Vox Pupuli where it is now being maintained and updated.
The author has suggested [puppet-rabbitmq](https://forge.puppet.com/puppet/rabbitmq) as its replacement.

The latest version (8.4.0) of puppet-rabbitq has a [new repo key location](https://github.com/voxpupuli/puppet-rabbitmq/blob/v8.4.0/manifests/repo/apt.pp) and thus should help avoid the recent key error:
```puppet
Error: /Stage[main]/Rabbitmq::Repo::Apt/Apt::Source[rabbitmq]/Apt::Key[Add key: 0A9AF2115F4687BD29803A206B73A36E6026DFCA from Apt::Source rabbitmq]/Apt_key[Add key: 0A9AF2115F4687BD29803A206B73A36E6026DFCA from Apt::Source rabbitmq]/ensure: change from absent to present failed: 523 Origin Unreachable for https://www.rabbitmq.com/rabbitmq-release-signing-key.asc
```
However, version 8.4.0 requires:
* Puppet >= 4.10.0 (current version is 3.4.3)
 * puppet/archive >= 2.0.0 (current version is 1.3.0)

See also: #3096
___
Original description from June 2016:
RabbitMQ has [transitioned to a new release signing key](https://www.rabbitmq.com/key-transition-0xF7B8CEA6056E8E56.txt). The puppetlabs-rabbitmq module still uses the old key which caused [provisioning to fail](https://github.com/parklab/refinery-platform/issues/1181). There is a [pull request to replace the key](https://github.com/puppetlabs/puppetlabs-rabbitmq/pull/481). We should update the puppetlabs-rabbitmq module to the version that contains the new key and remove the [temporary workaround](https://github.com/parklab/refinery-platform/commit/f03ac118bf96f8f61763315bd78f72e9b6bb27f2) from the manifest.

**Comment by mccalluc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;xrohRT3n&#x2F;52-1185"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> 1185</a>

**Comment by jkmarx** [comment]
https://forge.puppet.com/puppet/rabbitmq/reference#manage_python
