### ISSUE TITLE
Data Set / share API Adjustment

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#1191]
### Current behavior

 dataset/sharing api returns the sharelist field for data-set owners only
### Desired behavior

dataset/sharing api returns the sharelist field for data-set owners AND
- [x] all authenticated users
- [ ] public dataSet

**TODO:**
- [ ] Fix share_list field returned from the `data_sets` api

**Comment by jkmarx** [comment]
@ngehlenborg Please comment when you have a chance.

**Comment by hackdna** [comment]
also, please update https://github.com/parklab/refinery-platform/wiki/Security so we could keep track of the access control model

**Comment by scottx611x** [comment]
@ngehlenborg When you have some time could you comment on this?

**Comment by scottx611x** [comment]
https://github.com/parklab/refinery-platform/blob/develop/refinery/core/api.py#L303

**Comment by ngehlenborg** [comment]
Plan:

1. allow everyone to do a `GET` on the sharing information for a sharable resource
  * requires modifying permissions control in `res_sharing` to allow processing of request also for non-owners and anonymous users
1. include in the `share_list` only those groups that the current user is a member of
  1. get list `a` of groups that resources has been shared with
  1. get list `b` of groups that users is member of
  1. create intersection of `a` and `b` and return as `share_list`
1. retain current logic for `PUT` requests

**Comment by ngehlenborg** [comment]
Important: when retrieving list of shared groups and list of groups that user is member of, make sure that performance does not suffer.

**Comment by scottx611x** [comment]
@jmarx: When I try to GET any shareable resource that I'm an owner of, I do indeed see the `share_list` field, but it's always set to null: `"share_list": null,`

Are you seeing this same behavior?

**Comment by ngehlenborg** [comment]
@scottx611x: Has that resource been shared with any group?

**Comment by scottx611x** [comment]
@nils yes, it looks like the `share_list` field returned by the data_sets api is never set.

The proper sharing info is returned from:

api/v1/data_sets/<uuid>/sharing/?format=json

**Comment by scottx611x** [comment]
The intersection logic here seems to work fine (meaning that it properly returned the intersection between the groups a User belongs to and the Groups that a given ShareableResource is a part of)). 

Deeper investigation is necessary to figure out why this broke the sharing/import into own space in Datasets preview.

Could be due to the removal of the `share_list` field in the non-sharing API repose, but if I remember correctly I tested that out and it was not the case!!!

**Comment by jkmarx** [comment]
I ran into a bug with the anonymous user failing to return the share list. http://stackoverflow.com/questions/11314905/request-user-returns-a-simplelazyobject-how-do-i-wake-it
