### ISSUE TITLE
Remove INTERVAL_BETWEEN_CHECKS from settings

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#1209]
It appears to be unused.

**Comment by mccalluc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;zb1BmIR8&#x2F;54-1209"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> 1209</a>

**Comment by ngehlenborg** [comment]
Please remove!
