### ISSUE TITLE
Live chat integration for Refinery?

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#1219]
There could potentially be a need for live chat integration within Refinery once we have a more established user base. 

Some options for this are:
- Chatra | https://chatra.io/
- PureChat | https://www.purechat.com/
- Intercom | https://www.intercom.io/

**Comment by drj11** [comment]
At ScraperWiki we used intercom.io (which is more than just live chat, it has customer profiling, segmentation, and a message store), and it's great (but not at all cheap).

**Comment by bzz** [comment]
Sorry for the stupid question, but where do you think this live chat can be applied?
Is there a public instance of Refinery running somewhere?

**Comment by scottx611x** [comment]
@bzz Yes indeed: http://beta.stemcellcommons.org

**Comment by jkmarx** [comment]
@scottx611x Do we want to keep this question open?

**Comment by scottx611x** [comment]
Probably not! I'll go ahead and close
