### ISSUE TITLE
Download multiple files at once

### ISSUE THREAD

**Issue by sjhosui** [refinery-platform/refinery-platform#1253]
Currently have to download files one by one using the down arrow icon.

Would like to select multiple files and hit download.

**Comment by ngehlenborg** [comment]
@jkmarx: Is this on the roadmap for the next iterations of the file browser? I remember the team discussed different options for this in the past but I am not sure if we scheduled this already.

**Comment by jkmarx** [comment]
@ngehlenborg Phase 2 Enhancements https://github.com/parklab/refinery-platform/issues/326

**Comment by jkmarx** [comment]
Added this to issue #326, since they are closely related.
