### ISSUE TITLE
Isolate AWS related deployment artifacts

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#1276]
Currently, they are stored in various locations under `refinery/deployment`:
- aws-config/
- aws-tags/
- aws-requirements.txt
- aws.sh
- bin/
- stack.py

We should move them to `refinery/deployment/aws` to make supporting other cloud environments easier in the future. AWS-specific Puppet manifests can stay where they are.

**Comment by mccalluc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;YgfSDzVt&#x2F;55-1276"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> 1276</a>

**Comment by hackdna** [comment]
Closed mostly by #3101 and #3179
