### ISSUE TITLE
Unit Tests: Service to create uuids

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#1289]
- [x] Implement a common service to generate uuids, for front end testing.
- [x] Update unit tests

Reference:
http://stackoverflow.com/questions/105034/create-guid-uuid-in-javascript

**Comment by mccalluc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;s4IyZs4a&#x2F;58-1289"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> 1289</a>
