### ISSUE TITLE
Replace REFINERY_URL_SCHEME with native Django options

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#1293]
Django provides native support for determining whether a session is secure, including situations when ELB is used:
https://docs.djangoproject.com/en/1.7/topics/security/#ssl-https
http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/x-forwarded-headers.html#x-forwarded-proto

Depends on Django version 1.7 (#614)

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;At5n55H0&#x2F;6-configure-refinery-vms-to-use-https"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> configure Refinery VMs to use https</a>

**Comment by scottx611x** [comment]
`os.environ['wsgi.url_scheme'] = 'https'` -> in wsgi_xxxx.py

http://security.stackexchange.com/a/8970

**Comment by hackdna** [comment]
The SE answer you referenced is almost three years old and I don't think it'd work with our ELB setup. Have you looked at the URLs listed in the first comment?

**Comment by scottx611x** [comment]
@hackdna I'm just trying to help. 

I thought the Django portion of the answer was relevant. I'm not too familiar with ELB yet, so if you could enlighten me as to why this type of solution wouldn't work with our setup that would be awesome.

**Comment by hackdna** [comment]
It's explained in the docs referenced in the first comment: "If your Django app is behind a proxy, though, the proxy may be “swallowing” the fact that a request is HTTPS, using a non-HTTPS connection between the proxy and Django."

Here are the relevant portions of ELB and Apache configurations:
https://github.com/refinery-platform/refinery-platform/blob/b4a3e7921317ca6368efc68b2ee8cb6c9aa15195/deployment/stack.py#L338
https://github.com/refinery-platform/refinery-platform/blob/b4a3e7921317ca6368efc68b2ee8cb6c9aa15195/deployment/refinery-modules/refinery/manifests/apache2.pp#L29

**Comment by hackdna** [comment]
Native Django options require request context which is not always available. Custom Django setting appears to be the preferred solution:
* https://stackoverflow.com/a/34992631
* [ACCOUNT_DEFAULT_HTTP_PROTOCOL](https://github.com/pennersr/django-allauth/blob/master/docs/configuration.rst)
