### ISSUE TITLE
Analysis Icons on Dashboard and Navbar

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#1302]
Change for global analysis popover and workflows. 

![pasted image at 2016_08_04 03_07 pm-1](https://cloud.githubusercontent.com/assets/9956764/17482322/425601b8-5d4f-11e6-9d1d-8d755312fef9.png)

**Comment by jkmarx** [comment]
@ngehlenborg The analysis content icon (bar chart) is being used as the fastqc viewer. 

<img width="120" alt="screen shot 2016-08-26 at 1 31 20 pm" src="https://cloud.githubusercontent.com/assets/9956764/18014569/84638b48-6b91-11e6-9795-e550c05d3b1b.png">

**Comment by jkmarx** [comment]
@ngehlenborg Do you still approve switching to these icons? I only ask because the issue is pretty old.

**Comment by scottx611x** [comment]
@jkmarx I've removed the FastQC viewer in #2042 Re: https://github.com/refinery-platform/refinery-platform/issues/1302#issuecomment-242801301

**Comment by jkmarx** [comment]
Issue is outdated.
