### ISSUE TITLE
Created manager group names are cryptic

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1307]
Commit: 33de42c5dcd1e22fe17e4
### Steps to reproduce
- Create a new group
### Observed behavior

An admin group, titled something like `.Managers 8c74c9f0-01c2-4c85-bdb1-6d963e8e508c` is created.

[My account](https://test.stemcellcommons.org/users/1c5f033e-6546-46c6-937f-eccf6245dfc2/) lists two groups:
- [`Public2`](https://test.stemcellcommons.org/groups/8c74c9f0-01c2-4c85-bdb1-6d963e8e508c/), which I created
- and [`.Managers 8c74c9f0-01c2-4c85-bdb1-6d963e8e508c`](https://test.stemcellcommons.org/groups/81785b8e-a95e-48b5-bb4b-e21293396870/), whose name matches the ID of the former.
### Expected behavior

Perhaps it should be called something like "[new group name] Managers", or something else more human readable?

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;cos9jM49&#x2F;304-data-set-sharing-collaboration"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> data set sharing &#x2F; collaboration</a>

**Comment by hackdna** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove Manager groups](https://trello.com/c/iSVS3sSJ/122-remove-manager-groups)
