### ISSUE TITLE
Details always says "using 0 bytes"

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1309]
Commit: 33de42c5dcd1e22fe17e4
### Steps to reproduce
- Click the "Details" tab on https://test.stemcellcommons.org/data_sets/090e1238-5604-4cae-bdb0-94226e7dcae2/#/details/
- Note that under "Data Files" it says "24 files using 0 bytes".

If getting the actual number is hard, maybe it could just be dropped? How important this is will also depend on whether it's being stored on EBS or S3.

**Comment by scottx611x** [comment]
@mccalluc This is due to these files not having been imported into Refinery yet. That metric only is talking about these files size on disk.

Once my analysis is complete on that Dataset you should see the size update

**Comment by ngehlenborg** [comment]
@scottx611x: Is the size different from 0 when a tabular meta data file is imported with the `Data File Permanent` option checked (i.e., files will get imported upon data set creation)?

**Comment by jkmarx** [comment]
Should we can info to the UI, so the user does not think the 0 is correct?

**Comment by ngehlenborg** [comment]
@scottx611x: Can you investigate https://github.com/refinery-platform/refinery-platform/issues/1309#issuecomment-238536177 and check if there are open issues related to file size calculation?

@jkmarx: Yes, we should add an "info tooltip" that gives possible explanations for why the file size of the data set is 0, e.g the files are all stored on a remote server or the files are of size 0 (<- that's actually something to be concerned about).

**Comment by scottx611x** [comment]
Related to #773

**Comment by jkmarx** [comment]
Resolved at some point. 
<img width="269" alt="screen shot 2018-05-23 at 10 22 40 am" src="https://user-images.githubusercontent.com/9956764/40430536-55d76a48-5e73-11e8-8ca7-9cdc18815eae.png">
