### ISSUE TITLE
Data Import add Help Popover

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#1324]
- [ ] Question marks next to fields that launches a pop up with additional help information

**Comment by jkmarx** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;nppQOdjX&#x2F;187-update-data-import-ui"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Update data import UI</a>

**Comment by jkmarx** [comment]
@ngehlenborg Comments?
<img width="1413" alt="screen shot 2016-08-09 at 2 08 19 pm" src="https://cloud.githubusercontent.com/assets/9956764/17527911/35e470a8-5e3b-11e6-83d8-923604a2a6f1.png">

**Comment by jkmarx** [comment]
@ngehlenborg Is the idea we put the current field text in the help or are we adding additional text in the help?

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;GoXu66WF&#x2F;295-improve-data-set-import-form"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> improve data set import form</a>

**Comment by jkmarx** [comment]
@sjhosui @ngehlenborg Comments on the additional help/text?

**Comment by ngehlenborg** [comment]
Address once #1406 has been completed.

**Comment by jkmarx** [comment]
@ngehlenborg I was thinking of this issue. I believe you wanted to define the additional help text.

**Comment by ngehlenborg** [comment]
Let's discuss in a meeting. @jkmarx - can you please organize and loop in @drj11. We also have written feedback from beta tester.

**Comment by drj11** [comment]
cc @SarahKit
