### ISSUE TITLE
Should Provenance graph selection change current set?

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1337]
Should the Provenance Graph path selection change the current set? Or is it there just to help identify dependencies?

<img width="881" alt="screen shot 2016-08-12 at 11 36 55 am" src="https://cloud.githubusercontent.com/assets/730388/17628049/8ec3bf7e-6081-11e6-9248-54f688acd434.png">

I had been curious what the blue dots in the graph did during the the demo. It looks like they highlight paths in the graph: Should that also update the selected rows? (ie, something like "14 out of 32" in this case.) I don't have any intuition about what makes sense to the end user.

**Comment by mccalluc** [comment]
@flekschas : Do you see anything here which demands action? Unless something here strikes you, I propose that we close this.

**Comment by flekschas** [comment]
@mccalluc I haven't worked on or with the provenance graph unfortunately, so I can't really say much. @ngehlenborg probably knows best what's going on

**Comment by jkmarx** [comment]
@mccalluc This issue along with a couple of other provenance graph issues could be captured in a broader 'enhance provenance ui'. I'd recommend combining your comments with issues #1467, #1466, #1338, #1337, #816

**Comment by jkmarx** [comment]
Encapsulated in larger issue. Ref #1338
