### ISSUE TITLE
When using ELB, log client IP

### ISSUE THREAD

**Issue by drj11** [refinery-platform/refinery-platform#1389]
Commit: 29d22f5911b8578a246fcf39d4a6c8b251b648b9
### Steps to reproduce

Not a user-visible problem, but...
### Observed behavior

When using an ELB the apache logs record the ELB IP address which generally does not change and is not very helpful.
### Expected behavior

The source client IP address should be logged.
Use the [X-Forwarded-For header](http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html#x-forwarded-for)

**Comment by hackdna** [comment]
Implemented in https://github.com/refinery-platform/refinery-platform/commit/7cd597698036f1d44335c5474610acce8fcd7ae4
