### ISSUE TITLE
ontology info box mispositioned on FF only

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1403]
-    Specific code commit: 30c8f75
-    Version of the web browser and OS: FF 42.0.1 (works on chrome)
-    Environment where the error occured: test.stemcellcommons.org
### Steps to reproduce
1. FF only
2. DO NOT log in
3. Click "Explore"
4. Click on one of the first three ontology terms in any column
### Observed behavior
- The text of the info box is positioned correctly, but the box itself is against the bottom of the column.

<img width="293" alt="screen shot 2016-09-15 at 9 24 01 am" src="https://cloud.githubusercontent.com/assets/730388/18551571/0111be9a-7b27-11e6-90ce-40346b521a67.png">
### Expected behavior
- Rendering on FF should match that on Chrome.

**Comment by flekschas** [comment]
Seems like quite a few things are broken in FF. I'll address while going forward to version 1.0 of the list graph, which I am currently working on.

This will be included in the satori-demo branch.

**Comment by flekschas** [comment]
Both bugs are related to Firefox not supporting relative _transform-origin_ for SVG elements...

**Comment by flekschas** [comment]
Fixed in the most current build of the ListGraph. Will be integrated in the satori-tutorials after testing.
