### ISSUE TITLE
Create non-interactive, external tutorial

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#1405]
Describe a use case including the following steps:
1. import a tabular metadata file with local files (http://data.cloud.refinery-platform.org/?prefix=data/sample-data/human-chipseq/) - @sjhosui: any concerns about using that for the tutorial?
2. view data set in data set browser
3. open data set in file browser
4. filter data set based on facets and sort table
5. select files and:
   1. run analyses: FASTQC and peak calling with MACS2
   2. monitor analyses
   3. view FASTQC results and download FASTQC results
   4. launch web-based IGV on peak calling output
6. [view data set in provenance graph]
7. create group for collaboration
8. invite other users to group
9. share data set with with group
10. [delete MACS2 analysis]
11. [delete data set]

Provide as webpage (e.g. in the wiki).

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;f2OiO48f&#x2F;267-prepare-documentation-help-for-users"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> prepare documentation&#x2F;help for users</a>

**Comment by scottx611x** [comment]
@gmnelson can this be closed?

**Comment by gmnelson** [comment]
@scottx611x yes, closing now
