### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#1406]
Describe Refinery on  feature-by-feature basis:
- accounts
  - creating an account
  - resending password
  - filling out user profile
- data upload
  - tabular meta data 
    - local files
    - remote files
  - ISA-Tab with remote files
- browsing of data sets
  - filter
  - search
  - [exploration features]
  - preview
  - [deleting analyses]
  - [deleting datasets]
- browsing of data set contents
  - facets
  - filtering
  - [provenance graph]
  - details/about
- launching and monitoring analyses
  - viewing workflow details
  -  single input workflows
  - paired input workflows
  - checking analysis progress
  - viewing analysis results
  - canceling running analyses
- visualization 
  - general limitations
  - launch web-based IGV
  - launch standalone IGV
- collaboration
  - creating a group
  - inviting group members
  - resending invites
  - canceling invites
  - promoting members to managers
  - removing members from a group
  - deleting a group

Provide as webpage.

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;f2OiO48f&#x2F;267-prepare-documentation-help-for-users"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> prepare documentation&#x2F;help for users</a>

**Comment by scottx611x** [comment]
@gmnelson can this be closed?

**Comment by gmnelson** [comment]
@scottx611x i would say yes
