### ISSUE TITLE
Suggested edits for currently implemented tutorials

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#1417]
https://www.evernote.com/shard/s59/sh/3819898f-5e8f-4378-b17f-4363aab950df/96bb4f715fec660e

Trying Data Upload tutorial
- [x] Popover should allow body click to exit, like global analysis popover.
- [ ] I was able to break out of the tutorial by clicking “Upload” rather than “Proceed to Upload Page” — perhaps something to consider changing — instead, break out of the tutorial with either an upper-right corner (of the popup) “X”, or by pressing Escape. There is no way to break out of the tutorial at the first step, though an X does appear later.
- [ ] Perhaps the X button should become “Finish” at the end of the tutorial, and perhaps it should leave the user on the default Upload page.
- [ ] It’s also unclear in the tutorial when the “ISA-Tab Metadata” tab has been selected — some animation could help? Not too important.
- [ ] I think it would be great if these tutorials were made more prominent upon login, especially for new users. Maybe default?
- [ ] The checkbox showing completion of each tutorial doesn’t fill until the user navigates away from the page on which the tutorial ended.

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Emf3Y059&#x2F;309-improve-data-upload-tutorial"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> improve data upload tutorial</a>

**Comment by scottx611x** [comment]
Note to self: Close Dataset Preview/Explore on DataSet tutorial start

**Comment by jkmarx** [comment]
Tutorial is not a feature at the moment. Issue can be reopened if it's reintroduced.
