### ISSUE TITLE
Delete related objects when workflow is deleted

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#1425]
- Specific code commit: 738eba5c
- Version of the web browser and OS: N/A
- Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Vagrant VM, dev mode
### Steps to reproduce
1. Import a Galaxy workflow
2. Delete a single workflow in the Django admin (not in bulk)
### Observed behavior

Related objects like WorkflowDataInput, WorkflowInputRelationships (others?) are not deleted
### Expected behavior

Related objects should be deleted

**Comment by hackdna** [comment]
See also #2173

**Comment by scottx611x** [comment]
@hackdna Were there any other models related other than the two referenced in this issue that needed removal? These two (`WorkflowDataInput` & `WorkflowInputRelationships`)  as well as: `WorkflowDataInputMap` don't exist as of: https://github.com/refinery-platform/refinery-platform/pull/2654

**Comment by hackdna** [comment]
Yes, possibly. It would be great to check that nothing is left behind.

**Comment by jkmarx** [comment]
@scottx611x Check, models were removed at some point.

**Comment by scottx611x** [comment]
After double-checking it looks like https://github.com/refinery-platform/refinery-platform/pull/2654 took care of this
