### ISSUE TITLE
Delete related objects when analysis is deleted

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#1428]
- Specific code commit: 738eba5c
- Version of the web browser and OS: N/A
- Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Vagrant VM, dev mode
### Steps to reproduce
1. Import a Galaxy workflow and a data set
2. Run the workflow on the data set
3. Delete the resulting analysis in the Django admin (not a bulk delete)
### Observed behavior

Related objects like WorkflowDataInputMap, WorkflowFilesDL (others?) are not deleted
### Expected behavior

Related objects should be deleted

**Comment by ngehlenborg** [comment]
Refer to #2173?

**Comment by jkmarx** [comment]
Ref #2466
