### ISSUE TITLE
IGV data loading errors

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1435]
### Steps to reproduce
1. Reference http genome data in an upload
2. Load IGV from a https server

(May have a similar problem when the server does not provide CORS headers: Our S3 bucket does, but others may not.)
### Observed behavior
- Browser security will prevent the data from loading

(@jkmarx has also seen this locally on http, which may be CORS, but I'm not sure: There could be something else in here.)
### Expected behavior

Not sure. Assuming the diagnosis is correct:
- Warn during upload?
- Copy to server during upload?
- Copy to server when IGV is requested?
- Our https server could proxy http files w/o long term storage?
- More human-readable error message in IGV?

**Comment by ngehlenborg** [comment]
Let's try to get the IGV.js maintainer to provide a meaningful error message when tracks can't be loaded.

**Comment by mccalluc** [comment]
I think it would be feasible to monkey patch IGV, or something like that, to add a more informative message. (For a generic user, the existing error messages are really all that can be expected.)

I'll be doing this work in https://github.com/refinery-platform/igv-wrapper-for-refinery/issues/6: It doesn't make sense to maintain both versions.

**Comment by hackdna** [comment]
Contributing this code to the IGV.js project would be even better.
