### ISSUE TITLE
provenance attributes menu not showing on FF

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1466]
- Specific code commit: fad81a20e6ce1334cde6c3350a1bf89fa4b82a81
- Version of the web browser and OS: FF 47.0.1 / MacOS 10.11.6
- Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): test.stemcellcommons.org
  ### Steps to reproduce

Please list all the actions and the input data used:
1. Pick any dataset
2. View in File Browser
3. Pick Provenance as Display
4. Click on the Attributes pulldown (with the wrench)
### Observed behavior
- The shading of the button changes on mousedown, but no menu appears (as it does on Chrome)
  ### Expected behavior
- A menu should appear, and I should be able to select attributes from it.

FF left / Chrome right

<img width="549" alt="screen shot 2016-10-12 at 11 28 40 am" src="https://cloud.githubusercontent.com/assets/730388/19317080/d033102a-9071-11e6-94d7-99f66988787f.png">

**Comment by jkmarx** [comment]
![firefox-fixed](https://user-images.githubusercontent.com/9956764/35021596-9447347a-faff-11e7-8f82-cba641657e13.gif)
