### ISSUE TITLE
Django-Rest Swagger Broken on Test Site

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#1470]
Specific code commit: 7969dc1
Version of the web browser and OS: 49.0.1, 10.11.6 El Capitan
Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): https://test.stemcellcommons.org/#/
### Steps to reproduce

Please list all the actions and the input data used:
1. Go to  https://test.stemcellcommons.org/docs/
### Observed behavior

<img width="1121" alt="screen shot 2016-10-13 at 1 30 14 pm" src="https://cloud.githubusercontent.com/assets/9956764/19359682/37013340-9149-11e6-820d-5a7cd74b35ce.png">

Console Errors:
`shred.bundle.js:2609 Mixed Content: The page at 'https://test.stemcellcommons.org/docs/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://test.stemcellcommons.org/docs/api-docs/'. This request has been blocked; the content must be served over HTTPS.`
### Expected behavior

Swagger to work correctly and no errors.

**Comment by hackdna** [comment]
Need to configure the `/docs/api-docs/` URL access via HTTPS.

**Comment by jkmarx** [comment]
We can't upgrade django swagger to 3.5.1 until django rest is updated to 3.5.1. Django Rest can't be updated until we upgrade Django to 1.8.

**Comment by hackdna** [comment]
What is the root cause for this problem? Why is it necessary to upgrade django-rest-swagger to v2.0.5 to fix it?
