### ISSUE TITLE
File Broswer/ Visualiztion should utilize `auxiliary_file_generation_task_state`

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#1484]
The Node API V2 returns a field called `auxiliary_file_generation_task_state`, which is simply the status of the accompanying Celery task for the creation of an auxiliary file.

We should have some indicator or icon letting our users know that they may not be able to reap all of the benefeits of a given viz tool.

For example, **IGV** can't zoom to the base-pair level on large `.bam` without a `.bam.bai` file.

There is also a field returned by this api that is a more simplistic boolean called: `ready_for_igv_detail_view`

**Comment by jkmarx** [comment]
Node API V2 revised to not include field.
