### ISSUE TITLE
After migration of repo, reconnect travis

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1493]
I expect we'd lose the history of earlier tests, but otherwise shouldn't be difficult.

**Comment by hackdna** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Move Refinery repo in Github](https://trello.com/c/iIOWxXnm/329-move-refinery-repo-in-github)

**Comment by scottx611x** [comment]
This was done automatically during the move to `refinery-platform` organization
