### ISSUE TITLE
Sorting Datasets by name is case-dependent

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#1530]
* Specific code commit: e81a3d9f9f7304506ba10e7753638b5ebc5fc705
* Version of the web browser and OS: `Firefox 49.0.2 Ubuntu 16.04 LTS`
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): 
https://test.stemcellcommons.org

### Steps to reproduce
Please list all the actions and the input data used:

1. On the dashboard, use the sorting functionality to sort Datasets by name in ascending order.

### Observed behavior
- DataSets whose names begin with a lowercase character are ranked below any Datsets whose names begin with an uppercase character.

See:
![screen shot 2016-11-16 at 2 51 47 pm](https://cloud.githubusercontent.com/assets/5629547/20363221/68270d40-ac0c-11e6-8e10-10d7ef7aa665.png)

### Expected behavior
* For Datasets to be sorted alphabetically regardless of case.

**Comment by jkmarx** [comment]
The client does not sort the data sets.

**Comment by jkmarx** [comment]
http://lucene.472066.n3.nabble.com/SOLR-Lucene-sorting-Question-requesting-suggestion-td481965.html

https://wiki.apache.org/solr/AnalyzersTokenizersTokenFilters#solr.LowerCaseFilterFactory

**Comment by jkmarx** [comment]
Related to #337

**Comment by jkmarx** [comment]
Since this is solr's default, I'm going to make it an enhancement instead of a bug.

**Comment by mccalluc** [comment]
(In that same bit of machinery, might look at handling of initial article.)

**Comment by jkmarx** [comment]
With v1.6.9 Explore/Satori has been removed.
