### ISSUE TITLE
DataSet Explorer: the preview link's tooltip can stay permanently

### ISSUE THREAD

**Issue by flekschas** [refinery-platform/refinery-platform#1540]
* Specific code commit: https://beta.stemcellcommons.org
* Version of the web browser and OS: Mac + Chrome (latest)
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): https://beta.stemcellcommons.org

### Steps to reproduce
1. Mouse over the links and scroll. It doesn't happen all the time but sometimes.

I think this is caused by an open tooltip which root / base element is gone before it faded out properly. In that case the tooltip stays forever.

### Observed behavior
![bildschirmfoto 2016-11-29 um 09 24 52](https://cloud.githubusercontent.com/assets/932103/20713326/e00622c0-b615-11e6-8452-c81f047545f8.png)

![bildschirmfoto 2016-11-29 um 09 30 54](https://cloud.githubusercontent.com/assets/932103/20713510/8dd36ad4-b616-11e6-9b56-f4a7147b0023.png)

### Expected behavior
- Only one tooltip should be shown at all times.
- The tooltip pops up and disappears all the time during scrolling which is kind of distracting. Maybe it should be disabled, i.e., hidden, entirely during scrolling (+ a few milliseconds after the scroll event ended)

**Comment by jkmarx** [comment]
With v1.6.9 Explore/Satori has been removed.
