### ISSUE TITLE
Jumpy dataset list on the data explorer

### ISSUE THREAD

**Issue by flekschas** [refinery-platform/refinery-platform#1549]
* Specific code commit: 40820a779698c6e1c678fad190307234e20375fd
* Version of the web browser and OS: Mac + Chrome
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): AWS

### Steps to reproduce
1. Login to http://satori.cloud.refinery-platform.org/account/login (ask me for credentials)
2. Scroll the **very end** of the dataset list
3. Now you should see this jumpy behavior

### Observed behavior
![jumpy dataset list](https://cloud.githubusercontent.com/assets/932103/20888746/2e6780e6-bace-11e6-8ea6-ee7db528050f.gif)

It seems like the scroll list jumps back to its original position.

### Expected behavior
Should scroll normally

**Comment by jkmarx** [comment]
With v1.6.9 Explore/Satori has been removed.
