### ISSUE TITLE
Ontology term box tabs are mis-positioned on FF

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1551]
* Specific code commit: e7bf4f1009902c807c6bfa52259e72557c3a0ea2 
* Version of the web browser and OS: 47.0.1
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): beta.stemcellcommons.org

### Steps to reproduce
Please list all the actions and the input data used:

1. Bring up the dashboard
2. Click "Explore"
3. Hover over ontology terms

### Observed behavior
The horizontal tabs extending from the terms are mis-positioned and float in and out of the frame.

<img width="618" alt="screen shot 2016-12-05 at 3 24 43 pm" src="https://cloud.githubusercontent.com/assets/730388/20901134/1ff1d38c-baff-11e6-81cf-5865670a1ad5.png">

### Expected behavior
* Behavior should match that on Chrome.

**Comment by hackdna** [comment]
Same is #1403?

**Comment by mccalluc** [comment]
Perhaps there's some common underlying problem with horizontal position on FF, but no, I don't think these are dupes.

**Comment by jkmarx** [comment]
With v1.6.9 Explore/Satori has been removed.
