### ISSUE TITLE
Account activation welcome email is incorrect

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#1578]
* Specific code commit: 7cd0938e3982eb6540f242a78e97f2f9a0c75fba
* Version of the web browser and OS: `Chrome  54.0.2840.59 (64-bit) Ubuntu 16.04 LTS`
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): 
test.stemcellcommons.org

### Steps to reproduce
Please list all the actions and the input data used:

1. Register for a new account and have an admin activate said account.

### Observed behavior
1. Email to user has the incorrect information:
     ```
     Your account has been activated! 
     To log into Refinery, please follow this link and use your username or email address and
     password provided when you registered: 
     http://192.168.50.50:8000/accounts/login/ 
     If you have any questions, please contact the Refinery team at admin@example.org
     ```
2. See: https://github.com/refinery-platform/refinery-platform/blob/6577086e2257a0f79ae6c4089037109a8cc2dfda/refinery/config/config.json.erb#L116

### Expected behavior
* `config.json.erb` should use the proper configured values instead of  the hardcoding happening in `REFINERY_WELCOME_EMAIL_MESSAGE`

**Comment by hackdna** [comment]
This can be fixed by adding `REFINERY_WELCOME_EMAIL_MESSAGE` with appropriate value to `config.yml` before you spin up a stack (it is already present in `config.yml.template`). Perhaps we need better documentation for AWS deployment.

**Comment by hackdna** [comment]
Also, HTTPS is not set correctly in other templates. For example:
```
Your analysis successfully completed.  View your results here: http://test.stemcellcommons.org/data_sets/d19e80e2-8459-45e2-9dd1-8301c96b00b5/analysis/b315571d-8eda-499b-944e-3057dc9a6001
```

**Comment by jkmarx** [comment]
Closing as this issue is resolved. Note, the last comment is a separate issue.
