### ISSUE TITLE
"Add all to DataCart" star is broken

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#1579]
* Specific code commit: 7cd0938e3982eb6540f242a78e97f2f9a0c75fba
* Version of the web browser and OS: `Chrome  54.0.2840.59 (64-bit) Ubuntu 16.04 LTS`
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): 
test.stemcellcommons.org

### Steps to reproduce
Please list all the actions and the input data used:

- Click on the Star icon next to the # of total datasets on the Dashboard page

### Observed behavior:

- DataCart is not populated and this console error pops up:
```
TypeError: Cannot read property 'id' of undefined
    at a (commons.js:4315)
    at d.add (commons.js:4371)
    at p.<anonymous> (dashboard.js:2028)
    at angular.js:16606
    at m.$eval (angular.js:17913)
    at m.$digest (angular.js:17727)
    at m.$apply (angular.js:18021)
    at angular.js:18322
    at e (angular.js:6035)
    at angular.js:6314
(anonymous) @ angular.js:14110
(anonymous) @ angular.js:10633
(anonymous) @ angular.js:16614
$eval @ angular.js:17913
$digest @ angular.js:17727
$apply @ angular.js:18021
(anonymous) @ angular.js:18322
e @ angular.js:6035
(anonymous) @ angular.js:6314
```

### Expected behavior
- For all Datasets to be added to the DataCart

**Comment by jkmarx** [comment]
@scottx611x Duplicate issue #1552

**Comment by scottx611x** [comment]
@jkmarx Good find, thanks
