### ISSUE TITLE
Reference loading indictator should timeout 

### ISSUE THREAD

**Issue by flekschas** [refinery-platform/refinery-platform#1587]
* Specific code commit: http://satori.cloud.refinery-platform.org/
* Version of the web browser and OS: any
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): all

### Steps to reproduce
1. Open a preview with references

### Observed behavior
* The reference APIs of PubMed don't seemed to be stable and time out from time to time but the loading indicator keeps animating forever

![ref-load-indicator](https://cloud.githubusercontent.com/assets/932103/21933887/3c1fc232-d975-11e6-993a-93476a12be2f.gif)

### Expected behavior
* After 20-30 seconds the indicator should turn into a message saying that the references could be loaded.

**Comment by flekschas** [comment]
Addressed in #98f0fb0d23d7b6c395a8fedad559ebcca073c539

**Comment by jkmarx** [comment]
With v1.6.9 Explore/Satori has been removed.
