### ISSUE TITLE
Data set sharing list in File Browser 2 too comprehensive

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#1600]
* Specific code commit: 00795603a7ff0b8c45bd6e3ac0d84ab57decc6bc
* Version of the web browser and OS: Mac OS X
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): production

### Steps to reproduce
Please list all the actions and the input data used:

1. View "Details" tab in File Browser 2 for any data set

### Observed behavior
* List of "Groups" in "Sharing" section includes all groups that the current user is a member of.

### Expected behavior
* "Groups" should only show groups that the current user is a member of *and* that have _read_ or _modify_ access to the data set. If that results in no groups, "Not shared with any groups." (or similar) should be shown.

**Comment by jkmarx** [comment]
@ngehlenborg For admins, same filter?
