### ISSUE TITLE
DataSet Enhancement - Add how-to intro

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#1616]
File upload UI will provide "Before You Get Started" information

- [x] Ask Nils for text
- [x] ?? Just adding intro text

**Comment by ngehlenborg** [comment]
Let's make this a bullet point list. Could we take this from the tutorial?

Key points:

1. Have you meta data ready. The list of files and the associated meta data should be final before you start uploading your data set.
2. Uploading files is easier when handled as a one-time operation rather than doing this in multiple steps.

Refer to written feedback from beta testers.

**Comment by drj11** [comment]
Where is the written feedback?

**Comment by jkmarx** [comment]
@ngehlenborg Do you know where the written feedback is?

**Comment by jkmarx** [comment]
1. Nothing is described before you upload your metadata, so I didn't realise I had to have a species column and had to edit my file and reupload.
2. I didn't understand what "source grouping" meant, something much simpler could be used like: select the column containing the unique sample name.
3. For the data file column, it would be useful to have an example of the "path" as I wasn't sure what format would work.
4. I misunderstood what the "URL shortcut" meant, mainly because of the "example.com" rather than stemcellcommons.org. [drj adds: possibly we could add this ability after upload and then remove it from upload to avoid clutter]
5. Didn't know what "base path" meant.
6. Looking at it again, I also don't know what "optional upload data files" fully means - is this the sample files? How does it link it to the metadata entry? What if you upload something that doesn't quite match the name in the meta data?

**Comment by ngehlenborg** [comment]
@jkmarx: proposed "Before You Get Started" text (note that the "Download an example tabular metadata file. The first row needs to contain column headers." line gets moved into the new section):

#### Before You Get Started
---

Before uploading a data set, you should follow these steps to prepare your metadata and data files:

  1. Your metadata file needs to contain at least three columns: a _sample identifier_, a _file name_, and a _species name/species identifier_. Additional columns should be provided to characterize your data. The first row of the table needs to contain column headers, which can be chosen by the user. The order of the columns can be arbitrary.  [Download an example tabular metadata file]().
  1. Data referenced in the _file name_ column of the metadata file should either be located on your computer for upload to this site through your browser or located on a web server accessible through public URLs.

The upload process is not designed to be iterative, it pays off to spend some time to prepare both metadata and data files to avoid having to repeat the process.

**Comment by ngehlenborg** [comment]
Additional revisions for required fields on the upload page:

**Title** (split into on page and popup)
_Page_: Update the title of the data set to be imported.
_Popup_: This will be shown in the data set browser.

**Sample Identifier** (modify and split)
_Page_: Select a containing the sample identifier or multiple columns that will concatenated to form an identifier. 
_Popup_: Values in the selected columns will be concatenated to create an identifier for the "source" of the data. Each unique value will be treated as a separate source identifier. If necessary, up to three columns can be selected and concatenated to create unique source names. At least one column needs to be selected.

**Data File Column** (modify and split) 
_Page_: Column that contains the name or URL of a data file. 
_Popup_: File names must not contain a path. If URLs are provided, they have to be publicly accessible. 

**Species Column** (modify and split)
_Page_: Column containing species names or identifiers.
_Popup_: Acceptable identifiers are defined by the [NCBI Taxonomy](https://www.ncbi.nlm.nih.gov/Taxonomy) database. For example, for human samples "Human", "Homo sapiens", or "H. sapiens" can be used.

**Comment by ngehlenborg** [comment]
We will address this other issues separately.

**Comment by jkmarx** [comment]
@ngehlenborg Ilya pointed out "Sample Identifier (modify and split)
Page: Select a containing the sample identifier or multiple columns that will concatenated to form an identifier."  Should the text say "Select the sample identifier or multiple columns that will concatenated to form an identifier."

**Comment by hackdna** [comment]
I would even try to be more explicit. Something like: "Select a column with all unique values to use as sample IDs or if no single column contains unique values select multiple columns that will be concatenated to form unique IDs."
