### ISSUE TITLE
Dataset sharing/unsharing with Public Group leaves UI artifacts

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#1618]
* Specific code commit: 00cc0a962a09e73754b16944a6d43db4ed127cec
* Version of the web browser and OS: `Chrome 54 & Firefox 49 Ubuntu 16.04 LTS`
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): https://test.stemcellcommons.org

### Steps to reproduce
Please list all the actions and the input data used:

1. Share a Dataset that you own with the Public group with `Read Only` permissions
2. Stop sharing said Dataset with the Public Group
3. API responses from `/api/v1/data_sets/<uuid>` & `/api/v1/data_sets/<uuid>/sharing` will provide the correct information in the `public` field and `read` permission field, but the UI provides incorrect information.
4. Refreshing or hard reloading the page does not Remove the Globe showing incorrectly on the unshared Dataset

> Note: The only way I've been able to clear the public Globe icon from said Dataset is by opening the sharing modal for another Dataset that I own and saving it without changing any permissions.

### Observed behavior
- `api/v1/data_sets/09d0b5f7-56ce-40eb-889b-e0b2050f11a9/?format=json` after sharing from ui:
```diff
{
"accession": null,
"accession_source": null,
"analyses": [],
"creation_date": "2016-12-05T13:04:10.802789",
"date": "2016-12-05T13:27:12.983703",
"description": "",
"file_count": 14,
"file_size": 304757648,
"id": 113,
"is_owner": true,
"is_shared": true,
"modification_date": "2016-12-07T12:24:50.016107",
"name": "hg19-metadata-local",
"owner": "c68451bd-a4aa-4c48-a7d5-85e72759b64d",
++"public": true,
"resource_uri": "/api/v1/data_sets/09d0b5f7-56ce-40eb-889b-e0b2050f11a9/",
"share_list": null,
"slug": null,
"summary": "",
"title": "hg19-metadata-local",
"uuid": "09d0b5f7-56ce-40eb-889b-e0b2050f11a9",
"version": 2
}
again w/ sharing kwarg

{
"owner": "c68451bd-a4aa-4c48-a7d5-85e72759b64d",
"share_list": [
{
"group_id": 101,
"group_name": "Testing",
"group_uuid": "0ce973e1-a89a-4803-9117-f02927980029",
"perms": {
"change": false,
"read": false
}
},
{
"group_id": 100,
"group_name": "Public",
"group_uuid": "bd359b17-ae44-424a-9d5b-d549e093919b",
"perms": {
"change": false,
++"read": true
}
}
]
}
```
- same endpoint after unsharing from UI:
```diff
{
"accession": null,
"accession_source": null,
"analyses": [],
"creation_date": "2016-12-05T13:04:10.802789",
"date": "2016-12-05T13:27:12.983703",
"description": "",
"file_count": 14,
"file_size": 304757648,
"id": 113,
"is_owner": true,
"is_shared": false,
"modification_date": "2016-12-07T12:24:50.016107",
"name": "hg19-metadata-local",
"owner": "c68451bd-a4aa-4c48-a7d5-85e72759b64d",
++"public": false,
"resource_uri": "/api/v1/data_sets/09d0b5f7-56ce-40eb-889b-e0b2050f11a9/",
"share_list": null,
"slug": null,
"summary": "",
"title": "hg19-metadata-local",
"uuid": "09d0b5f7-56ce-40eb-889b-e0b2050f11a9",
"version": 2
}
again w/ sharing kwarg:

{
"owner": "c68451bd-a4aa-4c48-a7d5-85e72759b64d",
"share_list": [
{
"group_id": 101,
"group_name": "Testing",
"group_uuid": "0ce973e1-a89a-4803-9117-f02927980029",
"perms": {
"change": false,
"read": false
}
},
{
"group_id": 100,
"group_name": "Public",
"group_uuid": "bd359b17-ae44-424a-9d5b-d549e093919b",
"perms": {
"change": false,
++"read": false
}
}
]
}
```

- Showing the odd sharing/unsharing bhavior
![feb-22-2017 12-36-57](https://cloud.githubusercontent.com/assets/5629547/23224268/a93c1eec-f8fb-11e6-93f6-2e226f345709.gif)

- Showing how I've been able to remove the Globe icon
![feb-22-2017 12-39-15](https://cloud.githubusercontent.com/assets/5629547/23224363/0c64c55a-f8fc-11e6-9b85-349d9428c353.gif)

### Expected behavior
* For the UI to properly display dataset sharing information.

**Comment by jkmarx** [comment]
@jkmarx Check if this issue is on the dashboard

**Comment by jkmarx** [comment]
Not an issue on the dashboard. Launch pad was removed in the last release v1.6.8, so no longer an issue.
