### ISSUE TITLE
Move "URL shortcut" field from upload page to data set details in file browser

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#1629]
It is not necessary to set this during upload and is distracting to users without prior experience with the system.

This feature should be located next to edit features for other data set details, such as title, description etc.

_This is dependent on availability of other data set detail editing capabilities in the data set preview and new file browser._

**Comment by mccalluc** [comment]
You can now edit the shortcut with the other metadata, so it should be easy to remove it from the old place.
