### ISSUE TITLE
"?" help icon should be consistent across pages

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#1633]
On the Upload page the icon looks like this (small & light blue) and **shows the default (arrow) cursor when hovered**:

![image](https://cloud.githubusercontent.com/assets/1216518/23923252/48f23e5e-08dc-11e7-8175-abe381e38e52.png)

In the File Browser the icon looks like this (bigger and darker blue) and **shows the hand cursor when hovered**:

![image](https://cloud.githubusercontent.com/assets/1216518/23923275/638e91c2-08dc-11e7-8965-a821677a74ce.png)

The color and cursor from the File Browser should be applied to the help icons on the Upload page.

I am not sure about the size, given that there are so many of those icons on the upload page, we might not want to make them any bigger.

**Comment by jkmarx** [comment]
@ngehlenborg The color for the ? in the file browser is the default link color as oppose to the custom blue used here and the file browser two ?. An option would be to change all the ? to the primary blue button, but since it's an info popover, designating a specific color could be useful. Since it's not a link which redirects, I don't recommend using the default link color.

**Comment by ngehlenborg** [comment]
I agree that the primary button color is not the best choice here. Do we have a secondary button color? If so, we could use that.

Or maybe gray (which is our non-primary button color at the moment) would be sufficient for these buttons? I think people will look for the question mark once they are done reading the text next to it and are looking for an explanation or clarification, so it doesn't have to stand out.

**Comment by jkmarx** [comment]
@gray-light
<img width="1181" alt="screen shot 2017-03-15 at 11 03 46 am" src="https://cloud.githubusercontent.com/assets/9956764/23955028/1d4d08e0-096f-11e7-9f59-f31e1e500c40.png">

Default button color
<img width="1115" alt="screen shot 2017-03-15 at 11 02 10 am" src="https://cloud.githubusercontent.com/assets/9956764/23955027/1d40fa00-096f-11e7-9625-c66e773e7330.png">

**Comment by jkmarx** [comment]
@ngehlenborg The analysis status unknown uses the same icon and a slate gray.
