### ISSUE TITLE
spacing in About page layout is broken

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#1640]
* Specific code commit: 5965130ef900c1d66e56bcd0d851d6e254cbeb8c
* Version of the web browser and OS: Chrome Version 57.0.2987.110 (64-bit) on Mac OS X 10.12 
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): https://beta.stemcellcommons.org/about/

### Steps to reproduce
Please list all the actions and the input data used:

1. Go to https://beta.stemcellcommons.org/about/. 

### Observed behavior
* No space between browser frame and content blocks
* No space between content blocks

![image](https://cloud.githubusercontent.com/assets/1216518/24114148/8c8ce6c6-0d75-11e7-90fc-55790219c768.png)

### Expected behavior
* Spacing like on https://beta.stemcellcommons.org between content blocks.

**Comment by jkmarx** [comment]
FIXED snapshot. 
<img width="1439" alt="screen shot 2017-03-20 at 3 21 45 pm" src="https://cloud.githubusercontent.com/assets/9956764/24117527/fae8ee8e-0d80-11e7-990f-2883b7c3d677.png">
