### ISSUE TITLE
on AWS, automatically rotate backups

### ISSUE THREAD

**Issue by drj11** [refinery-platform/refinery-platform#1648]
Backups on AWS are currently made automatically.

They appear as RDS- and EBS- snapshots.

Problem: Eventually an account will run into the limit of manual snapshots it can take.

Further Problem: Which means that CloudFormation will fail to delete a stack (it complains that it can't take a final snapshot).

Backups need to be identified and deleted according to some sort of reasonable retirement policy.

**Comment by hackdna** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Backups on AWS are not rotated after two weeks](https://trello.com/c/CSyTLaJP/361-backups-on-aws-are-not-rotated-after-two-weeks)

**Comment by drj11** [comment]
- [ ] Tag EC2 instance so that scheduler rotates them out
- [ ] Document / enable launch of EBS Snapshot Scheduler
- [ ] retire RDS backups.

**Comment by drj11** [comment]
Now #1693 and #1717 are merged this can be closed.
