### ISSUE TITLE
Data file upload failure when data set is submitted before files are uploaded

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#1659]
* Specific code commit: afe887d
* Version of the web browser and OS: Firefox 52, OS X 10.11
* Environment where the error occurred: AWS instance

### Steps to reproduce
1. Navigate to the import form (`/data_set_manager/import/`)
1. Select a [data set](https://s3.amazonaws.com/data.cloud.refinery-platform.org/data/sample-data/E-MTAB-4119/e-mtab-4119-local.txt) that references [local](https://s3.amazonaws.com/data.cloud.refinery-platform.org/data/sample-data/E-MTAB-4119/sampleA1_1.fq) [files](https://s3.amazonaws.com/data.cloud.refinery-platform.org/data/sample-data/E-MTAB-4119/sampleA1_2.fq)
1. Add data files to the data upload section
1. Click Submit button to upload the data set

### Observed behavior
Data set appears to have been imported successfully but not all the data files are available in the data set browser view, for example:
![screen shot 2017-03-29 at 16 36 25](https://cloud.githubusercontent.com/assets/452575/24475472/f0d5cf7e-149d-11e7-82b0-c4e7ec1a38a7.png)

### Expected behavior
Submit button should stay inactive until there are no more data files left to upload

**Comment by scottx611x** [comment]
@hackdna, I've seen this happen with larger files before. I think the `import_file` task isn't very speedy. Does the lightning bolt go away after you refresh this page?

**Comment by hackdna** [comment]
The lightning bolt is still there and it's been more than half hour since I've imported the data set. I think the problem is that the redirect to the data set browser page occurs before the second file is transferred over the network, so the file import either never gets started or hangs/fails because there is no data file to process. Whatever the root cause is, no data files should be lost during import.

**Comment by ngehlenborg** [comment]
Need to deactivate "Submit" button until all file upload have completed.
