### ISSUE TITLE
PhantomJS causing OOM failures

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#1660]
PhantomJS processes sometimes fail to quit and keep occupying memory (~130MB each) which causes OOM failures

http://stackoverflow.com/questions/25110624/how-to-properly-stop-phantomjs-execution

http://stackoverflow.com/questions/19139325/phantomjs-not-closing-and-leaving-orphan-processes

**Comment by hackdna** [comment]
I've noticed that this happens when I do `grunt test | less` (when there are so many errors that they scroll off the screen).
