### ISSUE TITLE
Turn on CORS on S3

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1669]
I think we're on the same page that the JSON passed to the visualization will contain S3 URLs for data files. These URLs will be of no use to client-side code unless they comply with same-host rules. I think the easiest thing is to turn on CORS for our S3 buckets. http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html

The alternative would be something like
- ~~To do this, for every hostname that will be running Refinery, and every bucket which could be referenced by that Refinery, we need to set up a subdomain CNAME,~~
- ~~*and*, we need to be sure that JSON provided to the visualization uses the appropriate CNAMEd hostname, for the instance we are running on.~~
- ~~*and*, running locally, you would want to have a hosts.txt entry to make localhost look like something else.~~

or
- ~~Proxy or cache remote files on refinery~~

**Comment by hackdna** [comment]
https://github.com/refinery-platform/refinery-platform/blob/hackdna/s3_static_files/deployment/stack.py#L446 :) Still testing and fixing minor bugs on that branch but expect to merge into develop today.

**Comment by scottx611x** [comment]
@hackdna Whats the state of this?

**Comment by hackdna** [comment]
CORS has been enabled on S3 buckets.
