### ISSUE TITLE
Use django_docker_engine's purge_inactive()

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1670]
There is already a method which should kill containers which have been inactive for a certain period of time. It needs to do more (ie, allow the container to start up again: https://github.com/refinery-platform/django_docker_engine/issues/36), but I don't think there's anything that would prevent us picking a timeout period, and having Refinery periodically call the method.

I think that right now an unrealistically short timeout period should be chosen, so it will get plenty of exercise.

- [ ] Override `Tool.delete()` (Keep in mind that Queryset.delete won't trigger the delete  method)
- [ ] Celery task?

**Comment by hackdna** [comment]
FYI, Amazon ECS can be configured to use [Service Auto Scaling](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-auto-scaling.html): "You can use these service utilization metrics to scale your service up to deal with high demand at peak times, and to scale your service down to reduce costs during periods of low utilization."

**Comment by mccalluc** [comment]
We need to have at least one tiny instance up all the time if we want response times shorter than a minute, and we're a long ways from needing more than one. I am working on bridging to ECS right now (which is a precondition to anything more complicated) and when that's done we can think about which direction is the best to elaborate.

**Comment by mccalluc** [comment]
fixed by #2103
