### ISSUE TITLE
Can't cleanly delete CloudFormation stack due to circular dependency

### ISSUE THREAD

**Issue by drj11** [refinery-platform/refinery-platform#1678]
(for tag `v1.5.5`commit abca28511c9646c389bd13927898d8d40935afa6)

When you try and delete a stack the delete operation will eventually fail.
At the moment this is merely annoying because
the failure only leaves behind a few security groups which do not cost anything.

But the undeleted security groups do clutter up the account.

The failure is something like:

```
 	15:53:26 UTC+0100 	DELETE_FAILED 	AWS::EC2::SecurityGroup 	ELBSecurityGroup 	resource sg-9f14bae0 has a dependent object
```

this happens because some of the security groups have circular dependencies (these circular dependencies were added in https://github.com/refinery-platform/refinery-platform/pull/1606 ).

While CloudFormation can create security groups with circular dependencies, apparently it can't delete them.

As a workaround I've tried deleting the egress rules from a security group by hand and trying the delete again.
It's take uncharacteristically long, even by CloudFormation standards.

**Comment by hackdna** [comment]
I might have seen this once but I was able to delete several stacks without issues. I think it's a transient error.

**Comment by drj11** [comment]
Think you're right. Transient. Closing.
