### ISSUE TITLE
Metadata field naming conflicts

### ISSUE THREAD

**Issue by gmnelson** [refinery-platform/refinery-platform#1699]
* Specific code commit: abca285
* Version of the web browser and OS: Unknown (user testing)
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): https://beta.stemcellcommons.org

### Steps to reproduce
Please list all the actions and the input data used:

1. Provide a metadata field during data set upload with the same name as an internally generated metadata field

### Observed behavior
<img width="199" alt="repeatinternalmetadatafield1" src="https://cloud.githubusercontent.com/assets/23487494/25535625/ca05fb9c-2c05-11e7-83b8-509854681064.png">
<img width="116" alt="repeatinternalmetadatafield2" src="https://cloud.githubusercontent.com/assets/23487494/25535632/cd788d6c-2c05-11e7-9ae0-42e203350eb8.png">

### Expected behavior
* Either need instruction to avoid naming conflicts or another solution to disambiguate internal and external metadata fields

**Comment by jkmarx** [comment]
For the hsci retreat, just adding a line about the reserved text but keeping issue open.

**Comment by jkmarx** [comment]
Resolved #3196
