### ISSUE TITLE
Collaboration/sharing updates

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#1707]
- [ ] Cross-reference collaboration/preview/file browser
- [ ] Add information to tutorial and FAQ

@jkmarx Sorry for the lack of info, I don't remember everything from the meeting earlier :/

Pic for reference: 
![metting_5_1_17](https://cloud.githubusercontent.com/assets/5629547/25587683/13478f72-2e73-11e7-883d-7056efbb4eb0.jpg)

**Comment by jkmarx** [comment]
@ngehlenborg 
## Collaboration Page
<img width="1438" alt="screen shot 2017-05-03 at 1 58 35 pm" src="https://cloud.githubusercontent.com/assets/9956764/25674402/b20ce300-3008-11e7-800e-b95e78afea36.png">
<img width="479" alt="screen shot 2017-05-03 at 1 58 27 pm" src="https://cloud.githubusercontent.com/assets/9956764/25674403/b20d1f14-3008-11e7-925e-2cd844a1e2c4.png">

## Permissions Editor 
<img width="605" alt="screen shot 2017-05-03 at 1 58 12 pm" src="https://cloud.githubusercontent.com/assets/9956764/25674404/b20e404c-3008-11e7-83eb-cb4b7ce34dde.png">
<img width="601" alt="screen shot 2017-05-03 at 1 57 59 pm" src="https://cloud.githubusercontent.com/assets/9956764/25674406/b2106872-3008-11e7-8f23-6461342fb86e.png">

## File Browser Sharing
<img width="1431" alt="screen shot 2017-05-03 at 1 39 51 pm" src="https://cloud.githubusercontent.com/assets/9956764/25674407/b217cf4a-3008-11e7-8367-5c1f8b9ff45f.png">

**Comment by ngehlenborg** [comment]
Thanks @jkmarx! In my opinion that is exactly what we need. @sjhosui: what do you think?

**Comment by sjhosui** [comment]
Looks good. Can we change the text to “Only data set owners can change sharing options. To share with an authenticated user, create a new group or invite the user to an existing group on the collaboration page. Owners can update data set permissions (including making it public) on the data set preview by clicking the “sharing” button”.

Also for the permissions editor, I suggest: “Select groups you would like to access this data set. To share…”
