### ISSUE TITLE
Dashboard: Filter with Groups Bug

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#1724]
* Specific code commit: 34678985d9904406311d556150f1a01bd01acf2c
* Version of the web browser and OS: Version 58.0.3029.110 (64-bit), v10.11.6
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): 
Test site

### Steps to reproduce
Please list all the actions and the input data used:

1. On the dashboard, select own or public
2. Then select a group set

### Observed behavior
![dashboard-filter-bug](https://cloud.githubusercontent.com/assets/9956764/25968994/5c4969c0-3661-11e7-81f2-d398f2249d35.gif)

### Expected behavior
Should show the intersection

**Comment by mccalluc** [comment]
Think I've rediscovered this. To describe it another way:
- Selecting a group does not add another filter to "Own" and "Public": It overrides those filters and only filters by group.
