### ISSUE TITLE
Workflow Detail Page: Toggle Bug

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#1725]
* Specific code commit: 34678985d9904406311d556150f1a01bd01acf2c
* Version of the web browser and OS: Version 58.0.3029.110 (64-bit), v10.11.6
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): 
Test site

### Steps to reproduce
Please list all the actions and the input data used:

1. Click on 'Toggle selection details'

### Observed behavior
![screen shot 2017-05-11 at 4 06 59 pm](https://cloud.githubusercontent.com/assets/9956764/25969719/fd938bec-3663-11e7-852b-9955e7d70efb.png)

### Expected behavior
Should toggle.

**Comment by scottx611x** [comment]
@jkmarx It seems like this toggles fine after an element of the workflow has been selected

**Comment by mccalluc** [comment]
(I was confused by the same thing just now: On initial page load, I'm expecting that link to do something, or else why is it there? But not a big deal.)
