### ISSUE TITLE
Group Details: Empty Names

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#1726]
* Specific code commit: 34678985d9904406311d556150f1a01bd01acf2c
* Version of the web browser and OS: Version 58.0.3029.110 (64-bit), v10.11.6
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): 
Test site

### Steps to reproduce
Please list all the actions and the input data used:

1. Go to the public group page, https://test.stemcellcommons.org/groups/bd359b17-ae44-424a-9d5b-d549e093919b/

### Observed behavior
![screen shot 2017-05-11 at 4 09 46 pm](https://cloud.githubusercontent.com/assets/9956764/25969838/62a9109c-3664-11e7-8056-ba4d1cfaf410.png)

### Expected behavior
Empty names shouldn't show

**Comment by hackdna** [comment]
Also, inactive accounts shouldn't be displayed.

**Comment by scottx611x** [comment]
These two empty names are for `admin` and `AnonymousUser` 
![screen shot 2017-05-11 at 4 15 47 pm](https://cloud.githubusercontent.com/assets/5629547/25970043/46a398c6-3665-11e7-94d5-10ff7e9656b4.png)

**Comment by scottx611x** [comment]
![screen shot 2017-05-11 at 4 15 47 pm](https://cloud.githubusercontent.com/assets/5629547/25970051/53a54b96-3665-11e7-9130-73b4afa1141e.png)

**Comment by jkmarx** [comment]
Nils commented this will be resolved with the views update.
