### ISSUE TITLE
Analysis Filtering Discrepancy FF vs. Chrome

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#1728]
* Specific code commit: 34678985d9904406311d556150f1a01bd01acf2c
* Version of the web browser and OS: `Chrome Version 54.0.2840.59 (64-bit) & Firefox 53.0.2 (64-bit) - Ubuntu 16.04 LTS`
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): 
https://test.stemcellcommons.org

### Steps to reproduce
- Attempt to use the `Analysis` filtering functionality within the aforementioned browsers/OS.

### Observed behavior
**FF closes the popover upon any radio or asc./desc. click**
![bug](https://cloud.githubusercontent.com/assets/5629547/26001834/a7f3e4a0-36fb-11e7-93b7-830c532913c0.gif)
**Chrome does not close the popover upon any radio or asc./desc. click**
![no_bug](https://cloud.githubusercontent.com/assets/5629547/26001838/ac28c7ca-36fb-11e7-80e6-5db6acf42858.gif)

### Expected behavior
* Not sure...
    - On one hand its nice to be able to see what you're filtering for rather than have the popover hide the first ~4 results (in the case where the popover automatically closes)
    - On the other hand, it's also nice to be able to chain the radios & asc./desc. filters together without having to keep re-opening the filter popover

**Comment by jkmarx** [comment]
Dashboard revamp will remove this column completely.
