### ISSUE TITLE
Canceling analysis does not terminate file import tasks

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#1730]
* Specific code commit: f941f91
* Version of the web browser and OS: any
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): AWS

### Steps to reproduce
1. Start an analysis that requires file import
2. Cancel the analysis while a file import task is running

### Observed behavior
Analysis is canceled but the file import task continues running which results in a blocked file_import queue and could prevent other actions that require file import like analyses and data set imports from completing.

Example
the task in STARTED state is blocking the four subsequent file import tasks from running (RECEIVED state):
![screen shot 2017-05-12 at 15 10 12](https://cloud.githubusercontent.com/assets/452575/26014065/19fe7498-3729-11e7-97ca-d9c45136271f.png)

This prevents data set import from completing:
![screen shot 2017-05-12 at 15 16 56](https://cloud.githubusercontent.com/assets/452575/26014068/1cf5291c-3729-11e7-86a3-1252115fdfb7.png)

### Expected behavior
File import tasks should be terminated.

### Notes
Potential solution:
```python
celery.task.control.revoke(task_id, terminate=True)
```
http://stackoverflow.com/questions/8920643/cancel-an-already-executing-task-with-celery

**Comment by scottx611x** [comment]
closed by #1747
