### ISSUE TITLE
Tidy up enormous function in stack.py

### ISSUE THREAD

**Issue by drj11** [refinery-platform/refinery-platform#1736]
the `make_template` function is way too big, and should be split up.

Probably something like:

    make_instance(...)
    make_volume(...)
    make_rds(...)
    ...

**Comment by hackdna** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor stack.py](https://trello.com/c/VcvEgD56/124-refactor-stack-py)

**Comment by hackdna** [comment]
We should probably evaluate a replacement for cfn-pyplates (Terraform?) before we start refactoring. See the Trello card linked above for details.

**Comment by hackdna** [comment]
Replaced by #2602
