### ISSUE TITLE
Should Solr run on Travis?

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1760]
Should Solr run on Travis? Is it running already? [This script](https://github.com/moliware/travis-solr) isn't too complicated and seems like a good place to start.

(On a closer look, that script assumes only one core, I think.)

**Comment by hackdna** [comment]
No external APIs (like Solr) should be necessary for running unit tests: any interaction should be mocked. However, it is different for integration testing: https://softwareengineering.stackexchange.com/a/65480.

**Comment by mccalluc** [comment]
I believe that our travis run does encompass integration tests, and since there are a lot of details in the solr configuration that matter, I would expect them to be tested, but I don't see that they are: That's really my question.

I'm looking at changing `UserFilesAPITests` over to an `APITestCase` and need to understand how to make that work when I'm not running a class-based view... and somewhere in there would be the details of mocking solr, I think?

**Comment by mccalluc** [comment]
Schema doesn't change often, and if it did break something, we'd notice. Adding solr to travis is high cost with minimal gain. (W/ Scott.)
