### ISSUE TITLE
Remove REFINERY_USER_AUTHENTICATED if unused

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1765]
refinery/templates/core/user_files.html :
```
    {% if user.is_authenticated %}
      var REFINERY_USER_AUTHENTICATED = true;
    {% else %}
      var REFINERY_USER_AUTHENTICATED = false;
```
The main problem would be if any kind of security relied on this...

**Comment by mccalluc** [comment]
```javascript
function updateDownloadButton(button_id) {
          if (query.getCurrentDocumentCount() > MAX_DOWNLOAD_FILES || query.getCurrentDocumentCount() <= 0 || !REFINERY_USER_AUTHENTICATED || ( showAnnotation && !allowAnnotationDownload )) {
```
I think this is just used to determine if a button should be shown. I also suspect that this button might not any longer be part of Refinery? I'm going to CC Scott, who was interested in looking at it a little closer, but I'll go ahead and close.

**Comment by mccalluc** [comment]
cc @scottx611x

**Comment by hackdna** [comment]
We should remove this variable if no longer used. Re-opening as a technical debt issue.
