### ISSUE TITLE
Upgrade Node.js to v8.x

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#1767]
[Node v8.0.0 was released on 2017-05-30](https://nodejs.org/en/blog/release/v8.0.0/). It includes npm version 5.0.0 which might help with the [intermittent build failures](https://github.com/npm/registry/issues/10) on TravisCI.

- [x] Upgrade puppet-nodejs to v4.0.0 

- [x] Update to nodejs v8 (npm v5 allows pinning)

puppet-nodejs Requires:
 Version 4.0.1 is compatible with:
Puppet Enterprise 2018.1.x, 2017.3.x, 2017.2.x, 2017.1.x, 2016.5.x, 2016.4.x
Puppet >=4.7.1 < 6.0.0

Ref #3096

**Comment by hackdna** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Upgrade Node.js to v8.x](https://trello.com/c/26gkiZp1/170-upgrade-nodejs-to-v8x)

**Comment by jkmarx** [comment]
Ref #3397
