### ISSUE TITLE
Upgrade NPM to sporadic Travis errors

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1768]
https://github.com/refinery-platform/refinery-platform/pull/1749#issuecomment-306521020

- First step would be to check what version Travis is giving us by default, and only if that is particularly old, try to update it. 
- Some folks reported that changing to http fixed things: There are good reasons not to do that in production, but I would be ok doing that just for Travis... though objections would be reasonable, too.
- Simply retrying might also get around the problem: If errors are independent, trying twice would radically reduce the already low error rate.

If neither of these seem to work, or seem appropriate, I think it would also be ok to close this issue, since we are pretty confident it has nothing to do with our code.

(In response to [Ilya](https://github.com/refinery-platform/refinery-platform/pull/1749#issuecomment-306537024), the advice seems to be upgrading npm, rather than node itself, though that might be a good thing, too.)

**Comment by hackdna** [comment]
[NPM is installed along with Node](https://github.com/refinery-platform/refinery-platform/blob/046c8ac130f364c7c9ebe991f9af24ed735f3aad/deployment/refinery-modules/refinery/manifests/init.pp#L82). Also, we should start using Puppet for Travis builds to ensure we have similar configuration for all environments.

**Comment by mccalluc** [comment]
#822 covers using puppet under travis, and hopefully that will fix this.

**Comment by mccalluc** [comment]
@hackdna : My sense is that setting up Puppet for Travis is more involved, and not something we'll get to immediately. Meanwhile, I continue to get NPM errors on Travis builds: Waiting for the build, only to need to restart it, is wasting time. Unless you strongly object, I would like to upgrade NPM on Travis now, unless you think puppet-on-travis really shouldn't take too long.

**Comment by hackdna** [comment]
OK but we should still update the Node/NPM in the Puppet manifest to match the new version of NPM in Travis.

**Comment by hackdna** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Upgrade Node.js to v8.x](https://trello.com/c/26gkiZp1/170-upgrade-nodejs-to-v8x)

**Comment by mccalluc** [comment]
Earlier commit should have auto-closed this. Closing.
