### ISSUE TITLE
Intro JS for the launchpad broken in repo mode

### ISSUE THREAD

**Issue by flekschas** [refinery-platform/refinery-platform#1773]
* Specific code commit: 91f5ccf05bc94eafdd48ca74643b77cf6b419a30
* Version of the web browser and OS: Chrome latest
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): macOS Sierre + VM

### Steps to reproduce
Please list all the actions and the input data used:

1. Enable repo mode
2. Open intro tutorial for the launchpad
3. Navigate to the second toolbox
4. Go to the last 2 tooltips.

### Observed behavior
* User has to scroll to the right
* Last 2 tooltips don't have an associated DOM element because the workflow and analysis panel are missing

![screen shot 2017-06-07 at 5 35 43 pm](https://user-images.githubusercontent.com/932103/26902624-f8ed4250-4ba7-11e7-913d-ff23816cf962.png)

### Expected behavior
* Horizontal scrolling should be avoided

**Comment by jkmarx** [comment]
With v1.6.9 Explore/Satori has been removed.
