### ISSUE TITLE
IntroJs tutorials are not checked until user refreshes page

### ISSUE THREAD

**Issue by flekschas** [refinery-platform/refinery-platform#1774]
* Specific code commit: 91f5ccf05bc94eafdd48ca74643b77cf6b419a30
* Version of the web browser and OS: macOS Chrome latest
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): VM

### Steps to reproduce
1. Complete a intro js tutorial

### Observed behavior
* Tutorial isn't checked until the user refreshes the page or goes to another page in Refinery
* Console outputs success though

![screen shot 2017-06-07 at 5 45 36 pm](https://user-images.githubusercontent.com/932103/26903004-83c7f360-4ba9-11e7-9108-85a368f36aa9.png)

### Expected behavior
* Tutorial should be checked right away

**Comment by jkmarx** [comment]
Ref #1417
