### ISSUE TITLE
DataSet Upload Intro JS logs comments to the console

### ISSUE THREAD

**Issue by flekschas** [refinery-platform/refinery-platform#1775]
* Specific code commit: 91f5ccf05bc94eafdd48ca74643b77cf6b419a30
* Version of the web browser and OS: macOS Chrome latest
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): VM

### Steps to reproduce
1. Do the DataSet Upload Intro JS tutorial
2. Watch console

### Observed behavior
* Logs stuff

![screen shot 2017-06-07 at 5 45 27 pm](https://user-images.githubusercontent.com/932103/26903082-cf305df6-4ba9-11e7-968e-9dc7b5afa90e.png)

### Expected behavior
* Shouldn't log stuff

**Comment by jkmarx** [comment]
Most of the consoles were removed previously, except for a success and error. Closing issue.
