### ISSUE TITLE
Postcss doesn't do anything

### ISSUE THREAD

**Issue by flekschas** [refinery-platform/refinery-platform#1778]
* Specific code commit: d82da24ae1fb4e28a5ad786dd059053bd41d73e0
* Version of the web browser and OS: macOs Chrome latest
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): vm

### Steps to reproduce
1. Check https://github.com/refinery-platform/refinery-platform/blob/develop/refinery/ui/Gruntfile.js#L153-L155

### Observed behavior
* Postcss takes CSS files as input but all our style files are `.less`
* Postcss would output files in `tmp` which is removed after Grunt finishes and the files are not copied over anywhere.

### Expected behavior
* Why is Postcss run?

**Comment by jkmarx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/refinery-platform/refinery-platform/issues/1778](https://trello.com/c/N9M2BkHG/172-https-githubcom-refinery-platform-refinery-platform-issues-1778)

**Comment by jkmarx** [comment]
Ref: https://github.com/refinery-platform/refinery-platform/issues/1528 
https://github.com/refinery-platform/refinery-platform/pull/1571/files

**Comment by jkmarx** [comment]
https://github.com/less/less-plugin-autoprefix
