### ISSUE TITLE
Better validation of Solr responses?

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1789]
Where we have something like:
```python
try:
   solr_response_json = json.loads(solr_response)
except TypeError:
   return "Error loading json."
```
I would like to append:
```python
assert solr_response_json['responseHeader']['status'] == 0, solr_response_json['error']['msg']
```
(and probably bundle it up as a utility method: I don't know how many places there are in our code where we hit solr.)

If the solr status is 0 (no error), there is no change in behavior.

If the solr status is non-zero, before:
- At some point latter in the code we will try to access a missing element in the result dict and throw a KeyError, with no other information to go on.

after:
- We will immediately throw an AssertionError, whose message contains the information we have from solr.

A good analogy might be the interface to a relational database: We would not catch explicitly catch segfaults or connection errors: There's no way to recover, so we just let the exception bubble up, and let Django take care of the 500.

This seems reasonable to me, but I haven't made a good case in the PR. I would like to get on the same page as you guys.

**Comment by hackdna** [comment]
Yes, it's fine to let exceptions propagate up the stack but at least explicitly raised [exceptions should still be handled](https://doughellmann.com/blog/2009/06/19/python-exception-handling-techniques/) and the docs for the function should describe the exceptions it raises.

**Comment by jkmarx** [comment]
It's fine.
