### ISSUE TITLE
Add new facets which don't care about diambiguation?

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1815]
For the user files browser, we want to be able to facet just like we can within a single dataset. This is hard because each dataset adds a uuid so its fields are named differently. I would like something like `facet.field=*`, [but that was proposed, and shot down](https://issues.apache.org/jira/browse/SOLR-247). If I can't do that, then I guess I would need to iterate over the entire found set to collection facet field names, and then hit solr again for the facets, and even with that, I would still need to figure out what to do when the user clicked on a single facet that corresponded to multiple underneath.

Alternate proposal: We add new indexes to solr that will be consistent across all datasets: If a particular record uses a given field twice, that's fine: it doesn't need to be unique.

Thoughts? cc: @jkmarx @scottx611x

**Comment by scottx611x** [comment]
Should we add an entirely new index? Or just a another field to the current `DataSetIndex`? 

I think adding a new `prepare` method to the index to normalize this data sounds like it would be sufficient, but I could not be understanding the problem fully.

**Comment by mccalluc** [comment]
Fixed in #1824
