### ISSUE TITLE
Data Set 2 - Add modal notification when clearing launch config

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#1832]
* Specific code commit: 4131d854bd8172d098616505756c18fda1d90e68

### Steps to reproduce
Please list all the actions and the input data used:

1. In data set 2 browser, select a tool and set up a launch config
2. Exit page or select a different tool

### Observed behavior
No notification the configs will be cleared

### Expected behavior
Either notification the configs will be cleared or configs will be saved

-- A pop up is current implemented in the meta data upload when exiting the page

**Comment by ngehlenborg** [comment]
Needs to be updated with custom modal rather than browser modal.

**Comment by jkmarx** [comment]
@scottx611x @mccalluc @ngehlenborg Instead of a modal, how about a confirmation popover with the same info.
![confirmation-button](https://user-images.githubusercontent.com/9956764/31725817-47f1ba30-b3f3-11e7-8795-8258775063d7.gif)

**Comment by scottx611x** [comment]
@jkmarx I like the confirmation popover idea! Just wondering where else this could be utilized.

I know of Dataset & Analysis deletion could both benefeit.
![screen shot 2017-10-18 at 2 13 28 pm](https://user-images.githubusercontent.com/5629547/31735052-a30e4cce-b40e-11e7-8780-a7b2c8adc3df.png)
![screen shot 2017-10-18 at 2 14 47 pm](https://user-images.githubusercontent.com/5629547/31735078-b92e0d6e-b40e-11e7-9753-965f1f7485b7.png)

**Comment by jkmarx** [comment]
![screen shot 2017-10-23 at 7 27 36 am](https://user-images.githubusercontent.com/9956764/31886853-0c26e3f2-b7c4-11e7-97eb-ed43ef528cfc.png)

Modal was already implemented.
