### ISSUE TITLE
See if number-underscore-number facet names are really necessary

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1852]
The work on user-files would have been easier if the same facet names were used across datasets. Are the unique field names really necessary? Investigate, and if possible, clean up. (Also, remember to clean up the `_generic_` fields I added as a kludge.)

chuck:
> This is a long shot, but are we sure the number-underscore-number facet names are necessary? If those two values are stored in their own fields, then it seems like you could constrain the query just on those two, and the remaining facet counts would not be across all records, but only those that matched? I’m probably missing something, but I couldn’t articulate to myself why it needs to work this way.
>
> In the background, I guess it’s that I’ve worked with a few solr-backed sites, that at least superficially needed to handle the same kind of faceting, but I haven’t seen the problem attacked this way before. (edited)

nils:
> *definitely not sure* that we need these kind of complex facet names.
>
> if you are aware of better solutions (e.g. the ones that you described), we can explore that.
>
> just keep in mind that there are a lot of pieces in refinery that might depend on this.

**Comment by jkmarx** [comment]
Right now, yes. It associates fields with a particular data set.
