### ISSUE TITLE
/user/files/ makes useless call to /api/v1/nodeset/

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1853]
* Specific code commit: c57fc63dabd8cb2d8c551d3eebcca6456ec748bb
* Version of the web browser and OS: mac / ff
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): local dev

### Steps to reproduce
Please list all the actions and the input data used:

1. Load http://192.168.50.50:8000/user/files/
2. Look in the console

### Observed behavior
* `POST http://192.168.50.50:8000/api/v1/nodeset/ 500 (INTERNAL SERVER ERROR)`

### Expected behavior
* There's no reason for this page to even hit that endpoint.

**Comment by jkmarx** [comment]
![screen shot 2017-10-26 at 10 56 31 am](https://user-images.githubusercontent.com/9956764/32060327-6c0f50c2-ba3c-11e7-8d16-0abedfc7612f.png)

I believe when you transitioned to the new file browser or when you cleaned up the user.html it resolved this issue. @mccalluc
