### ISSUE TITLE
When header wraps, top of body is obscured.

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1876]
All browsers / All recent versions

### Steps to reproduce

Narrow the window to a width where the header content needs to wrap

### Observed behavior

Body content is truncated at the top: It does not take account of the header using more space than it usually does.

<img width="678" alt="screen shot 2016-10-11 at 1 12 53 pm" src="https://cloud.githubusercontent.com/assets/730388/19280577/94d4bd0c-8fb4-11e6-8a15-736bed485699.png">

(Screen shot also demonstrates #1461)

### Expected behavior

With more headers on the beta site ("Collaboration Statistics About Original Site CSCB Home") it's easier to hit this.

For some widths, it also exactly obscures the "Registration for full access..." note, and it's not obvious that anything is missing.

-- Plan --
- [ ] Discuss & Mock-up suggestions for improving and fixing nav bar during resize
- [ ] Dashboard & File Browser: Reconsider location bar (is it useful)
- [ ] File Browser: Update tab for minimizing

**Comment by mccalluc** [comment]
Here's a better example of how it can be confusing: The tabs are cleanly truncated, and so unless you're pretty familiar with the software already, you might not realize that anything is missing:

![screen shot 2017-07-11 at 2 59 35 pm](https://user-images.githubusercontent.com/730388/28085406-a9adc662-6649-11e7-88c3-fa8d90b32a96.png)

**Comment by jkmarx** [comment]
Tackling this issue, it'd be worth while to investigate how we want to deal with the resizing. Current platform in Chrome.

**Comment by jkmarx** [comment]
![filebrowser](https://user-images.githubusercontent.com/9956764/34888731-606fdd8c-f799-11e7-8cad-54eff7fb597d.gif)

**Comment by mccalluc** [comment]
Similar, perhaps duplicate: #793

**Comment by jkmarx** [comment]
@mccalluc I'm going to say yes.

**Comment by jkmarx** [comment]
Ref #793
