### ISSUE TITLE
Data Set summary is exposed on private sets even with no login

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1888]
* Specific code commit: bc425b3403264b8a0fb1d28cd412a7360e05dc6b
* Version of the web browser and OS: FF MacOS
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Production

### Steps to reproduce
Please list all the actions and the input data used:

1. Login, and identify an unshared data set.
2. Click on it to get a preview URL
3. Log out, and then load that same URL

### Observed behavior
- The Preview will load, though with nothing highlighted on the left.

### Expected behavior
* Not sure: Maybe this is intentional, or maybe we're leaking information which should be private? If this is not the desired behavior, I'm not sure what is... Maybe a 404-equivalent only on the right-hand side?

**Comment by jkmarx** [comment]
With v1.6.9 Explore/Satori has been removed.
