### ISSUE TITLE
Discrepancies between "Details" tab: file browser 1 vs. 2

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#1890]
* Specific code commit: bc425b3403264b8a0fb1d28cd412a7360e05dc6b

**Changes to be made in File Browser 2:**
- [x] Extra `:` in title
- [ ] Missing `None:None` under `STUDIES`
- [x] Cleaner display of `DATA FILES`
- [x] Prettified dates under `HISTORY`
- [x] Missing `Not Available` under `META DATA`
- [x] Missing `Import into Own Space` button (add "?" info popover to this and have nicer button

## File Browser 1
![screen shot 2017-07-10 at 5 14 02 pm](https://user-images.githubusercontent.com/5629547/28040294-58110fe6-6593-11e7-8817-c82f3fb41992.png)

## File Browser 2
![screen shot 2017-07-10 at 5 13 51 pm](https://user-images.githubusercontent.com/5629547/28040295-58128150-6593-11e7-9f0e-6fd43e793a39.png)

**Comment by mccalluc** [comment]
> Missing `None:None` under `STUDIES`

This does not come through because in the source code we have
```
  <span ng-if="study.identifier">
    <strong>{{study.identifier}}</strong>
  </span>
  <span ng-if="study.title">
    : {{study.title}}
  </span>
```
... which seems more like a feature than a bug?

Also: New one is missing creation date of the current version: Should that also be ported from the old version?

**Comment by mccalluc** [comment]
TODO: deploy this, confirm that all the features are complete.

**Comment by scottx611x** [comment]
@mccalluc Everything looks good to me.
