### ISSUE TITLE
Does this analysis run state make sense?

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1892]
@scottx611x: will look into the pending state persisting for Refinery Import Stage

Started off several analyses with arbitrary files and I've got this state, which doesn't seem to be changing:
![screen shot 2017-07-10 at 7 12 14 pm](https://user-images.githubusercontent.com/730388/28044184-df3e9b0e-65a3-11e7-9fb6-52916850d79e.png)

- Can Galaxy Import be complete with Refinery Import is still Pending?
- What does it mean if the blue stripes don't have a number and never seem to change?

I'm not sure what kind of behavior would be reasonable.

https://test.stemcellcommons.org/data_sets2/1fc2e593-a265-49cb-a01a-ebc40017fec2/#/analyses/

The last of the three is reported as being at 5040%, and the number keeps increasing:

![screen shot 2017-07-10 at 7 24 34 pm](https://user-images.githubusercontent.com/730388/28044426-50c95114-65a5-11e7-9b5d-4741ec95ca12.png)

ok, now something seems to be resolved, though the first one is still weird:

![screen shot 2017-07-10 at 7 28 55 pm](https://user-images.githubusercontent.com/730388/28044574-2da6ceea-65a6-11e7-870b-32eef7dc4c83.png)

Should the icons be in sync? The first one is a gear in one place and a download icon in the other.

**Comment by scottx611x** [comment]
@mccalluc I haven't been able to reproduce this state yet, but will be good to keep an eye on. I checked out the celery logs and nothing looked out of place.

**Comment by scottx611x** [comment]
@mccalluc I have been running a lot of Analyses from FB2 lately and haven't run into this. Going to close.
