### ISSUE TITLE
FB2 analysis launch: "You can't execute queries until the end of the 'atomic' block."

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1894]
* Specific code commit: bc425b3403264b8a0fb1d28cd412a7360e05dc6b
* Version of the web browser and OS: FF MacOS
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Production

### Steps to reproduce
Please list all the actions and the input data used:

1. Uploaded the ISA-tab for "Genome-wide location analysis of BMP (SMAD1) in mouse erythroid progenitors co-occupted with lineage specific regulators (GATA1, GATA2) "
2. Selected "MACS2 ChIP-Seq"
3. Chose the first file for both elements of the pair

### Observed behavior
Raw POST:
```
{"dataset_uuid":"1fc2e593-a265-49cb-a01a-ebc40017fec2","tool_definition_uuid":"fcf99640-690c-45b1-989c-c481e31cfa2c","file_relationships":"[(02466024-6975-450b-8939-2288a4fac9d9,02466024-6975-450b-8939-2288a4fac9d9)]","parameters":{}}
```
Response:
```
An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
``` 

### Expected behavior
* There should at least be a user visible alert that something went wrong. I don't know whether the inputs I selected were invalid, or if there is another problem.

**Comment by scottx611x** [comment]
@mccalluc I haven't run into this in any of my recent analysis launches from FB2. I'm going to close.
