### ISSUE TITLE
In Recent Analyses list, percentage complete should be top-aligned.

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1895]
* Specific code commit: 
* Version of the web browser and OS: MacOS FF
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): 

### Steps to reproduce
Please list all the actions and the input data used:

1. Click on the gear in the upper right when the names are long enough to wrap

![screen shot 2017-07-10 at 7 24 34 pm](https://user-images.githubusercontent.com/730388/28044426-50c95114-65a5-11e7-9b5d-4741ec95ca12.png)

### Observed behavior
- Note that the percentage is aligned to the second line.

### Expected behavior
* It should be aligned with the first line

**Comment by jkmarx** [comment]
<img width="502" alt="screen shot 2017-10-16 at 12 07 33 pm" src="https://user-images.githubusercontent.com/9956764/31622515-9e1db894-b26a-11e7-8434-cca137445b83.png">
Fixed with PR #2230
