### ISSUE TITLE
Add Satori to manual testing

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1896]
If Satori is an important part of the system, it needs to be tested, probably manually. It would probably to good to take screenshots to demonstrate where to click, and what the results should be. (I would *really, really* prefer that it not be giphies: I have trouble following them, and find it hard to read any other text on the same page.)

**Comment by scottx611x** [comment]
Closed by addition of: https://github.com/refinery-platform/refinery-platform/wiki/SATORI-Test-Protocol

**Comment by mccalluc** [comment]
Added reference from the main document. Still wondering if there's some way we could identify just what is most likely to break...
