### ISSUE TITLE
Confusing error page if invitation token reused

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1898]
* Specific code commit: bc425b3403264b8a0fb1d28cd412a7360e05dc6b
* Version of the web browser and OS: FF MacOS
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Production 

### Steps to reproduce
Please list all the actions and the input data used:

1. On the Collaboration page, create a new group membership invitation
2. Open the email and click on the link
3. Click on the link again
4. You'll get a page like:
>  Invalid token. Not found or expired.
> Click here to view group information:
> View group information 
5. The URL is a link like "https://test.stemcellcommons.org/collaboration/#//"
6. That page is empty, but has no error message, either.
### Observed behavior
* That page is empty, but has no error message, either.

### Expected behavior
* I'm not sure what the point of the link is... To take you to the group the link would have worked for? I think we could just get rid of it.

**Comment by mccalluc** [comment]
See also #1460: Different route to the same error message.

**Comment by jkmarx** [comment]
Collaboration page was removed.
