### ISSUE TITLE
filebrowser2: table rows disappear after scroll in short window

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1900]
* Specific code commit: bc425b3403264b8a0fb1d28cd412a7360e05dc6b
* Version of the web browser and OS: FF MacOS
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Production

### Steps to reproduce
Please list all the actions and the input data used:

1. I've loaded this data set: "Genome-wide location analysis of BMP (SMAD1) in mouse erythroid progenitors co-occupted with lineage specific regulators (GATA1, GATA2)"
2. On a really tall window it's fine. (After switching between tabs: #1882 )
3. But if the window is shorter, after scrolling down the whole grid is cleared: it's just empty now, and neither scrolling up or down is possible.

### Expected behavior
* Probably a bug in the infinite scroll logic? Should this behavior depend on window height?

**Comment by jkmarx** [comment]
@mccalluc I couldn't reproduce. Can you provide a giphy?

**Comment by mccalluc** [comment]
No, sorry, I can't reproduce it now. For that matter, I can't reproduce #1882. Closing, but I'll try to keep an eye on it, and will try to provide better information in the future.

**Comment by mccalluc** [comment]
Argh: I saw this just now, but I can't reproduce it. Not a particularly small window. The grid was empty on initial load (known bug) swapped tags and swapped back. Won't reopen, but want to keep in mind.
