### ISSUE TITLE
FileBrowser2: Change columns and the grid disappears

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1902]
* Specific code commit: c20478ddb56db4533837fae0b6a27db7f9a5b72d
* Version of the web browser and OS: MacOS FF
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Production

### Steps to reproduce
Please list all the actions and the input data used:

1. Load FileBrowser2
2. click between the tabs to get the data to load
3. Click on the "config" button
4. toggle some checkboxes

### Observed behavior
* Grid is cleared and is not redrawn. May be entangled with window height?

### Expected behavior
* Grid should reflect the chosen columns

**Comment by jkmarx** [comment]
@mccalluc Couldn't reproduce, please feel free to reopen with a specific example.
![click](https://user-images.githubusercontent.com/9956764/47851329-b07f9780-ddae-11e8-9f66-3b4e9aafe47c.gif)
