### ISSUE TITLE
Number of References doesn't match expected?

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1903]
* Specific code commit: 2623df259c0eeed61a4e861ca1c1ac5e74302d3f
* Version of the web browser and OS: FF MacOS
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Test Production

### Steps to reproduce
Please list all the actions and the input data used:

1. Follow the instructions at https://github.com/refinery-platform/refinery-platform/wiki/SATORI-Test-Protocol
2. "Preview should open and contain the Summary, 2 References, and the Protocol with 13 steps (although step 13 is empty)"

### Observed behavior
* There is only one reference

![screen shot 2017-07-12 at 1 28 43 pm](https://user-images.githubusercontent.com/730388/28130769-decad35a-6705-11e7-8fc6-ef8eb83aefce.png)

### Expected behavior
* two references? @flekschas : Is it possible you mistyped? Or maybe data is being dropped from the DB, somehow?

**Comment by flekschas** [comment]
Ups I mistyped. Will fix. Thanks Cheers

PS: For those micro issues, Slack works too ;)
