### ISSUE TITLE
Satori icon loading could be enhanced

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1905]
* Specific code commit: 2623df259c0eeed61a4e861ca1c1ac5e74302d3f
* Version of the web browser and OS: MacOS Chrome
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Test Production

None of the icons for Satori are loading: Neither the hints in the header, nor elements in the real gui. In the js console:
```
d3.min.js:4 Unsafe attempt to load URL 
https://refinery-static.s3.amazonaws.com/vendor/d3-list-graph/dist/icons.svg 
from frame with URL https://test.stemcellcommons.org/#/exploration?context=OWL:Thing&branchId=0. 
Domains, protocols and ports must match.
```

**Comment by flekschas** [comment]
It seems like one of the issue is that JS is dynamically requesting the external SVG from a different domain.

**Comment by flekschas** [comment]
I think Chrome is fine if the request is issued by the website but probably not if JS (i.e., the client) does this. (Just guessing)

My best guess is to have the front-end point to the original URL and have the website do the redirect.

**Comment by flekschas** [comment]
Here's what I would do:

Instead of changing the static URL in a hard way, i.e., using `getStaticUrl()`, I would set up a proxy from `refinery.rocks/static/**/*` to `refinery-static.aws-whatever.com/**/*`. This way all the frontend request point to the same domain, protocol, and port.

**Comment by flekschas** [comment]
This might also work:

```
<IfModule mod_headers.c>
  Header set Content-Security-Policy "default-src 'none'; script-src 'self' https://refinery-static.aws-whatever.com; style-src 'self' 'unsafe-inline' https://refinery-static.aws-whatever.com; img-src 'self' https://refinery-static.aws-whatever.com; font-src 'self'; connect-src 'self' https://refinery-static.aws-whatever.com"
</IfModule>
```

**Comment by mccalluc** [comment]
We're not necessarily running inside apache, but we have set up a proxy in django for the docker visualizations, so we might look at that.

**Comment by scottx611x** [comment]
@flekschas @mccalluc So I've been digging around the web today, and it seems that the underlying issue here is that the SVG2 standard doesn't allow for external SVGs referenced in `<use>` elements to be loaded regardless of CORS headers etc.

There are a couple of third party solutions, but looking into them [svgxuse](https://github.com/Keyamoon/svgxuse) seems to be the most up-to-date and least invasive solution.

See PR here: https://github.com/refinery-platform/refinery-platform/pull/1919

I just wanted your opinions on adding a third party library for this?

**Comment by flekschas** [comment]
@scottx611x What do you mean with "SVG2 standard doesn't allow for external SVGs referenced in <use> elements to be loaded regardless of CORS headers etc."? It works fine with http and https if the source is on the same domain, port, and protocol.

svgxuse seems fine but it's kind of an overhead if one could simple proxy requests on the server side. Be aware that you still might have to activate CORS AJAX headers for this to work.

**Comment by scottx611x** [comment]
@flekschas sorry I should have specified: `external SVGs` being svgs located at a different domain. 

We could probably proxy these requests but considering that each of our deployed stacks would potentially have a different s3 bucket url to handle in the proxy, that could become difficult.

**Comment by flekschas** [comment]
I thought the AWS process is automated? Was thinking of something like https://github.com/mjumbewu/django-proxy
Anyway, your call :)

**Comment by scottx611x** [comment]
Sounds good, @mccalluc and I are gonna talk tomorrow. We're already using a proxy for docker containers, but could probably use it for this as well, just need to figure out pros and cons of both approaches
