### ISSUE TITLE
exploration views do not fully instantiate

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#1907]
* Specific code commit: 58aa066d2c88a78c64eb928e8b249e5c01504887
* Version of the web browser and OS: Chrome on Mac OS X (27-inch display at 5120 x 2880)
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): 

### Steps to reproduce
1. Go to launch page (i.e. site base URL, e.g. https://test.stemcellcommons.org/#/)
2. Click "Explore"

### Observed behavior
* Upon opening of the exploration views, the views do not initialize at all or do not use the available space: [zipped MP4 of behavior](https://github.com/refinery-platform/refinery-platform/files/1143721/Jul-12-2017.20-26-20.mp4.zip) (GIF was too big ...)

* After closing and re-opening the exploration panel everything works fine.

### Expected behavior
* Exploration views fully initialize and use available space.

**Comment by mccalluc** [comment]
It's usually the treemap, I think, but if you click the "explore" as soon as it is on the screen, both the treemap and the node-link diagram might be empty:

<img width="1177" alt="screen shot 2017-07-13 at 11 48 44 am" src="https://user-images.githubusercontent.com/730388/28175201-8df71a12-67c1-11e7-91c1-af42c740dd87.png">

These parts of the UI seem to depend on the data sets list already being available.

**Comment by flekschas** [comment]
I assume this is a hiccup in layouting. The rendering works fine but somehow the width of the container holding the visualizations is not determined correctly (i.e., is zero or something else)

**Comment by flekschas** [comment]
a11b955abb9f417dbfacfa7180775790683e0bfd should fix it

**Comment by scottx611x** [comment]
Fixed by: https://github.com/refinery-platform/refinery-platform/commit/df80a73e2c4b600761362712768068fbb96b29c9
