### ISSUE TITLE
Second search for "ce" seems to bring up a number of title-less datasets 

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1922]
* Specific code commit: 4cc2c8480de9fbec9da49c31e13f4e4b94404870
* Version of the web browser and OS: MacOS Chrome and FF
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Test Production

### Steps to reproduce
Please list all the actions and the input data used:

1. On the dashboard, in the data sets search box, type "ce": This brings up a number of results, most including "cell" in their titles.
2. Delete "ce": You now have the full list, again.
3. Type "ce" again

### Observed behavior
* It finds the same number of datasets...
* but most of them have no titles or other metadata.
* where there is a title, matching words are not getting highlights.

### Expected behavior
* Search results the second time should match the first time, and titles should not be missing:

![screen shot 2017-07-14 at 11 51 28 am](https://user-images.githubusercontent.com/730388/28220114-496b6a4e-688c-11e7-84ed-a7bbc785c60d.png)

**Comment by scottx611x** [comment]
Possibly related to https://github.com/refinery-platform/refinery-platform/issues/1652

**Comment by jkmarx** [comment]
Not an issue on beta as of 7/24/18
