### ISSUE TITLE
Limit to one dashboard filter menu at a time?

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1923]
* Specific code commit: 4cc2c8480de9fbec9da49c31e13f4e4b94404870
* Version of the web browser and OS: MacOS Chrome and FF
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Test Production

### Steps to reproduce
Please list all the actions and the input data used:

1. Login and load the dashboard
2. Click the funnels for "Data Sets", "Analyses", and "Workflows" in turn: Each menu will open, and then close when its neighbor is opened.
3. Now click back on the "Analyses" funnel: "Workflows" does not close.
4. Click on the "Data Sets" funnel: "Analyses" closes, but "Workflows" stays open.
5. Click on "Analyses": Now all three are open at the same time.

<img width="1177" alt="screen shot 2017-07-14 at 1 52 16 pm" src="https://user-images.githubusercontent.com/730388/28224292-8ebe1d2a-689c-11e7-80b4-929640adaa47.png">

- Relatedly, the filter and sort menus on Data Sets can be open at the same time.
- And once more than one menu is open, clicking in another region of the window only closes the most recent one.

### Expected behavior
* We probably want only one menu open at a time?

**Comment by jkmarx** [comment]
Dashboard revamp, we will only have the data sets filter.
