### ISSUE TITLE
filebrowser2: table rows disappear after adding filter

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1926]
* Specific code commit: 4cc2c8480de9fbec9da49c31e13f4e4b94404870
* Version of the web browser and OS: MacOS Chrome and FF
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Test Production

### Steps to reproduce
Please list all the actions and the input data used:

1. Visit https://test.stemcellcommons.org/data_sets2/707bb3d3-c024-4e31-868d-e74ecf7ebb78/#/files/
2. Table is empty. known bug. toggle between tabs and the table will be cleared.
3. Click the checkbox beside any facet: the table clears.
4. Uncheck: the table is still clear

see also: table drawing and redrawing just isn't working: #1900 and #1902

**Comment by jkmarx** [comment]
@mccalluc I can't reproduce this error on the beta site which has the latest version. 
![filters](https://user-images.githubusercontent.com/9956764/29243310-2762c8ee-7f6a-11e7-85a2-8cfd4c7a74d1.gif)

**Comment by jkmarx** [comment]
Able to reproduce with Data Set 14909: Genome-wide location analysis of BMP (SMAD1) in mouse erythroid progenitors co-occupted with lineage specific regulators (GATA1, GATA2) using replicate ids and using the replicate id filter

<img width="1401" alt="screen shot 2017-08-12 at 2 34 35 pm" src="https://user-images.githubusercontent.com/9956764/29243369-743c7966-7f6b-11e7-856d-a2ab77b9f120.png">

**Comment by mccalluc** [comment]
@jkmarx : We're not seeing a "replicate id filter" right now on test (and it doesn't sound like we're expecting a "replicate id filter" either?) so we can't reproduce this. A lot of other things have changed in the filtering: Do you think it's still a problem?

**Comment by jkmarx** [comment]
Could not reproduce issue with the above data set (note replicate ids are not available).
