### ISSUE TITLE
Why does Node have FK to Study?

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1929]
`data_set_manager/models.py`:
```python
    study = models.ForeignKey(Study, db_index=True)
    assay = models.ForeignKey(Assay, db_index=True, blank=True, null=True)
```

What's going on here? I would think the only FK necessary is Assay (the lowest level of ISA), and from Assay you can get the Study. Also, why the `blank=True, null=True`? 

(Looking at this in order to enrich `create_dataset_with_necessary_models`, in order to improve the tests in #1875.)

**Comment by scottx611x** [comment]
@mccalluc I don't have a good answer to this, it looks like that code is [5 years old](https://github.com/refinery-platform/refinery-platform/commit/efc157283b110af3e943f48d0d317266efb63c37#diff-7f24622f6c1dae8153dd867c33a58b4bR235)

**Comment by jkmarx** [comment]
I think this is part of #713. Feel free to reopen if you disagree.
