### ISSUE TITLE
Understand solr errors in logs for /user/files

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1938]
Hitting /user/files causes this error to show up multiple times in the logs. What's going on?
```
2017-07-21 15:32:21 ERROR    core.views:760 solr_select() - 400 Client Error: Bad Request
```

**Comment by jkmarx** [comment]
@jkmarx confirm this is still an issue

**Comment by jkmarx** [comment]
Have not seen this issue recently (past few months), closing for now.
