### ISSUE TITLE
Why are Investigation and Study NodeCollections, but not Assay?

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1943]
```
class Investigation(NodeCollection):
class Study(NodeCollection):
class Assay(models.Model):
```
Reading the specs, I see that Investigation and Study do have some similarities not shared with Assay, but NodeCollection is a slightly confusing name for this concept, since there is no obvious relationship to our Nodes.

Reading the [specs](http://isa-specs.readthedocs.io/en/latest/isamodel.html#study) also confuses me a little: 

> A Study SHOULD record the following:
>
> Property | Datatype | Description
> -- | -- | --
> Identifier | String | A identifier or an accession number provided by a repository. This SHOULD be locally unique.
> Title | String | A concise name given to the investigation.
> Description | String | A textual description of the investigation.
> ... | |

Do they really mean "Investigation" here? I could read this as requiring the denormalized, redundant storage of Investigation metadata on each Study?

**Comment by jkmarx** [comment]
Ref #713    Part of improving the data set model.
