### ISSUE TITLE
Remove unused templates

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1993]
https://github.com/refinery-platform/refinery-platform/issues/783#issuecomment-237878783:
> Also the data set import templates.

Those were not tackled in #1987 and probably still need to be done.

**Comment by jkmarx** [comment]
/search  ?remove
<img width="1282" alt="screen shot 2017-11-01 at 11 51 34 am" src="https://user-images.githubusercontent.com/9956764/32283572-1eebbd1c-befb-11e7-8807-098ae4a1aec0.png">

**Comment by scottx611x** [comment]
@jkmarx ^^^ Thats kinda cool. I had no clue it was even a thing!

**Comment by jkmarx** [comment]
/contact ?remove

<img width="951" alt="screen shot 2017-11-01 at 12 03 42 pm" src="https://user-images.githubusercontent.com/9956764/32284175-c3421036-befc-11e7-96ce-524dabdcc138.png">

**Comment by jkmarx** [comment]
templates/core
Current file browser covers:
? analyses.html
? analysis.html 

Current collaboration page:
? group invite

? home

**Comment by jkmarx** [comment]
? samples_solr.html unsure what this is for

**Comment by jkmarx** [comment]
?? What are we doing with Projects?
![screen shot 2017-11-02 at 7 52 13 am](https://user-images.githubusercontent.com/9956764/32324751-cf33f660-bfa2-11e7-8d5c-fc063d46b86f.png)

**Comment by mccalluc** [comment]
@jkmarx : Also asked about Projects in #1936, but no useful information there.

**Comment by jkmarx** [comment]
Closing the issue, projects has a separate tech debt issue.
