### ISSUE TITLE
Does it really make sense to try to keep the same facets betw fb2 and user/files?

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#1994]
If someone finds an interesting file on `user/files` and then navigates to the corresponding data set, it seems reasonable that the context should be preserved somehow. #1981 tried to do this, but the facets used in the two tools just don't match: Most of the time this is not going to work. Options:

- Revert #1981 and take no more action (my preference)
- Somehow get fb2 to ensure that all the `user/files` facets are available.
- Add some new machinery to fb2 to allow the highlighting of arbitrary files. I don't think this "highlight" state would have any other use.

@ngehlenborg ?

**Comment by ngehlenborg** [comment]
Is #1981 causing errors? Should FB2 maybe just ignore facets that are in the URL but are not found in the dataset?

If we revert #1981 I would suggest that we prioritize highlighting in FB2.

**Comment by mccalluc** [comment]
I have not seen additional errors, but my concern is mostly that it just doesn't make sense: With only one or two facets in common, it's really not accomplishing what we want, even if we leave it in. If this feature is important there need to be some prerequisites in place.

My sense is that the real goal is preserve context between the two screens, and we had thought that we could just use the faceting on both ends to do this, but since that doesn't actually work, instead there should be some way to highlight one arbitrary file on fb2.

Details TBD.

**Comment by mccalluc** [comment]
(Talked with Jennifer, and I think we're on the same page that trying to keep the same facet selection between pages doesn't make sense, because the pages are getting their lists of facets from different places. Highlighting the record we came from is probably doable.)

**Comment by mccalluc** [comment]
Closing this. If highlighting the file we came from is important, that can be filed, but I don't see it as a priority.
