### ISSUE TITLE
Why is user/files slow?

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2006]

**Comment by ngehlenborg** [comment]
It seems that two identical queries (`GET /api/v2/user/files/?fq=&limit=100&sort=`) are sent to obtain (1) the content of facets/facet value list and (2) the content of the table. 

Timing for the 1st query:
![image](https://user-images.githubusercontent.com/1216518/29415064-b7cf4308-832f-11e7-92d2-f50552e5e8bd.png)

Timing for the 2nd query (stalled by the 1st):
![image](https://user-images.githubusercontent.com/1216518/29415083-c4ed5d86-832f-11e7-904e-63e687508fcb.png)
