### ISSUE TITLE
Facet sorts done right

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2008]
Confirmed that we just want to toggle between an alphabetic and a numeric sort.

![screen shot 2017-08-15 at 10 29 03 am](https://user-images.githubusercontent.com/730388/29320127-4139ec48-81a4-11e7-8fe5-af1f67f679aa.png)
```
<i style="float: right;" class="fa fa-sort-alpha-asc"></i>
```
Getting it to align with the counts might be tricky, just because that positioning depends on a ratio of the width, and the top line has a greater width.

**Comment by ngehlenborg** [comment]
@sjhosui: as per discussion with me. We can extend if we need all 4 possible sorting options.

**Comment by mccalluc** [comment]
Fixed by #2055
