### ISSUE TITLE
Strip down data_sets_old?

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2015]
In conjunction with #2014, we no longer need the old file browser, so I guess it should be removed, leaving the provenance and matrix views? But maybe we'll be able to port those in the near-ish future, and trying to excise just the browser would be more trouble than it's worth?

**Comment by ngehlenborg** [comment]
Should be removed, also refer to #2202.

**Comment by jkmarx** [comment]
We're integrating the provenance and matrix into the current file browser. I don't think the data_set_old template is even around. Closing issue.

**Comment by jkmarx** [comment]
Duplicate issue or encompassed within Ref #2202 Closing.
