### ISSUE TITLE
Analysis Filtering url is not picked up by File Browser 2 facet filtering

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2027]
Commit: `c33d8d5f9dd88168c140c5e99114c5e61e535d72`

@mccalluc Analysis facet filtering in FB2 is not triggered with the newly created urls. It seems like the logic to create the url on facet selection is there, but the selections aren't updated with the inverse manner.

**Comment by mccalluc** [comment]
@scottx611x : I can't reproduce this now... If you remember anything particular about the situation we had and could remind me of details, that would be great, but maybe we were just confused?

**Comment by scottx611x** [comment]
@mccalluc I can still reproduce, I think it'd be clearer if I just showed you what I was getting at

**Comment by jkmarx** [comment]
Console Error: ```TypeError: selectedFilterService.attributeSelectedFields[internalName].indexOf is not a function
    at b.scope.showField (file-browser.js:301)
    at fn (eval at compile (angular.js:15033), <anonymous>:4:461)
    at m.$digest (angular.js:17747)
    at m.$apply (angular.js:18021)
    at angular.js:18322
    at e (angular.js:6035)
    at angular.js:6314```

**Comment by scottx611x** [comment]
@jkmarx  I'm still seeing this issue with the latest develop: ac1873f33fdb24597ba0456102b209c58f619b73

See below:
![oct-25-2017 11-21-02](https://user-images.githubusercontent.com/5629547/32007127-a7015a8e-b976-11e7-820f-0bb70325d8c2.gif)

**Comment by jkmarx** [comment]
@scottx611x This is a separate issue. The filtering is based on field names and the analysis page is redirecting via analysis_uuid. I think it's a quick fix.

**Comment by jkmarx** [comment]
@scottx611x URLs generated from the analysis filter should work now and weren't previously.
