### ISSUE TITLE
Refinery freezes when trying to view Protocol Reference Parameters

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#2032]
* Specific code commit: (unable to retrieve, whatever is deployed on https://beta.stemcellcommons.org on 8/22/2017)
* Version of the web browser and OS: Chrome Version 60.0.3112.101 on Mac OS X 10.12.6 
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): https://beta.stemcellcommons.org

### Steps to reproduce
Please list all the actions and the input data used:

1. Go to admin interface.
2. Select a "Protocol reference parameter" object (or "Protocol reference", I don't remember)

### Observed behavior
* admin UI becomes unresponsive
* site no longer responds

### Expected behavior
* admin UI show details of the "Protocol reference parameter"/"Protocol reference" object

A possible explanation: The admin UI is following some foreign key field or many-to-many field to create the content for a dropdown list and that query is taking too long.

**Comment by ngehlenborg** [comment]
Ultimately, the server returns a 504 error.

**Comment by hackdna** [comment]
RDS instance shows negligible CPU and memory use. EC2 instance shows a CPU use spike to 50-60% for 2-3 minutes then 10-20%.

**Comment by scottx611x** [comment]
The lis of Nodes in the detail view in the Admin ui seems to list every `Node` in the system. Could be a sideEffect of `ForeignKeyAutocompleteAdmin`

**Comment by ngehlenborg** [comment]
The CPU spike might be the admin page template generation (the database query to retrieve all nodes should be fast).

**Comment by mccalluc** [comment]
I think we decided that it would be acceptable to just remove this functionality from admin, and that it is not required for 1.6?

**Comment by scottx611x** [comment]
@mccalluc Yes I believe that was the consensus
