### ISSUE TITLE
Only one file of two file upload shows up in data_sets at first, but reindex helps

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2049]
* Specific code commit: 0139c1e 
* Version of the web browser and OS: mac chrome
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): local dev

### Steps to reproduce
Please list all the actions and the input data used:

1. I uploaded this tsv:
```
Sample ID	URL	Organism
sampleA1_1	sampleA1_1.fq	Human
sampleA1_2	sampleA1_2.fq	Human
```
2. and uploaded two local files with the right names

### Observed behavior
* Upload seems to complete successfully, except there is only one file listed:
![screen shot 2017-08-24 at 2 51 21 pm](https://user-images.githubusercontent.com/730388/29683310-df320dca-88db-11e7-810d-592a5ea0c967.png)
No change with page reload.
* Do a commandline reindex (`./manage.py update_index --using=data_set_manager`) and now it looks right:
![screen shot 2017-08-24 at 2 56 44 pm](https://user-images.githubusercontent.com/730388/29683368-1c8841d0-88dc-11e7-8084-15f988f9ceea.png)

For all I know, we might always be missing one file from uploads, and just didn't notice it in longer lists...

**Comment by scottx611x** [comment]
@mccalluc I think you may not even need to reindex to get the second file to show up. Try waiting for a bit then refreshing. I think you are just seeing a case where the 2nd file is still being imported.

**Comment by mccalluc** [comment]
That's plausible. I'll close, but reopen if you want further action.
