### ISSUE TITLE
With download url in solr, don't need the per-row api hits in file browser

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2050]
With #2044, we update the solr index once we have a url for the file store. With this, the file browser could depend just on the data from solr, and wouldn't need to hit the node api once per row. Currently being used on the all-files browser, so make sure no problems crop up there before trying to use it more broadly.

**Comment by jkmarx** [comment]
@mccalluc Think I can implement for 6.2?
