### ISSUE TITLE
Is there any reason not to just say `fl=*`?

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2052]
I got tripped up because I forgot about explicitly adding a new column to the `fl` parameter... Would there be any downside to just saying `fl=*`... or just leaving it off, since that's the default? At least where I'm looking, we are requesting just about every field in any case.

**Comment by drj11** [comment]
context? Like, which view, which API call?

**Comment by mccalluc** [comment]
This was in user/files, but more generally, if we don't need the constraint, then it's just another thing that needs to be maintained over time.

**Comment by jkmarx** [comment]
@mccalluc In the file browser (via the config), a user can remove column/fields from the table and they're not returned from solr. I'd assume the user/files will have the same capabilities at some point.  Closing the question, please feel free to reopen if you'd like to discuss further.
