### ISSUE TITLE
FB2: Should all selected facets be visible?

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2075]
* Specific code commit: 24dd3c679983467e6f75de8a9858b2bfbc33d853
* Version of the web browser and OS: FF MAc
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): "test" production

### Steps to reproduce
Trying to get a reproducer on #1926, so I begin with [that dataset](https://test.stemcellcommons.org/data_sets/8d51838c-c60d-4337-9ff1-45b10e0ca5a6/#/files/) and then...
![screen shot 2017-09-05 at 9 51 21 am](https://user-images.githubusercontent.com/730388/30064440-c605a2ba-921f-11e7-8419-1d6374acc0d5.png)

### Observed behavior
* After applying `Antibody: GATA2`, the `Genotype` facet disappears... I would expect all non-zero facets to be shown, but maybe I'm not thinking about it the right way?

**Comment by jkmarx** [comment]
I think that was a bug. 
![count-zero](https://user-images.githubusercontent.com/9956764/34880155-8b4f4306-f77d-11e7-8a9b-b23d73adb907.gif)
