### ISSUE TITLE
New details tab: port over the instructions about how to transfer ownership

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2082]
The old details tab had instructions about how to transfer ownership. (Visible only if logged in?) Port these to the new details tab

**Comment by jkmarx** [comment]
anyone have an image?

**Comment by jkmarx** [comment]
@mccalluc Do you have more details?

**Comment by mccalluc** [comment]
I filed this around the same time I was working on #2060, which also deals with the details tab. I'd say at this point enough may have changed that it makes more sense to ask if the current design is good enough... If more text would help, great, otherwise don't worry about it.
