### ISSUE TITLE
Old file browser is broken

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2083]
- https://test.stemcellcommons.org/provenance/dc0bdaa9-eb00-4162-9567-309c7f3b3de9/#/files/browse brings up an empty pane
- Details tab can not even be clicked on

This page needs to hang around for the provenance visualization, and other functionality will be removed, gradually, but it seems broken right now.

**Comment by mccalluc** [comment]
Doing a binary search through the history: `provenance` was introduced at 61ebee109ad524269dab1d8, and that works when I check it out.

**Comment by mccalluc** [comment]
Works at a679b9904cc8d9c199, broken at 97af50631a519a78a6 -> My PR #2061 is at fault.

**Comment by mccalluc** [comment]
Looking at commits within that PR, I'm not convinced it has ever worked after the rename. The behavior at 75a4d4a07e118925ee7 matches the behavior at c8d8f77edf7794d091. It's possible I had done `supervisorctl restart`s but not `grunt build` and didn't realize it wasn't working?

**Comment by mccalluc** [comment]
Angular routing is confused: going to data-set-ui-mode-browse.html, which is just
```
<!-- Nothing here -->
```

Simply removing that state from data-set-nav.js causes an `Infinite $digest Loop` error from Angular.

**Comment by mccalluc** [comment]
There are no links to `provenance` right now (#2096), so it's not a high priority for this milestone.

**Comment by scottx611x** [comment]
closed by #2179
