### ISSUE TITLE
cross-dataset browser: Download urls are sometimes still paths

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2086]
Not sure about reproducer: talk to @scottx611x

**Comment by scottx611x** [comment]
@mccalluc I don't think we need a reproducer, `core.utils.get_full_url(<relative_url>)` just needs to be utilized.

**Comment by hackdna** [comment]
Or simply let the web browser automatically display relative URLs as full by making them into hyperlinks.

**Comment by mccalluc** [comment]
- Can't leave it to the browser because the problem is in a csv download.
- The PR fixes it in the index. This does require a reindex, and introduces a bit of redundancy in the solr index, but if the urls were filled out only downstream, I suspect that some future user would trip over the same problem. This way that field just has what people expect it to have.
