### ISSUE TITLE
Details tab, metadata edit: updates not shown in dashboard

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2087]
I don't have it in front of me, but I after updating the metadata, I believe updates are being shown in the datasets list, but are not being shown in the fold-out to the right.

**Comment by scottx611x** [comment]
@mccalluc To add to this, I think we were seeing a subset of the updates in the Dataset Preview (`Accession` & `Summary`) but  the Dataset description was definitely not updating.

**Comment by mccalluc** [comment]
I'm not sure that these are the exact API calls that are behind the different components of the ui, but:
- http://192.168.50.50:8000/api/v1/data_sets/?format=json&order_by=-modification_date&uuid=b9f1047a-efbd-4d46-8499-e718fa98709b → has a description
- http://192.168.50.50:8000/api/v1/data_sets/b9f1047a-efbd-4d46-8499-e718fa98709b/studies/?format=json → description is blank

**Comment by mccalluc** [comment]
(meta-question: Hopefully this is quick, but if some fix got complicated, would we think about trying to use api v2 instead?)
