### ISSUE TITLE
file browser filters disappear as new facets applied

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2091]
* Specific code commit: 
* Version of the web browser and OS: 
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): 

### Steps to reproduce
For example:

![screen shot 2017-09-05 at 4 18 32 pm](https://user-images.githubusercontent.com/730388/30081643-fb9c5de8-9255-11e7-818a-42c3f4ae81e0.png)

with `facet.mincount=1` removed the behavior is 

![screen shot 2017-09-05 at 4 25 50 pm](https://user-images.githubusercontent.com/730388/30081866-cce752fe-9256-11e7-9ca4-b282fda2b4a9.png)

### Observed behavior
* If facets are only single valued, they are suppressed: I don't think this is the behavior Nils wants, but I think it's also not as much of a concern when we're showing 0-count facets.
* It also seems that there is no updating within-facet: In the second example, if I click on one of the zero values, it doesn't update the counts on its neighbors.

**Comment by jkmarx** [comment]
Fixed at some point. Giphy from beta site 
![beta-filter](https://user-images.githubusercontent.com/9956764/35059694-03d85a00-fb8a-11e7-96b5-fcb2a869e247.gif)
