### ISSUE TITLE
Run docker containers on separate burstable instance (or ECS?)

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2095]
The docker containers need to run on a separate burstable EC2 instance: We don't want their resource use to get in the way of the main Refinery work. There is code in django_docker for making the appropriate calls to CloudFormation to build a stack, but I don't know if that can be reused.

**Comment by mccalluc** [comment]
This does not have buy-in: Ilya believes ECS is a better solution to the problem. In my experience, starting containers through ECS is much slower than starting them directly on a docker engine, but I might have been doing it wrong.

Adding "(or ECS?)" to title and adding `Question` label.

**Comment by ngehlenborg** [comment]
After discussion: expand root volume and create directory there. It will be that way no matter how we resolve the question about launching a separate EC2 or using ECS to run Docker containers.

**Comment by mccalluc** [comment]
Continuing conversation from https://github.com/refinery-platform/refinery-platform/pull/2291#issuecomment-340595672: Ilya suggested I look into BlockDeviceMappings. I do think this is in the right direction, but it looks like there is a choice between ephemeral instance stores and ebs stores, and only for the latter can you set the volume size?  

- [Contrasting examples for the two](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-blockdev-mapping.html#w2ab2c21c14d514c11b2)
- [Documentation explaining that size can only be specified for ebs volumes](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-blockdev-mapping.html)
- Diagrams contrasting the two: [root device docs](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/RootDeviceStorage.html), [block device mapping docs](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/block-device-mapping-concepts.html)

**Comment by mccalluc** [comment]
On the AWS instance:
```
ubuntu@ip-172-31-53-83:~$ sudo du -sh /var/lib/docker
2.2G	/var/lib/docker
ubuntu@ip-172-31-53-83:~$ sudo ls -dl /var/lib/docker
drwx--x--x 11 root root 4096 Oct 26 21:41 /var/lib/docker
```

**Comment by hackdna** [comment]
"By default, the root device volume for an AMI backed by Amazon EBS is deleted when the instance terminates."

**Comment by mccalluc** [comment]
I think Zappa might be a better solution for us, for most usecases. I'll keep this open, but move it out of milestone.

**Comment by mccalluc** [comment]
Docker containers run on a separate instance, and that seems to be good enough for now. Closing.
