### ISSUE TITLE
groups: Blank lines / random order (but do we even need it?)

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2121]
* Specific code commit: 2a3c825183c423d388c391f52a18e13d5caa2925
* Version of the web browser and OS: ff macos
* Environment where the error occurred: test production

### Steps to reproduce

https://test.stemcellcommons.org/groups/bd359b17-ae44-424a-9d5b-d549e093919b/

(You can link to this from the user profile page.)

![screen shot 2017-09-12 at 4 12 22 pm](https://user-images.githubusercontent.com/730388/30346057-79c694e8-97d5-11e7-839a-31157714a699.png)

### Observed behavior
* Unsorted
* `Admin` and `AnonymousUser` and any user that has cleared their first and last name have blank, unusable links
* Do we even need this page? https://test.stemcellcommons.org/collaboration/#/bd359b17-ae44-424a-9d5b-d549e093919b/ is prettier: Maybe just add last login there, if it's important?

**Comment by jkmarx** [comment]
Issue is resolved but the question remains.

**Comment by jkmarx** [comment]
Remove page but add info to collaboration page.

**Comment by jkmarx** [comment]
- [ ] User profile link should also go to collab page

**Comment by jkmarx** [comment]
Closing this issue because inactive users are no longer shown so there are no blank/empty rows. At some point we will remove collaboration page and do other enhancement.
