### ISSUE TITLE
Data cart sizing inconsistent between FF/Chrome

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2128]
* Specific code commit: 2a3c825183c423d388c391f52a18e13d5caa2925
* Version of the web browser and OS: ff macos
* Environment where the error occurred: test production

### Steps to reproduce
Please list all the actions and the input data used:

1. Load satori and expand the data cart

![screen shot 2017-09-13 at 9 55 35 am](https://user-images.githubusercontent.com/730388/30381188-ae09d258-9869-11e7-8e23-8f48bffd3094.png)

### Observed behavior
* FF accommodates 2 1/2 entries, Chrome 1 1/2

I don't think the difference matters, but wanted to note, in case it matters to someone else.

**Comment by jkmarx** [comment]
Data Cart feature will be removed in new dashboard design
