### ISSUE TITLE
First add-all-to-cart takes 4 seconds (with 119 data sets)

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2129]
* Specific code commit: 2a3c825183c423d388c391f52a18e13d5caa2925
* Version of the web browser and OS: ff macos + chrome
* Environment where the error occurred: test production

### Steps to reproduce
Please list all the actions and the input data used:

1. Load the site from scratch
2. Once the screen has fully rendered, click the star to "Add all to data cart"
3. Wait 4 seconds... and then they all get their gold stars.

Successive add-to-carts are only about 1 second.

### Expected behavior
* Aim for no more than a second or two? It's slow enough that I've been tempted to click again, in which case I wouldn't see anything change, and might think it's broken.

May be related to #1552, where add-to-cart seemed to do nothing at all.

**Comment by jkmarx** [comment]
Data cart will be removed in dashboard re-design
