### ISSUE TITLE
Treemap looses orange when mouse leaves data sets list

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2132]
* Specific code commit: 2a3c825183c423d388c391f52a18e13d5caa2925
* Version of the web browser and OS: ff macos
* Environment where the error occurred: test production

### Steps to reproduce
Following the test protocol:
>**4. Click on the rectangle once.**
> In addition to the description above everything should be highlighted in orange. Also, the clicked rectangle should display a subtle lock icon.
> **5. Move mouse cursor elsewhere.**
> Data sets, nodes, and rectangles should still be highlighted in orange but the black outlines / highlights should be gone.

In particular:
- After locking a rectangle in the tree map, move the mouse over any portion of the data sets list on the left, (much of the map will turn orange), and then move the mouse out of that region. (No clicking.)

### Observed behavior
On mouse-leave from the datasets list, the locked rectangle looses its orange

### Expected behavior
It still should be orange? (More generally, if a treemap box is locked, it should be orange, right?)

![screen shot 2017-09-13 at 11 09 09 am](https://user-images.githubusercontent.com/730388/30384911-9048853e-9873-11e7-8bfd-4df19990eefc.png)

**Comment by jkmarx** [comment]
Ref #2673
