### ISSUE TITLE
FF Depth bug even worse when rooted on particular nodes

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2137]
* Specific code commit: 2a3c825183c423d388c391f52a18e13d5caa2925
* Version of the web browser and OS: ff macos (not chrome)
* Environment where the error occurred: test production

### Steps to reproduce
1. https://test.stemcellcommons.org/#/exploration
2. Click on the node for "Connective Tissue" in the third column and root it. (Some nodes seem to reliably reproduce the issue, others don't: I can't explain the difference.)
3. Click the up-arrow for "Depth"

### Observed behavior
* The depth index increases without limit.

This seems to be an even worse version of #1910 ... Before fixing that one, maybe figure out why this one only works for certain nodes? If that one is fixed first, this one will probably go away, too, but part of the weirdness will remain unexplained.

![screen shot 2017-09-13 at 2 18 32 pm](https://user-images.githubusercontent.com/730388/30393417-0aefddea-988e-11e7-8acc-e9828990e00d.png)

**Comment by jkmarx** [comment]
With v1.6.9 Explore/Satori has been removed.
