### ISSUE TITLE
Sorting data sets on launch pad is hard without more feed back

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2143]
* Specific code commit: 2a3c825183c423d388c391f52a18e13d5caa2925
* Version of the web browser and OS: ff macos
* Environment where the error occurred: test production

### Steps to reproduce

Not a big deal, but imagine you wanted to get datasets with lots of file: you find the filter, and click the arrow, and something happens, but how do you know it's the right thing? There are no counts in the UI, and it's unclear if the arrows represent the current state, or the state you'd like to be in.

**Comment by jkmarx** [comment]
@mccalluc What arrows are you referring to?

**Comment by mccalluc** [comment]
<img width="156" alt="screen shot 2018-07-24 at 4 05 26 pm" src="https://user-images.githubusercontent.com/730388/43163308-c5d11f24-8f5b-11e8-9fd6-21a471ebd9f0.png">

The arrows here are what I had in mind, I think, but it's not the "dashboard" as we understand it now, and it probably shouldn't be a priority.

**Comment by jkmarx** [comment]
With v1.6.9 Explore/Satori/Launchpad has been removed.
