### ISSUE TITLE
"Public" filter count does not match count seen by the public

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2144]
* Specific code commit: 2a3c825183c423d388c391f52a18e13d5caa2925
* Version of the web browser and OS: ff macos
* Environment where the error occurred: test production

### Steps to reproduce
Please list all the actions and the input data used:

(I believe this is what I did, but I have not been able to reproduce: Shared another set, added and removed privs, but the have not been able to change the counts)
1. Log in
2. Import some public data set into your own space
3. Click "Share" and give "Read-only" to "Public"; "Save"
4. Then reverse that: "Share": "Public": "None"; "Save"
5. Use the "Public" filter

### Observed behavior
![screen shot 2017-09-14 at 9 34 42 am](https://user-images.githubusercontent.com/730388/30432709-7608cb6c-9930-11e7-9452-0d92e43f2b16.png)

On the left you can see there are actually 119 public datasets, but on the right, when logged in but with the filter applied, the count is 120.

### Expected behavior
I'd expect them to be the same. Perhaps the index used by the UI isn't being updated correctly?

**Comment by mccalluc** [comment]
So I've shared a few more datasets with myself, toggling public access on and off after each share. What I think I'm seeing is that only the most recent share is slipping through the public filter... maybe somewhere in the process of sharing a second set and toggling its privs, everything is reindexed, so the discrepancy can't grow greater than one?

**Comment by jkmarx** [comment]
Tested on test site commit 76c23b21b2eacf65e476af3a840d7892ed51dcc8 
Public matches users-public filter (pre/post changing a data sets' perms)
@mccalluc Please reopen if you're still seeing this issue
