### ISSUE TITLE
svgxuse.min.js in error log

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2145]
* Specific code commit: 2a3c825183c423d388c391f52a18e13d5caa2925
* Version of the web browser and OS: ff macos
* Environment where the error occurred: test production

### Observed behavior
This appears in `/var/log/apache2/refinery_error.log`:
```
[Thu Sep 14 09:30:00.086206 2017] [:error] [pid 31426:tid 139774477465344] /refinery-all-files-test-static/vendor/svgxuse/svgxuse.min.js
```

Is this a 404? Are we specifying the wrong path somewhere?

**Comment by jkmarx** [comment]
Testing with vagrant production mode on Firefox, I can't reproduce error based on the info above. No errors are being logged. Commit https://github.com/refinery-platform/refinery-platform/commit/15bf05ccb1b1aacd16f9fd05b96857defc27a07a 

Please reopen if you see it again.
