### ISSUE TITLE
Cross-dataset: Filename column should not be url encoded

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2150]
* Specific code commit: 2a3c825183c423d388c391f52a18e13d5caa2925
* Version of the web browser and OS: ff macos
* Environment where the error occurred: test production

### Steps to reproduce

https://test.stemcellcommons.org/files/

Look at the "Filename" column.

### Observed behavior

We have url encoded strings (lots of `%`), because we just slice off the last portion of a url path... but it really should be un-encoded.

**Comment by jkmarx** [comment]
No longer an issue, reverted back to using the Name default column. Resolved by #2630
