### ISSUE TITLE
Prettier tool names

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2155]
* Specific code commit: 2a3c825183c423d388c391f52a18e13d5caa2925
* Version of the web browser and OS: ff macos
* Environment where the error occurred: test production

### Steps to reproduce

Should we give the IGV and HiGlass prettier names by default? After
```
./manage.py generate_tool_definitions --visualizations
```
I have
> Test LIST Visualization HiGlass
> Test LIST Visualization IGV

could it just be...?
> HiGlass
> IGV

**Comment by jkmarx** [comment]
On the beta site, 
![screen shot 2018-01-17 at 1 16 45 pm](https://user-images.githubusercontent.com/9956764/35059315-b743f8bc-fb88-11e7-8d8c-907ad29d3500.png)
