### ISSUE TITLE
Check that s3 caching settings are correct

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2156]
* Specific code commit: 2a3c825183c423d388c391f52a18e13d5caa2925
* Version of the web browser and OS: ff macos
* Environment where the error occurred: test production

### Question

* When S3 was unhappy on September 14, the test instance became unusable, but beta was still fine. That makes me think the caching policies were different across the two buckets? (It might also be that different buckets had different behavior during the outage?)

See also: #2157

**Comment by hackdna** [comment]
The buckets have identical configuration. One was affected by the outage, the other one wasn't.

**Comment by mccalluc** [comment]
We *only* use etags: There are no caching headers. (That's the part that surprised me.)
