### ISSUE TITLE
Cache-busting for static assets on S3

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2157]
* Specific code commit: 2a3c825183c423d388c391f52a18e13d5caa2925
* Version of the web browser and OS: ff macos
* Environment where the error occurred: test production

### Question

* Beta assets have urls like `https://scc-beta-static.s3.amazonaws.com/js/refinery.js`: We need to be sure we do not reuse these urls in the next release. I would suggest appending the git hash as a query to the url. Release version is not sufficient: May have a hot JS fix under the same version number. Bucket could work, but is overkill: It would mean we'd need to push an entire new bucket with a change to any single asset

See also: #2156

**Comment by hackdna** [comment]
I think this is already accomplished by [ETags in S3 response headers](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html)

**Comment by mccalluc** [comment]
I was assuming we had a `max-age` header on s3 assets. We don't. If we did, it might improve page load a little bit... at the cost of worrying about things like this. Closing.
