### ISSUE TITLE
Django docker tmp needs separate EBS mount

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2166]
Until Docker runs on a separate instance (#2095) the docker temp files will be created on a volume attached to the main instance. A PR is on the way for cleaning up docker temp files (#2160), but even with that, if the user selects HiGlass and tries to start it with very large files, it could still be able to consume all of disk. When this happens we know that Satori and RabbitMQ won't work (among other things).

If we want to get a fix out in this release, the easiest thing would be to have a separate EBS mount for `/tmp/django-docker`. We could just ignore this, but my sense is that we want 1.6.0 to be more stable than it is at this moment, but we don't want to go as far as #2095.

**Comment by mccalluc** [comment]
Different approach: `/tmp/django-docker` is hard coded in django_docker_engine. Make it configurable, and use `/data`

**Comment by ngehlenborg** [comment]
Refer to #2095?

**Comment by mccalluc** [comment]
Not going in this direction. Plan to have docker running on separate instance, and it will use the EC2 root volume there.
