### ISSUE TITLE
refinery-modules vs modules: Can we get rid of one?

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2170]
* Specific code commit: 2a3c825183c423d388c391f52a18e13d5caa2925

```
$ tree deployment/{,refinery-}modules/refinery/
deployment/modules/refinery/
└── manifests
    ├── apache2.pp
    ├── aws.pp
    ├── docker.pp
    ├── init.pp
    ├── neo4j.pp
    ├── postgresql.pp
    ├── python.pp
    ├── selenium.pp
    └── solr.pp
deployment/refinery-modules/refinery/
└── manifests
    ├── apache2.pp
    ├── aws.pp
    ├── docker.pp
    ├── init.pp
    ├── neo4j.pp
    ├── postgresql.pp
    ├── python.pp
    ├── selenium.pp
    └── solr.pp
$ diff -r deployment/{,refinery-}modules/refinery/
# no output
```
At a higher level, `deployment/refinery-modules` is missing files which are in `deployment/modules`.
- Can `deployment/refinery-modules` be removed?
- Or would it be better to keep it separate, and incorporate a reference from `deployment/modules`?

Maybe one is unused, and could just be deleted? Or maybe each is used in a different place by the build script?

```
$ git grep refinery-modules
deployment/Puppetfile:mod 'refinery/refinery', :path => "refinery-modules/refinery"
deployment/manifests/aws.pp:# See code in refinery-modules/refinery/...
deployment/manifests/default.pp:# See code in refinery-modules/refinery/...
```

Look at the history: Maybe it was a refactoring to pull out the details, but never was completed?

**Comment by mccalluc** [comment]
Oh.. I think the one is ignored...

**Comment by hackdna** [comment]
"Once using Librarian-puppet you should not modify the contents of your `modules` directory. The individual modules' repos should be updated, tagged with a new release and the version bumped in your Puppetfile." http://librarian-puppet.com/

**Comment by mccalluc** [comment]
Ok: and in Puppetfile we have
```
mod 'refinery/refinery', :path => "refinery-modules/refinery"
```
to pull it in. Thanks!
