### ISSUE TITLE
Unable to cancel an Analysis

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2171]
* Specific code commit: 2a3c825183c423d388c391f52a18e13d5caa2925
* Environment where the error occurred: `test.stemcellcommons.org`

### Steps to reproduce
Please list all the actions and the input data used:

1.  Execute an `Analysis`
2. Try to click the orange `x` icon in the `Analyses` listing to cancel said `Analysis`

### Observed behavior
![screen shot 2017-09-19 at 11 51 17 am](https://user-images.githubusercontent.com/5629547/30601946-2eea5890-9d31-11e7-9455-31f4c05d5718.png)

- It seems like `bootbox.js` isn't available

### Expected behavior
* For the `Analysis` to be able to be cancelled

**Comment by jkmarx** [comment]
Issue is bootbox is a global dependency which is injected into AngularJS. During the data_set.html cleanup, the library reference was removed.
