### ISSUE TITLE
Strip whitespace before indexing

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2176]
* Specific code commit: 2a3c825183c423d388c391f52a18e13d5caa2925

### Steps to reproduce
@gmnelson noticed this:

1. Crosss-dataset browser 
2. Sort genotype alphabetically

### Observed behavior
In the UI:
<img width="144" alt="screen shot 2017-09-21 at 10 13 10 am" src="https://user-images.githubusercontent.com/730388/30700504-c67bfba2-9eb5-11e7-86a9-128f099d171b.png">

and in the API:
```
            {
                "count": 4,
                "name": " GFP-transfected"
            },
```

### Expected behavior
* Field values should have padding space stripped... probably in `prepare`? Earlier than that there might be different execution paths for ISA and CSV -- Later than that, in the solr field definition, is too obscure.

**Comment by jkmarx** [comment]
Reference #1563
