### ISSUE TITLE
Facet counts behave differently between cross-dataset and within-dataset

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2178]
* Specific code commit: 2a3c825183c423d388c391f52a18e13d5caa2925

### Steps to reproduce

On cross dataset, the counts seem to be the number records with that value in the current found set, while it within dataset, it's more like the number that would be added?

On cross dataset, selecting only a zero valued facet will bring the others to zero, while within dataset, there may be to results, but the other facets will retain their counts.

I'm not clear on what the desired behavior is. For context: #2088 and #2069

**Comment by gmnelson** [comment]
@mccalluc I'd say the desired behavior is how the within-dataset browser is currently handling counts
