### ISSUE TITLE
rename() and rename_datafile() return `None` & mask errors

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2182]
[`rename()`](https://github.com/refinery-platform/refinery-platform/blob/480b2b64f8b06389b324238d01ac8f85bf5cd971/refinery/file_store/tasks.py#L270) & [`rename_datafile()`](https://github.com/refinery-platform/refinery-platform/blob/b7e32345bc4bd34165e1adb268e06b480d754305/refinery/file_store/models.py#L432) should fail appropriately and not return `None` instead

**Comment by jkmarx** [comment]
Ref #3040 & Ref #2725 
Closed by the above pull-requests
