### ISSUE TITLE
blue/green deployment

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2201]
Wondering whether a blue/green approach for deploying Refinery has been considered. It might work something like this: (with new features that would be required italicized)

- At the moment snapshots are taken, we toggle an admin setting that either *makes the DB read-only*, or just puts a *banner on the site* warning that changes will not be saved.
- A new site is deployed with the snapshot, but *the config no longer requires hostname* to be specified in advance.
- Once the new stack is up, it can be inspected: If there is a problem, we make changes and try again
- If there are no problems, add it to the ELB pool, and remove the old instance, and release the AWS resources, either in the aws gui, or with *a script*. (Sessions from the old site to the new site will not carry over, but that's ok.)

Advantages:
- No downtime for read-only access.
- Assurance that behavior of test instance will match production (because they are the same thing).
- One less redeployment required.

Disadvantages:
- New features required.
- If "test" instance is kept around, we'll probably be more adverse to putting it into an odd state.

**Comment by hackdna** [comment]
A couple of additional points:
* Planned downtime is not an issue currently.
* This type of deployment is impossible with the existing monolithic CloudFormation stack.
* The majority of the deployment time is spent on provisioning the AMI from scratch. This will be shortened significantly when we start building custom AMIs.
* DB schema changes are problematic.
Additional info: https://martinfowler.com/bliki/BlueGreenDeployment.html

**Comment by jkmarx** [comment]
Not feasible currently.
