### ISSUE TITLE
Remove config.json before `vagrant up`?

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2218]
Something was wrong with my environment, so I just wanted to start over from the top, but rather than getting a new checkout, I started from my existing. ... but that meant I had an old `config.json` in place that was missing a necessary key.

Could `vagrant up` overwrite `config.json` if it already exists, rather than just taking the existing one? Or is this better done by hand? 

@scottx611x : Do you have an opinion?

**Comment by hackdna** [comment]
Historic reference: https://github.com/refinery-platform/refinery-platform/issues/909 and https://github.com/refinery-platform/refinery-platform/issues/785.

**Comment by mccalluc** [comment]
Closing in favor of #909, which is pretty much the same problem.
