### ISSUE TITLE
File Browser sized just a little too large -> scroll bars on pane

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2220]
* Specific code commit: 8ca14656a4f64a948f8e02ccf5ea46ab2be15c54
* Version of the web browser and OS: FF and Chrome, Mac
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Local dev

### Steps to reproduce
Please list all the actions and the input data used:

1. Fresh install

### Observed behavior

<img width="1074" alt="screen shot 2017-10-10 at 2 38 11 pm" src="https://user-images.githubusercontent.com/730388/31404188-5a6f1570-adc9-11e7-8328-22008bf4ca31.png">

### Expected behavior
There shouldn't be the extra scrollbars: for some reason the main pane wants a little more room than is actually available.

**Comment by jkmarx** [comment]
<img width="1440" alt="screen shot 2017-10-18 at 3 23 47 pm" src="https://user-images.githubusercontent.com/9956764/31738357-63972b10-b418-11e7-9b2e-5b65f2885904.png">

**Comment by jkmarx** [comment]
<img width="1440" alt="screen shot 2017-10-18 at 3 23 31 pm" src="https://user-images.githubusercontent.com/9956764/31738366-6d0a9b14-b418-11e7-92b9-344ad4840c21.png">

**Comment by jkmarx** [comment]
@mccalluc I'm having issues reproducing. Does this only occur with a fresh new instance?
