### ISSUE TITLE
cypress npm dependencies pollute runtime ui... segregate?

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2257]
Cypress is an npm thing, so I placed it under `ui/`... but it probably doesn't belong there: It is javascript, but it has no relationship with our run-time JS. I'm not sure if its dependencies are actually built into our runtime, but at the very least it introduces the possibility for conflicts that weren't there before.

Probably pull it all the way to the top, but maybe there's an argument for only pulling it up one level, to `refinery`?

**Comment by jkmarx** [comment]
Development dependencies should be separate.
