### ISSUE TITLE
Data set link from cross-dataset browser is missing ID, sometimes

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2259]
When Sarah is looking at the cross-dataset browser, the dataset links do not work: The ID is missing from the url. There should be a check that only displays these links when they are valid. Perhaps looking at out-of-date code? b301acb2e32eb5f04cecd7264188154fbfaf5f2c

**Comment by mccalluc** [comment]
When I hit their [api endpoint](https://beta.genometranslationcommons.org/api/v2/files/?fq=&limit=100&sort=), I get back:
```
...
    "nodes": [
        {
            "django_id": "456672",
            "name": "BM_10_609",
            "assay_uuid": "3bbffb2a-6d2e-4253-b99e-83ecfd9bc1ad",
            "file_uuid": "2fdfe413-a304-4a13-8360-57ae69a4c84a",
            "study_uuid": "2bc08eb3-3210-48c8-a01a-38abebcb4ae9",
            "type": "Raw Data File"
        },
...
```

At the very least, for the link to work, it needs a `data_set_uuid`. @drj11 : Would you be able to reindex genometranslationcommons? Or is that not the issue?

**Comment by gmnelson** [comment]
assay_uuid
:
"e4789532-b7a0-4960-9d41-399cc2709854"
django_id
:
"144912"
file_uuid
:
"f2c923e6-1e81-4507-9179-5a5946e4a133"
filename_Characteristics_generic_s
:
"s5_p42_E2_45min.subsample.fastq"
name
:
"s5_p42_E2_45min.subsample.fastq"
organism_Characteristics_generic_s
:
"Human"
sample_id_Characteristics_generic_s
:
"s5_p42_E2_45min.subsample"
study_uuid
:
"1f0c5593-d046-4c8f-850a-d2ed929a6252"
type
:
"Raw Data File"

**Comment by mccalluc** [comment]
Again, data set UUID is missing. Why is it not in solr? To debug, try a reindex: is it failing at that point, or before, or after?

**Comment by gmnelson** [comment]
This seems to be a problem common to all data sets that have recently been uploaded, including: tabular metadata w/ and w/o files, ISA-Tab data set that has been shared with me. I haven't found a recent data set where its files are properly linked (i.e. have a data set UUID in the URL) in the cross-dataset browser.
