### ISSUE TITLE
"visualization tools" as a registry

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2261]
Wondering if it might make sense for the default tool installation to be by name (while retaining by-file as an option): It would find a match at [visualization-tools](https://github.com/refinery-platform/visualization-tools), download the definition from that repo, and install.

One complication would be if Refinery's expectations for format changed radically.

**Comment by mccalluc** [comment]
In this same space: Here's my experience trying to generate tool definitions:
```
$ ./manage.py generate_tool_definitions
Generating ToolDefinitions
2017-11-07 11:10:25 DEBUG    tool_manager.utils:356 get_workflows() - 0 workflow engines found.
```
* It should be made more explicit that either --visualizations or --workflows is required
```
./manage.py generate_tool_definitions --visualizations ~/higlass.json ~/igv.json ~/refinery-developer-tool.json  
Generating ToolDefinitions
```
* It should either accept command line arguments, or error on unexpected ones, and point you in a better direction.

... but if the preferred method were to be referencing by name, both of these are moot.

**Comment by scottx611x** [comment]
@mccalluc can we close this or is there more to do?

Ref: https://github.com/refinery-platform/refinery-platform/pull/2374
