### ISSUE TITLE
"Nightly" deployments from current develop

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2273]
At some point in the recent past we discussed that it would be nifty to have a dev instance available to play around with that was built/updated on every push to `develop`.

Some of my thoughts on how to achieve this:

**Easy:**
We could manually bring up a dev instance once, and update its code with the `fab <stack> update` command from Travis-CI if we detect an update on the `develop` branch. This solution falls short when: deployment code changes, one-off things like updating our Solr index comes into play, or with keeping up-to-date with the data that exists on the test site. Though its fairly quick to implement.

**Less-Easy:**
Build a completely new stack on every push to `develop`. This would be a more robust solution but would require a few extra things that might get hairy. 

We would need to:
- Know about the most up-to-date RDS and EBS snapshots for the beta site are and use those for each new stack creation.
- Be able to monitor stack creation from Travis in case anything goes wrong while `stack.py create` runs in AWS land
- Be able to delete the existing stacks from Travis and ensure that their snapshots are deleted as well
- Be able to reassociate the dev instance's url with newly created ELBs (our Route53 stuff is done manually atm)

Feel free to add any thoughts/questions/concerns

**Comment by jkmarx** [comment]
Closing issue because it hasn't been mentioned as an objective in a year or two.
