### ISSUE TITLE
Use relative size labels to be able to better estimate issue timelines

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2275]
[Relative size estimating](https://www.agilealliance.org/glossary/relative-estimation/#q=~(filters~(postType~(~'page~'post~'aa_book~'aa_event_session~'aa_experience_report~'aa_glossary~'aa_research_paper~'aa_video)~tags~(~'relative*20estimation))~searchTerm~'~sort~false~sortDirection~'asc~page~1)) is a great software development tool and we might be able to benefit from it.

This would allow us to gauge the amount of work we can get done in a milestone over time and would allow for more focused milestone definitions.

For example:

If after 5 milestones it is known that Scott can complete an average of 3 `quick-fix` issues, 2 `medium` issues, and 1 `large` issue per 4 week milestone, we can then use that data to make sure Scott isn't under/over utilized for the upcoming milestone while planning it.

**Comment by hackdna** [comment]
Another piece is a [burn up chart](http://www.clariostechnology.com/productivity/blog/whatisaburnupchart).

**Comment by hackdna** [comment]
On the flip side, simply finish all the issues assigned to a milestone then create a release when done - no estimation required.

**Comment by jkmarx** [comment]
Implemented
