### ISSUE TITLE
Info ? Popover activated/deactivated bug

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2305]
Commit: c67b47e75cc089952cb8cfed9fc41a743cef8856
* Version of the web browser and OS: `Chrome 62.0.3202.75 macOS 10.12.6`
* Environment where the error occurred:  Vagrant VM

### Steps to reproduce
1.  Select a Tool in FB2 that utilizes paired inputs.
2. Expand the `Input Files` section by clicking on it.
3. Click on the `?` next to one of the `Input Files`  to generate a popover.
3. Collapse the `Input Files` section by clicking on its header.
4. Popover is still active.

### Observed behavior
![oct-31-2017 17-17-09](https://user-images.githubusercontent.com/5629547/32249598-f9818886-be5f-11e7-9973-9bd5ddfaf8e6.gif)

### Expected behavior
* Popovers to deactivate

**Comment by jkmarx** [comment]
@scottx611x That's a design choice to click on the ? to deactivate popovers. The issue with focus popovers is when we have links in them (I think). We can switch over to them but this is not a bug.

**Comment by jkmarx** [comment]
@scottx611x We'd want to do it across the board, because I think all the popover ? are like this.

**Comment by scottx611x** [comment]
@jkmarx Okay, thats fine. Even if its not a bug I think its still odd behavior that warrants a fix. Reopening w/o bug label

**Comment by jkmarx** [comment]
@scottx611x On second thought (and closer examination of the giphy), it's a bug. The solution may be to switch to a focus activate/deactivate, but requires more research.

**Comment by jkmarx** [comment]
Scope wise, I'm sure this is exhibited elsewhere.

**Comment by jkmarx** [comment]
Options: 
mouseenter: mouseleave
click: click (currently implemented)
outsideClick: outsideClick
focus: blur
