### ISSUE TITLE
"Data File Column" upload message uses internal absolute path

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2323]
* Specific code commit: 4bd26aff83c2550bd9ee503ed21587c29eef0518
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): local dev

### Steps to reproduce
Please list all the actions and the input data used:

1. Upload a CSV referencing local files, but do not load them
2. Click "Check Data Files"

### Observed behavior
![screen shot 2017-11-03 at 10 13 38 am](https://user-images.githubusercontent.com/730388/32378148-5bbb1270-c080-11e7-8539-b2f63e0a3370.png)

### Expected behavior
* Instead of giving the full destination path, it should just echo the source filename.

**Comment by jkmarx** [comment]
Filename is currently file path.
