### ISSUE TITLE
Meaningful test of update_annotated_nodes

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2329]
I've [introduced a test](https://github.com/refinery-platform/refinery-platform/pull/2300/files#diff-cbd50ad73b641050464ccff9f3787bb9R1408) of `update_annotated_nodes`... but nothing seems to be happening? Look at this more closely and redo the test to assert something meaningful.

**Comment by jkmarx** [comment]
Next person who touches the method will update the unit test accordingly (our typical design process). Closing because I don't think it should be a separate issue.
