### ISSUE TITLE
Does override-config.yaml make things more confusing?

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2334]
I was trying to deploy a new branch for the first time, but it turned out I had one bad setting in my config.yaml. After puppet had run, Scott thought we should be able to enter the Django shell and fix the Site object. That did not fix it, and he thinks that's because the override-config.yaml still had the old setting.

Are we pretty sure `override-config.yaml` is the best way of arranging things?

**Comment by hackdna** [comment]
The `SITE_NAME` setting affects more than just the Site object. Also, we aim for [immutable infrastructure](https://www.digitalocean.com/community/tutorials/what-is-immutable-infrastructure), so failed deployments should be simply replaced to avoid configuration drift.

However, `override-config.yaml` is confusing. Django settings should be managed through `config.json.erb` as it is done in Vagrant.

**Comment by hackdna** [comment]
See also #1232.
