### ISSUE TITLE
Spurious slashes added to source name of data set files

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2340]
* Specific code commit: 09a2aa2e7e739fb286f370258e899dfe27f5d9c5
* Version of the web browser and OS: Any
* Environment where the error occurred: Production test 

### Steps to reproduce
Please list all the actions and the input data used:

1. Compare the "Sources" in the previews of an ISAtab and a CSV

### Observed behavior
<img width="1068" alt="screen shot 2017-11-08 at 11 27 59 am" src="https://user-images.githubusercontent.com/730388/32560722-64bd7b14-c478-11e7-87f4-6bd3831608fa.png">

### Expected behavior
It looks like we have strings in a slot that is expecting an array, so it gets split up by character... But even then, is a list of file extensions what we want here?

Also, if this information matters, should it show up in the Details tab and not just the preview? ... Or maybe it doesn't matter

**Comment by jkmarx** [comment]
Ref #2582

**Comment by jkmarx** [comment]
With v1.6.9 Explore/Satori has been removed.
