### ISSUE TITLE
User/files Empty Columns

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#2350]
* Specific code commit: 09a2aa2e7e739fb286f370258e899dfe27f5d9c5
* Version of the web browser and OS: Mac OSX
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): 
 Test site

### Steps to reproduce
Please list all the actions and the input data used:

1.  Open the user files page
2. Sort Date or Experimenter

### Observed behavior
![column-empty](https://user-images.githubusercontent.com/9956764/32624244-a3ab7978-c556-11e7-93bd-8e27405ac9c2.gif)

### Expected behavior
* If columns are empty, should they even be shown?

**Comment by gmnelson** [comment]
@jkmarx : The Shivdasani Lab's metadata template should populate all columns, though currently nothing is displayed for 'Date'. They have two fields in their template, 'Date_submitted' and 'Date_received', that are relevant here.

If the cross-data set browser could display one of these (preferably 'Date_submitted') in the 'Date' field, then we'd avoid empty columns, at least for our current primary users.

**Comment by mccalluc** [comment]
@gmnelson : These are different issues. I've added "Date submitted" to the list on #2458. Thanks!

**Comment by jkmarx** [comment]
https://gitter.im/angular-ui/ui-grid/archives/2014/12/18
