### ISSUE TITLE
Recent Analyses Popover spacing

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2351]
* Specific code commit: 09a2aa2e7e739fb286f370258e899dfe27f5d9c5
* Version of the web browser and OS: Chrome Linux
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): 
 Test site
### Steps to reproduce
Please list all the actions and the input data used:

1. Click on the `View Recent Analyses` cog in the top right of Refinery

### Observed behavior
* Test Site:
![screen shot 2017-11-09 at 2 04 59 pm](https://user-images.githubusercontent.com/5629547/32624401-33f2d2ec-c557-11e7-93ce-649c87446596.png)

* Beta Site:
![screen shot 2017-11-09 at 2 04 45 pm](https://user-images.githubusercontent.com/5629547/32624406-37d95b4c-c557-11e7-84ba-387316f388bf.png)

### Expected behavior
* For the spacing not to have changed

**Comment by jkmarx** [comment]
![screen shot 2018-11-01 at 8 34 56 am](https://user-images.githubusercontent.com/9956764/47852091-08b79900-ddb1-11e8-8f02-88ed2e05249b.png)
