### ISSUE TITLE
Details > History > "Import into own space" should get grey background

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2356]
* Specific code commit: 09a2aa2e7e739fb286f370258e899dfe27f5d9c5
* Version of the web browser and OS: OSX FF
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Prod test

### Observed behavior
* We never use buttons with just a white background
![screen shot 2017-11-09 at 3 13 21 pm](https://user-images.githubusercontent.com/730388/32627522-b5e9e07a-c560-11e7-8551-155ae4e11a65.png)

### Expected behavior
* Should be grey like others.

**Comment by jkmarx** [comment]
Resolves by #2472
