### ISSUE TITLE
Extra closing quote in group help pop over

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2362]
![screen shot 2017-11-13 at 10 04 17 am](https://user-images.githubusercontent.com/730388/32732297-255d5044-c85a-11e7-8b45-0d956fb40377.png)

(Notice the quotation mark at the end.)

**Comment by jkmarx** [comment]
Issue got resolved at some point. Popover is shared between component.
Recent, local instance.
<img width="289" alt="screen shot 2018-03-14 at 2 37 30 pm" src="https://user-images.githubusercontent.com/9956764/37423948-8f38fc8a-2795-11e8-9013-936aba635d80.png">
