### ISSUE TITLE
Data sets text search hides sort options

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2363]
* Specific code commit: 7e8847fb36e4a64352247def0ff60fad095abcef
* Version of the web browser and OS: osx, ff and chrome
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): prod test

### Steps to reproduce

1. Bring up the dashboard (old)
2. Do a text search for data sets

### Observed behavior
* The double headed arrow for sort disappears
* If you're logged in, the filter menu also disappears

### Expected behavior
* Maybe there's a reason that group filter and text filter can't be done at the same time, but it seems arbitrary not to let the user sort the list.

**Comment by jkmarx** [comment]
With v1.6.9 Explore/Satori has been removed.
