### ISSUE TITLE
Spurious error message in SharableResourceAPIInterface

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2378]
* Specific code commit: 34e202dd
* Version of the web browser and OS: any
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): any

### Steps to reproduce
Open the Launch Pad in a web browser as an anonymous user

### Observed behavior
One or more error messages in the Refinery log:
```
2017-11-15 12:01:01 ERROR    core.api:136 transform_res_list() - User: 's profile or UUID not available.
```

### Expected behavior
No error messages

**Comment by jkmarx** [comment]
No longer use launch pad removed v1.6.8. Shareable resource api removed in v1.6.9
