### ISSUE TITLE
Analysis Filters don't seem to work on some Analyses

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2383]
* Specific code commit: b301acb2e32eb5f04cecd7264188154fbfaf5f2c
* Version of the web browser and OS: any
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): 
`beta.stemcellcommons.org`
### Steps to reproduce
1.  go here: https://beta.stemcellcommons.org/data_sets/ca5ac159-4468-4317-b03d-e9d00550f3e1/#/files/
2. Filter by :`RNA-seq paired end with TopHat - hg19 2017-8-1@12:10:41`

### Observed behavior
* The url is updated -> https://beta.stemcellcommons.org/data_sets/ca5ac159-4468-4317-b03d-e9d00550f3e1/#/files/?%7B%22REFINERY_ANALYSIS_UUID_604_306_s%22:%22RNA-seq%2520paired%2520end%2520with%2520TopHat%2520-%2520hg19%25202017-8-1%254012%253A10%253A41%22%7D but the listing is empty
![screen shot 2017-11-16 at 4 36 55 pm](https://user-images.githubusercontent.com/5629547/32917213-7912a88a-caec-11e7-8451-f5a6539cdf16.png)
* This behavior does not seem to exist when filtering with newer Analyses
* No console errors

### Expected behavior
* To be able to filter on any Analysis

### General Notes
* Newer Analyses names don't have an `@` symbol in them like the legacy ones do. Not sure if this would affect filtering, but it could be a lead to fix the issue?

**Comment by scottx611x** [comment]
I observed this again today. Commit c8a9cb3f93

**Comment by jkmarx** [comment]
I saw it on beta today again.
