### ISSUE TITLE
Assert method calls only in test cases

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2407]
It is confusing to have assert methods in places other than test cases. For example, [delete_from_ui()](https://github.com/refinery-platform/refinery-platform/blob/95c6c7439f39fd2ccc4f76ded0fbdff1e94a761c/refinery/selenium_testing/utils.py#L167) is not a test case and it contains calls to `assert_text_within_id()`. Only test cases should be doing actual testing.

Two Scoops of Django 22.3.4: "Don't Repeat Yourself Doesn't Apply to Writing Tests"

**Comment by jkmarx** [comment]
Agreed to avoid having assert methods outside of tests.
