### ISSUE TITLE
Submit button on data set upload form is not changing its state on AWS

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2412]
* Specific code commit: e2bb3a6
* Version of the web browser and OS: any
* Environment where the error occurred: AWS

### Steps to reproduce
1. Navigate to the tabular metadata import form
1. Load a metadata file
1. Add one data file

### Observed behavior
Submit button is still enabled

### Expected behavior
Submit button should be disabled until the file is either uploaded or removed

### Notes
The state of Submit button is controlled with `metadataTable.areFilesInQueue()` and `fileUploadStatusService.fileUploadStatus`.

**Comment by jkmarx** [comment]
Closed in favor of #2691
