### ISSUE TITLE
VisualizationTool launches should have access to **all** of a Dataset's Node metadata information

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2413]
The [current implementation](https://github.com/refinery-platform/refinery-platform/blob/master/refinery/tool_manager/models.py#L423-L432) only sends `Node` information over for `Nodes` that were selected in the Tool Launch UI. 

Out of @mccalluc & @ngehlenborg  conversation today we now want to send over all the Node info related to the Dataset.

Implementation Notes:
- [ ] `file_relationship_urls` shouldn't be used in `_create_container_input_dict` anymore since we have access to file url info through Nodes
- [ ] We should still preserve the file relationship structure of the `file_relationships` key, except with Node uuids instead of urls, and the name in json should change. (`node_relationships`?)
- [ ] `update_file_relationships_with_urls` should be refactored to update the file relationships with `Node` uuids only , and should be renamed (`update_file_relationships_with_node_uuids` ?)
- [ ] Some of our existing Vis Tools probably won't like these changes so those should be updated to work properly

#### Edit: Not worrying so much about these checkboxes as theres no concrete use case for all of this extra Node information atm, and addressing the checkboxes would cause lots of backwards incompatibility with current vis tools. [Getting all of the DataSet's Node info into the input.json](https://github.com/refinery-platform/refinery-platform/pull/2569) should suffice for now.

**Comment by scottx611x** [comment]
Ping @mccalluc in case I missed anything

**Comment by mccalluc** [comment]
Looks good; one small edit.
