### ISSUE TITLE
All Files Browser: Chrome is mis-encoding an API url

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2425]
* Specific code commit: d29c88513b553d70b5fdd23c8175187e03bd687d
* Version of the web browser and OS: Version 62.0.3202.89 (Official Build) (64-bit)
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): beta production

### Steps to reproduce

1. Visit https://beta.stemcellcommons.org/files/#?organism=Human

### Observed behavior
* Note that there are no results found
* In the developer tools, you can see a request being made to 
```
https://beta.stemcellcommons.org/api/v2/files/?fq=((organism_Characteristics_generic_s:%22Human%22+OR+organism_Factor_Value_generic_s:%22Human%22))&limit=100&sort=
```
* In contrast, on firefox:
```
https://beta.stemcellcommons.org/api/v2/files/?fq=((organism_Characteristics_generic_s:"Human"+OR+organism_Factor_Value_generic_s:"Human"))&limit=100&sort=
```

Why is the URL encoding different? And why does it make a difference?

**Comment by jkmarx** [comment]
It seems to work now since the user/files update to fix the filtering. @mccalluc Please reopen if you can reproduce.
