### ISSUE TITLE
Results missing from some successful analyses

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2426]
* Specific code commit: v1.6.1
* Version of the web browser and OS: Chrome and Firefox on OS X
* Environment where the error occurred: beta.stemcellcommons.org

### Steps to reproduce
Open a successfully completed analysis. For example:
* https://beta.stemcellcommons.org/data_sets/c4494a99-01fa-4e3f-a478-af54ad497e90/#/files/?%7B%22REFINERY_ANALYSIS_UUID_230_115_s%22:%22RNA-seq%20single%20end%20with%20TopHat%20-%20hg19%202017-1-25@13:10:13%22%7D
* https://beta.stemcellcommons.org/data_sets/29610f2d-4b62-423c-be36-10cbbb3e6dc3/#/files/?%7B%22REFINERY_ANALYSIS_UUID_152_76_s%22:%22FastQC%202016-10-4@13:21:49%22%7D
* https://beta.stemcellcommons.org/data_sets/29610f2d-4b62-423c-be36-10cbbb3e6dc3/#/files/?%7B%22REFINERY_ANALYSIS_UUID_152_76_s%22:%22TF%20ChIP-Seq%20analysis%20using%20MACS2:%20danRer7%202016-5-19@8:24:42%22%7D
* https://beta.stemcellcommons.org/data_sets/6b3303bc-ef3c-4352-993c-e93c1b880082/#/files/?%7B%22REFINERY_ANALYSIS_UUID_6_3_s%22:%22Test%20workflow:%205%20steps%20without%20branching%202016-12-7@6:42:19%22%7D

### Observed behavior
Analysis results are missing. No errors in the web console. Repeating warnings in the server log (one per analysis result?):
```
[Tue Dec 12 16:03:35.820208 2017] [:error] [pid 4917:tid 140457003714304] 2017-12-12 16:03:35 WARNING  core.api:1112 dehydrate() - Unable to find file store item with UUID 'None'
```

### Expected behavior
Analysis results displayed. No errors in the server log.

**Comment by scottx611x** [comment]
Duplicate of https://github.com/refinery-platform/refinery-platform/issues/2383 ?

**Comment by hackdna** [comment]
Yes, it looks like it. If I remove the filters I can see the results.
