### ISSUE TITLE
Download links not displayed in the data set view

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2434]
* Specific code commit: 5f4109d
* Version of the web browser and OS: Chrome on OS X 10.12.6
* Environment where the error occurred: Vagrant VM

### Steps to reproduce
Import a data set ([example](http://data.cloud.refinery-platform.org.s3.amazonaws.com/data/sample-data/human-chipseq/hg19-metadata-local.txt)) and upload one of the data files.

### Observed behavior
There is no download link for the uploaded file in the data set view. 

### Expected behavior
Download link for the uploaded file should be displayed.

### Notes
No errors in either browser console or server log. FileStoreItem is created and the data file is downloadable in Django admin.

**Comment by jkmarx** [comment]
Refinery_download URL missing from API response.

**Comment by jkmarx** [comment]
Bug is observed on the beta site but is masked because the File Browser makes separate API calls. The API is not returning the refinery_download field from solr for the hg19 dataset but is returning it from other isa-tab files on the site. I don't think it's a perms issue.

**Comment by mccalluc** [comment]
The indexing takes place in `data_set_manager/search_indexes.py`:
```python
    def prepare(self, object):
        data = super(NodeIndex, self).prepare(object)
        ...
        data.update(self._assay_data(object))
        ...
        try:
            file_store_item = FileStoreItem.objects.get(
                uuid=object.file_uuid)
        ...
        data.update({
            NodeIndex.DOWNLOAD_URL:
                '' if file_store_item is None
                else file_store_item.get_datafile_url(),
            ...
        })
        ...
```

- I would want to see if the missing url is caused by the `if file_store_item is None`
- I also wonder if calling `data.update` twice is a bad thing? Though I don't see any connection between that and the immediate problem.

**Comment by jkmarx** [comment]
There are two bugs here. 
- The first is a timing issue: the node file is not finished uploading. When the node indexing occurs it can be missing the file path therefore no refinery_download_url. We discussed a solution involving pinging the node api for missing node url. This doesn't address the underlying issue with needing to reindex after the uploads are completed.
 - The second issue is solr is not responding with the nodes with a download url when any are missing.

**Comment by jkmarx** [comment]
``` def get_import_status(self):
        """Return file import task state"""
        return AsyncResult(self.import_task_id).state ```

When the node is being index, the file store item import status returns success even though the file path is missing.

**Comment by jkmarx** [comment]
Setting up a temp url for import state == pending, bypasses bug #2 and allows for the other nodes' file_download_urls to be returned. In the image below, the first three download urls are the temps and the fourth node has the correct download url.
![Uploading Screen Shot 2018-01-08 at 9.16.52 PM.png…]()

**Comment by jkmarx** [comment]
- [ ] Return a 'downloading in-progress' signifier when import is in progress
- [ ] Reindex with the node import completes
- [ ] Update UI to show user the download is in progress
