### ISSUE TITLE
IGV internal server error due to HTTP Error 404

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2450]
* Specific code commit: v1.6.1
* Version of the web browser and OS: N/A
* Environment where the error occurred: AWS

### Steps to reproduce
From @gmnelson: "I launched IGV on the beta site a few min ago and it was laggy to load and displayed a bit strangely (no gene tracks as before)"

### Observed behavior
373 internal server error reports in the span of 27 minutes:
```
Internal Server Error: /img/igv_logo_letters_paths.svg
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django_docker_engine/proxy.py", line 72, in _proxy_view
    return view(request, url=url)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/httpproxy/views.py", line 82, in dispatch
    response = super(HttpProxy, self).dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/httpproxy/views.py", line 141, in get
    return self.get_response()
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/httpproxy/views.py", line 166, in get_response
    response = urllib.request.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: File not found

Request repr():
<WSGIRequest
path:/img/igv_logo_letters_paths.svg,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{'_ga': 'GA1.2.924692811.1513653892',
'_gid': 'GA1.2.2010275775.1513653892',
'csrftoken': <redacted>,
'sessionid': <redacted>},
META:{'CONTEXT_DOCUMENT_ROOT': '/var/www',
'CONTEXT_PREFIX': '',
u'CSRF_COOKIE': <redacted>,
'DOCUMENT_ROOT': '/var/www',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': 'image/webp,image/apng,image/*,*/*;q=0.8',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.9',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_COOKIE': 'sessionid=<redacted>; csrftoken=<redacted>; _ga=GA1.2.924692811.1513653892; _gid=GA1.2.2010275775.1513653892',
'HTTP_HOST': 'beta.stemcellcommons.org',
'HTTP_REFERER': 'https://beta.stemcellcommons.org/visualizations/IGV-launch-c22e4fe8-287f-4751-8279-ea4728f5bac5/igv.css',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36',
'HTTP_X_FORWARDED_FOR': '71.232.100.43',
'HTTP_X_FORWARDED_PORT': '443',
'HTTP_X_FORWARDED_PROTO': 'https',
'PATH_INFO': u'/img/igv_logo_letters_paths.svg',
'PATH_TRANSLATED': '/srv/refinery-platform/refinery/config/wsgi_aws.py/visualizations/IGV-launch-c22e4fe8-287f-4751-8279-ea4728f5bac5/img/igv_logo_letters_paths.svg',
'QUERY_STRING': '',
'REMOTE_ADDR': '172.31.59.31',
'REMOTE_PORT': '58047',
'REQUEST_METHOD': 'GET',
'REQUEST_SCHEME': 'http',
'REQUEST_URI': '/visualizations/IGV-launch-c22e4fe8-287f-4751-8279-ea4728f5bac5/img/igv_logo_letters_paths.svg',
'SCRIPT_FILENAME': '/srv/refinery-platform/refinery/config/wsgi_aws.py',
'SCRIPT_NAME': u'',
'SCRIPT_URI': 'http://beta.stemcellcommons.org/visualizations/IGV-launch-c22e4fe8-287f-4751-8279-ea4728f5bac5/img/igv_logo_letters_paths.svg',
'SCRIPT_URL': '/visualizations/IGV-launch-c22e4fe8-287f-4751-8279-ea4728f5bac5/img/igv_logo_letters_paths.svg',
'SERVER_ADDR': '172.31.61.115',
'SERVER_ADMIN': '[no address given]',
'SERVER_NAME': 'beta.stemcellcommons.org',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SIGNATURE': '',
'SERVER_SOFTWARE': 'Apache/2.4.7 (Ubuntu)',
'mod_wsgi.application_group': 'beta.stemcellcommons.org|',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.enable_sendfile': '0',
'mod_wsgi.handler_script': '',
'mod_wsgi.input_chunked': '0',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '80',
'mod_wsgi.process_group': 'refinery',
'mod_wsgi.queue_start': '1513752112556616',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.version': (3, 4),
'wsgi.errors': <mod_wsgi.Log object at 0x7f5d7565b0b0>,
'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f5d74f2db70>,
'wsgi.input': <mod_wsgi.Input object at 0x7f5d7565b730>,
'wsgi.multiprocess': False,
'wsgi.multithread': True,
'wsgi.run_once': False,
'wsgi.url_scheme': 'http',
'wsgi.version': (1, 0)}>
```

### Expected behavior
No errors

### Notes
This error also shows up in tests ([example](https://api.travis-ci.org/v3/job/319211606/log.txt)):
```
2017-12-20 10:34:38 ERROR    django.request:231 handle_uncaught_exception() - Internal Server Error: /img/igv_logo_letters_paths.svg
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/django_docker_engine/proxy.py", line 72, in _proxy_view
    return view(request, url=url)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/httpproxy/views.py", line 82, in dispatch
    response = super(HttpProxy, self).dispatch(request, *args, **kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/httpproxy/views.py", line 141, in get
    return self.get_response()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/httpproxy/views.py", line 166, in get_response
    response = urllib.request.urlopen(request)
  File "/opt/python/2.7.14/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/python/2.7.14/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/opt/python/2.7.14/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/python/2.7.14/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/opt/python/2.7.14/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/opt/python/2.7.14/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: File not found
```

**Comment by ngehlenborg** [comment]
@gmnelson: could you please try to provide a more detailed description of what you did to launch IGV when this happened?

**Comment by gmnelson** [comment]
@ngehlenborg:

1. Selected 'IGV' within the Tool Panel
2. Added a bedGraph and a bigWig file as 'Input Files' (these files are in the 'tutorial' data set that has now been shared with the Testing group)
3. Clicked 'Launch'
4. Searched 'chr12:1-35,000,000' in the IGV search box

After this search, what IGV displayed did not look like what I was expecting (e.g. no gene tracks), and the error report e-mails started arriving.

**Comment by mccalluc** [comment]
There's only one line in the stack trace that's actually in our code:
```
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/django_docker_engine/proxy.py", line 72, in _proxy_view
    return view(request, url=url)
```
I've just filed https://github.com/refinery-platform/django_docker_engine/issues/97 to log the error instead of passing it up the stack, and I will close this, since I don't think any action is required in here.

**Comment by hackdna** [comment]
The root cause is missing `/visualizations/IGV-launch-c22e4fe8-287f-4751-8279-ea4728f5bac5/img/igv_logo_letters_paths.svg`. Logging this instead of fixing would just add noise to the log.

**Comment by scottx611x** [comment]
Running into this again. 

Wouldn't logging these errors be alright in this scenario? 

I don't think that we can assume that `Visualization Tools` that people create will be error free, and I would imagine that folks attempting to integrate their `Tools` with Refinery would like to know about the errors their `Tools` are creating without seeing 500s.

**Comment by hackdna** [comment]
Sure, logging could be useful in the long term. However, the real issue here is that a simple action of launching an IGV visualization can fail and produce hundreds of errors. I don't think silencing these errors without addressing the root cause is the correct approach.

**Comment by ngehlenborg** [comment]
In this case we should fix the problem if there is a fix but in general we need a solution that works for cases when a tools breaks unexpectedly.  I guess that we are seeing this specific error so many times due to how IGV is trying to access the missing file. 

I think we should consider:

1. Logging all errors. If we observe issues like the above, we should try to fix them asap so that our logs don't get clogged with repetitive error messages.
2. Throttling error emails. This could be handled through some sort of digest function. We should look for Python packages that support this.

**Comment by hackdna** [comment]
Error emails are only sent out when the application crashes (which should not happen, especially not when a tool simply raises an HTTP404), so throttling them is counterproductive because it would only mask the underlying problem with error handling and would further increase codebase maintenance burden.

**Comment by ngehlenborg** [comment]
We need to address this very specific issue in IGV at a minimum.

Here is also a simple error email throttling example (which could be stage 2 of addressing this): https://stackoverflow.com/questions/2052284/how-to-throttle-django-error-emails

**Comment by mccalluc** [comment]
Chiming in:
- I've started a [branch in django_docker](https://github.com/refinery-platform/django_docker_engine/compare/mccalluc/do-not-propagate-errors?expand=1) to make these errors quieter.
- Since it's hitting the proxy, I don't think it's an absolute URL issue, and turning on hostname routing is not a solution.
- The path in question is not referenced in the current IGV codebase, as far as I can tell. Could try upgrading, and pushing a new docker image wrapper.
- Short of that, I don't think there is really any code on our end to fix: The docker container is just a wrapper for their JS, and I don't think we should feel forced to fork their code.

**Comment by mccalluc** [comment]
More context on where the url reference is coming from:
- Here it is in the latest release tag, 1.0.9, essentially unchanged from 1.0.8, which our docker image is currently based on: https://github.com/igvteam/igv.js/blob/v1.0.9/css/igv.css#L628-L666
- In the latest code, the name changes to `igv-logo.svg`, but otherwise the CSS seems pretty much the same: https://github.com/igvteam/igv.js/blob/master/css/igv.css#L106-L131

**Comment by hackdna** [comment]
The image is here: http://igv.org/web/release/1.0.8/img/igv_logo_letters_paths.svg
It looks like it simply needs to be added to the [Dockerfile](https://github.com/refinery-platform/docker_igv_js/blob/master/context/Dockerfile) of docker_igv_js.

**Comment by hackdna** [comment]
FWIW, the number of emails is simply due to the [Googlebot](https://support.google.com/webmasters/answer/80553) crawling the site.
```bash
$ host 66.249.89.14
14.89.249.66.in-addr.arpa domain name pointer rate-limited-proxy-66-249-89-14.google.com
```

**Comment by scottx611x** [comment]
This has been addressed with the addition of `django_docker_engine==0.42.2` from #2597 along with the [addition of the missing svg file in igv](https://github.com/refinery-platform/docker_igv_js/blob/v0.0.7/context/Dockerfile#L22)
