### ISSUE TITLE
HTTP 500 error in DataSet API

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2451]
* Specific code commit: v1.6.1
* Version of the web browser and OS: N/A
* Environment where the error occurred: any

### Steps to reproduce
Access DataSet API using a query that returns an object that doesn't have a isarchive_file or pre_isarchive_file

### Observed behavior
DataSet API returns HTTP 500 error. Server log shows:
```
2017-12-20 14:22:27 DEBUG    core.models:754 get_pre_isa_archive() - Couldn't fetch FileStoreItem: FileStoreItem matching query does not exist.
[20/Dec/2017 14:22:27] "GET /api/v1/data_sets/?format=json&limit=50&offset=0&order_by=-modification_date HTTP/1.1" 500 2068
```

### Expected behavior
No HTTP 500 error

### Notes
`DataSet.get_isa_archive()` and `DataSet.get_pre_isa_archive()` can fail to return a value and there is no error handling for this condition in `DataSetResource.dehydrate()`.

**Comment by jkmarx** [comment]
No longer used the data set api to query data sets since launch pad was removed in v1.6.8
