### ISSUE TITLE
Add read-meta perms to existing dataset objs w/ read perm

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#2455]
With pull request #2409 , read-meta became the base level permission for data set objs.

- [x] Add any groups/users with read_dataset perms, should also have read_meta_dataset perms
(Pretty sure this effects public data sets (public_res_set ) https://github.com/refinery-platform/refinery-platform/pull/2409/files#diff-5ef7bea490eb7168eff6377e386b3886R135-R220 )

**Comment by scottx611x** [comment]
@jkmarx So I've added the `read_meta_dataset` permission to all existing Group's & Users on a per DataSet basis. See [here](https://github.com/refinery-platform/refinery-platform/pull/2457/files#diff-515561d075e29f2be51a0f84b451757dR13). 

I'm still seeing some odd behavior though ([dev.cloud.refinery-platform.org](http://dev.cloud.refinery-platform.org)).

- A dataset that has been shared with me w/ that I have Modify Permissions on has no Download links
![screen shot 2018-01-09 at 10 26 07 am](https://user-images.githubusercontent.com/5629547/34728335-a0a67f24-f527-11e7-8a6c-7085b88c7bdd.png)

- A dataset that has been shared with me w/ that I have Read Permissions on has no Download links
![screen shot 2018-01-09 at 1 40 54 pm](https://user-images.githubusercontent.com/5629547/34737025-d9c900f4-f542-11e7-8f02-13eec98a222e.png)

- The Show Tool Panel button still exists for datasets with read meta only perm
![screen shot 2018-01-09 at 1 38 58 pm](https://user-images.githubusercontent.com/5629547/34736916-8d179414-f542-11e7-9547-4b0dcffa149e.png)

If you could poke around and confirm/deny that the behavior I'm seeing is/isn't a side-effect of #2434 that would be really helpful!

**Comment by jkmarx** [comment]
@scottx611x 
1) DataSet tutorial -> can you confirm the name column is missing? If so, this is a bug....
2) DataSet 11445 -> the name column and download column disappears if the user has read_meta perms only. In the above example, we can still see the name column which means the missing download column is due to the index bug.
3) I thought we agreed users can launch visualizations with read_meta only -- so this behavior is correct.

**Comment by scottx611x** [comment]
@jkmarx 

1. `Name` is there just way to the right hidden in that pic
2.  👍  🆒  🆒  🆒  👍 
3. I think we are just allowing launch if the user has read perms because allowing launch with `core.read_meta_dataset` permission would end up exposing datafile urls circumventing the read_meta idea
