### ISSUE TITLE
Add columns/facets to cross filebrowser to meet Shivdasani lab needs

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2458]
Talking with @gmnelson: Currently we have a column for the filename. Instead:
- Have a column for the sample name: This should be filled in, and is more likely to be useful: The filename could have been chosen arbitrarily by the processing center.
- Have a column for the original local path: This is actually what the lab needs, since they will only be using it for metadata.
- Add a filetype facet, and a column, because a facet without a column might be odd?
- and *remove* the current filename column: It is redundant with path.

And:
- Change "Date" to "Date Submitted" (but there seems to be some deeper problem with the rendering of the Date column? #2350)

**Comment by jkmarx** [comment]
@mccalluc I'd be hesitate to remove filename since it's used so much in the filebrowser. 

@mccalluc Should it be file_type or filetype? local_path or originial_local_path?

**Comment by jkmarx** [comment]
@gmnelson Current columns: ```USER_FILES_COLUMNS: "filename,organism,technology,antibody,date_submitted,
genotype,experimenter,cell_type,sample_name,local_path,filetype"```

**Comment by gmnelson** [comment]
@jkmarx Looks good, except I would argue that since ```local_path``` contains the filename that ```filename``` is probably not necessary. Is there something important about having a standalone ```filename``` field?

@jkmarx Excluding ```filename``` for the moment, those current columns sound good. Can we rearrange the order to be:

```sample_name, local_path, filetype, organism, technology, genotype, cell_type, antibody, experimenter, date_submitted```?

**Comment by jkmarx** [comment]
@gmnelson I guess it's only semi-arugment is uniformity btwn file_browser & user_files. It's not a strong argument..just a hesitation. Let's see what @mccalluc says.  
I'd say yes to the rearranging.

**Comment by mccalluc** [comment]
I don't have strong preferences here, except that that some day this should be per-user: Whatever columns make the most sense for the immediate future. Thanks!

**Comment by jkmarx** [comment]
@mccalluc Thanks for reminding me about the per-user. Sure, I'll remove filename then. :)
