### ISSUE TITLE
Remove visualization_manager Django app

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2464]
We think VisualizationManager was not the first iteration, but it has been supplanted by all the django_docker_proxy stuff. It should be removed.

It appears to be unused, except for `igv_multi_species()` function in [core/views.py](https://github.com/refinery-platform/refinery-platform/blob/develop/refinery/core/views.py#L628)

See also #2393

**Comment by hackdna** [comment]
I still see this app present in the codebase (d87a66f).

**Comment by jkmarx** [comment]
@hackdna It was resolved by the remove_solr_igv dependencies which is merged in the django 1.8 release branch. It should be merged to develop this week.

**Comment by hackdna** [comment]
Shouldn't issues be closed when the code is merged into the develop branch?
