### ISSUE TITLE
Wrong highlighting, old popover stuck, first page of tutorial

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2485]
* Specific code commit: 8b2625abbe58f0bd0807aec82789c10a4c1152b6
* Version of the web browser and OS: Mac FF
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Test Prod

### Steps to reproduce
Please list all the actions and the input data used:

1. Log in
2. Click "Help" at the top
3. Click "Start Launchpad tutorial"

(I think this is not a 100% reproducer, but it's pretty close: There may be a race condition in here somewhere.)

### Observed behavior
![screen shot 2018-01-18 at 11 48 04 am](https://user-images.githubusercontent.com/730388/35110322-8856f036-fc46-11e7-9fb2-bc435bf4e32c.png)

- The original popover is still there in the background.
- The banner is not getting the appropriate light background

**Comment by scottx611x** [comment]
Related to https://github.com/refinery-platform/refinery-platform/issues/1417

**Comment by jkmarx** [comment]
We disabled the tutorial feature when we transitioned to the new landing page. This buggy page will need to be rewritten regardless, since the old exploration and collaboration page no longer exists. Closing for now.
