### ISSUE TITLE
Tutorial checkmarks not updated until page reload

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2486]
* Specific code commit: 8b2625abbe58f0bd0807aec82789c10a4c1152b6
* Version of the web browser and OS: Mac FF and Chrome
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Test Prod

### Steps to reproduce

1. Login and click "Help"
2. Run through a tutorial
3. Without leaving or reloading the page, click "Help" again

### Observed behavior
* The checkbox state will not be updated, but if you reload the page it will be.

**Comment by jkmarx** [comment]
Duplicate https://github.com/refinery-platform/refinery-platform/issues/1417
