### ISSUE TITLE
Remove "File Display" / "Table View" selector if there are not actually any choices

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2500]
* Specific code commit: 8b2625abbe58f0bd0807aec82789c10a4c1152b6

### Observed behavior
* I don't believe we currently have any views beyond "Table View" ... Until we do, would we like to get rid of this to minimize distractions?

**Comment by jkmarx** [comment]
I'd agree. @ngehlenborg

**Comment by jkmarx** [comment]
@ngehlenborg  Thoughts?

**Comment by ngehlenborg** [comment]
Ok to get rid of this for now.
