### ISSUE TITLE
Provenance Graph fails to load on some DataSets

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2501]
* Specific code commit: 8b2625abbe58f0bd0807aec82789c10a4c1152b6
* Version of the web browser and OS: Mac FF and Chrome
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Test Prod

### Steps to reproduce

https://test.stemcellcommons.org/data_sets/fdec5d74-4efd-4e07-a7fc-a2a4330ff0b3/#/provvis/ or https://test.stemcellcommons.org/data_sets/eae97d1d-8dd7-477f-8281-9ced8ffa9404/#/provvis/
Never gets past "Loading graph..."

Chrome:
```
provvis.js:7690 Uncaught TypeError: Cannot read property 'children' of undefined
    at g (provvis.js:7690)
    at Object.c [as runLayer] (provvis.js:7463)
    at provvis.js:10001
    at Object.<anonymous> (d3.min.js:1)
    at Object.t (d3.min.js:1)
    at XMLHttpRequest.u (d3.min.js:1)
```

FF:
```
TypeError: a[0][0] is undefined
```

**Comment by jkmarx** [comment]
Both data sets have missing fields. I'm assuming it's related to the failure to load the graph. We should add a time out when the graph can't load.
<img width="1165" alt="screen shot 2018-01-18 at 7 12 34 pm" src="https://user-images.githubusercontent.com/9956764/35128291-c83212b6-fc83-11e7-8865-339ed028e6e1.png">

<img width="1143" alt="screen shot 2018-01-18 at 7 14 33 pm" src="https://user-images.githubusercontent.com/9956764/35128309-ebcdb144-fc83-11e7-8bba-b3128e4e06b6.png">

**Comment by jkmarx** [comment]
@scottx611x This data sets are missing nodes on the test site. I just checked on the beta site.
https://beta.stemcellcommons.org/data_sets/89cbece0-6485-4a4f-9d1e-71f9897343a9/#/files/

https://beta.stemcellcommons.org/data_sets/eae97d1d-8dd7-477f-8281-9ced8ffa9404/#/files/

This seems like a bigger issue.

**Comment by scottx611x** [comment]
To me, this looks like a bug due to a mixture of the side effect of [this issue](https://github.com/refinery-platform/refinery-platform/issues/2293) (this behavior doesn't happen anymore) and the fact that we had to run the `rebuild_index` command instead of `update_index` to be able to void any existing `Nodes` who's `type` wasn't in `Node.INDEXED_FILES`.

One solution would simply be to delete the faulty analyses from the beta site

**Comment by scottx611x** [comment]
@mccalluc @jkmarx So The test site has since been updated to include the changes from #2524 and there aren't any Nodes with missing fields in the index anymore. 

The provenance graph still fails to load. I'm going to update this issue accordingly

**Comment by jkmarx** [comment]
https://test.stemcellcommons.org/data_sets/89cbece0-6485-4a4f-9d1e-71f9897343a9/#/provvis/
The admin owns data set loads the provenance fine. 
So I'm wondering if I had deleted an analysis at some point, which is a known provvis issue. I'm going to delete the dataset and reimport & run a new analysis.

**Comment by jkmarx** [comment]
It seems to be an issue with Chip Seq workflows. After I ran the analysis, the provvis failed. On another data set Data Set 14909: Genome-wide location analysis of BMP (SMAD1) in mouse erythroid progenitors co-occupted with lineage specific regulators (GATA1, GATA2), I ran a fast qc and the provvis loaded fine. 

The beta site seems to be exhibiting the same behavior with the same error. So this is not a new bug, but one which should be addressed. https://beta.stemcellcommons.org/data_sets/eae97d1d-8dd7-477f-8281-9ced8ffa9404/#/provvis/
https://beta.stemcellcommons.org/data_sets/fdec5d74-4efd-4e07-a7fc-a2a4330ff0b3/#/provvis/

**Comment by mccalluc** [comment]
Still happening with v1.6.5 with ChIP seq workflows.

**Comment by ilan-gold** [comment]
On the develop branch, I get the following problem: 
<img width="1919" alt="Screen Shot 2019-10-30 at 3 01 18 PM" src="https://user-images.githubusercontent.com/43999641/67890015-45ce7c80-fb26-11e9-948e-2bd89a8da80e.png">

There are other issues though - we are not making `workflow_json` available in the API once that is resolved either: https://github.com/refinery-platform/refinery-platform/blob/8292ba065ed822e7144d7e4c24efeaf20e15361e/refinery/ui/source/js/provvis/services/provvis-init-service.js#L587

Finally, for what Chuck is seeing, the errors are the same, I think.  The [0][0] element is an empty list.  Checking for its length and not doing anything if it is 0 fixes this, but I am unsure why that first list element needs to be empty at all.  For this, I will probably need to investigate further, and I am unsure if this is even worth it, really.

**Comment by ilan-gold** [comment]
<img width="826" alt="Screen Shot 2019-10-31 at 4 04 58 PM" src="https://user-images.githubusercontent.com/43999641/67982093-649d4380-fbf8-11e9-8216-4a286d82fd43.png">
an update: i realized that the auxiliary nodes were messing with topological sorting.  by not returning them, i did not need the check.  however, that only worked for kallisto - chip-seq was still not working with this problem even when returning only non-auxiliary nodes.  chip-seq does visualize something when the check is there, but it ain't pretty:

<img width="826" alt="Screen Shot 2019-10-31 at 4 04 58 PM" src="https://user-images.githubusercontent.com/43999641/67982230-aaf2a280-fbf8-11e9-8678-4aed289e5464.png">

**Comment by ilan-gold** [comment]
after not generating any superfluous auxiliary nodes, we find that the visualization works for a chip-seq:

<img width="1466" alt="Screen Shot 2019-11-01 at 9 40 42 AM" src="https://user-images.githubusercontent.com/43999641/68028626-b3e08400-fc8b-11e9-9b6c-9c926dff0865.png">
