### ISSUE TITLE
Provvis stuck on "Loading graph": errors in console: provvis.js:5081

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2502]
* Specific code commit: 8b2625abbe58f0bd0807aec82789c10a4c1152b6
* Version of the web browser and OS: Mac FF and Chrome
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Test Prod

### Steps to reproduce

https://test.stemcellcommons.org/data_sets/09d0b5f7-56ce-40eb-889b-e0b2050f11a9/#/provvis/
Never gets past "Loading graph..."

Chrome:
```
Uncaught TypeError: Cannot read property 'values' of undefined
    at Object.h [as handleCollapseExpandNode] (provvis.js:5081)
    at provvis.js:8342
    at Array.forEach (<anonymous>)
    at Object.w [as runRender] (provvis.js:8341)
    at provvis.js:10005
    at Object.<anonymous> (d3.min.js:1)
    at Object.t (d3.min.js:1)
    at XMLHttpRequest.u (d3.min.js:1)
```

FF:
```
a.parent.children is undefined
```

**Comment by jkmarx** [comment]
@mccalluc The data set is a test one.

**Comment by mccalluc** [comment]
@jmarx: Is there something about the test data that we know would be unlike a "real" data set? Or is it a question of priorities, and unless we see it in a real dataset we shouldn't pursue it?

**Comment by jkmarx** [comment]
@mccalluc I've encountered weirdness with other test datasets in the provenance. It's also priority thing right now. If you feel strongly about this issue, we can discuss further tomorrow.
