### ISSUE TITLE
Are there any datasets where provenance > workflows > tools is useful?

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2503]
* Specific code commit: 8b2625abbe58f0bd0807aec82789c10a4c1152b6
* Version of the web browser and OS: Mac FF
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Test Prod

### Observed behavior

Bring up a dataset: go to Provenance > Workflows > Tools

Are there any datasets where
- Analysis timeline extends beyond 1970-01-01?
- Checking "Show DOI" shows anything other than "NaN"?
- Toggling between "Hard" and "Soft" "Change Layering" does anything?

**Comment by jkmarx** [comment]
@mccalluc 
1) Have you check a data set with a completed analysis. I believe this is the default setting when there's no analysis.
2) 
<img width="1186" alt="screen shot 2018-01-18 at 7 05 27 pm" src="https://user-images.githubusercontent.com/9956764/35128051-9fdc3dec-fc82-11e7-9397-00b246d42dab.png">
3) Duplicate concern: https://github.com/refinery-platform/refinery-platform/issues/2470
