### ISSUE TITLE
Dataset Details tab: "Owner's information not available"

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2505]
* Specific code commit: 8b2625abbe58f0bd0807aec82789c10a4c1152b6
* Version of the web browser and OS: Mac FF
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Test Prod

### Steps to reproduce
Under the "Details" tab, under the sharing section, except for data sets I own, I have never seen anything other than "Owner's information not available." For instance, https://test.stemcellcommons.org/data_sets/eae97d1d-8dd7-477f-8281-9ced8ffa9404/#/about/ "tutorial" is listed as being owned by Geoff on the dashboard, but that same information is not available once the file is open.

**Comment by jkmarx** [comment]
DataSet sharing api is only returning data set owner info is they are the owner or the admin
