### ISSUE TITLE
Dataset is shared with me, but I can't actually edit metadata

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2506]
* Specific code commit: 8b2625abbe58f0bd0807aec82789c10a4c1152b6
* Version of the web browser and OS: Mac FF
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Test Prod

### Steps to reproduce
Please list all the actions and the input data used:

1. Visit a dataset which has been shared with me: https://test.stemcellcommons.org/data_sets/eae97d1d-8dd7-477f-8281-9ced8ffa9404/#/about/
1. I have the Document+Pencil icon: It's shared with the "Testing" group, and I am a member of that group 
1. but, there is no option for me to edit Summary, Description, or Shortcut Name

**Comment by scottx611x** [comment]
@mccalluc I think this is the expected behavior. Only the primary DataSet owner would be able to edit such things. The modify permissions that you're seeing give you the ability to launch Analyses on the Dataset. 

This could be confusing to others though, so maybe we need a solution to clear things up

**Comment by mccalluc** [comment]
Yeah: When I hover, the pop-over says "group members can view and edit the data set", so that's what I was expecting. Fixing the messaging is probably easier than changing the behavior.

**Comment by jkmarx** [comment]
@mccalluc Not a bug. We can clarify the popover. If you can suggested text, please let me know.

**Comment by mccalluc** [comment]
Maybe "group members can view and run analyses"?
