### ISSUE TITLE
Table all blue when "uuid" is not exposed.

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2511]
* Specific code commit: 8b2625abbe58f0bd0807aec82789c10a4c1152b6
* Version of the web browser and OS: Mac FF
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Prod Test

### Steps to reproduce
Please list all the actions and the input data used:

1. Bring up the table view of a dataset
2. Click the wrench
3. Check and un-check "Expose" for "UUID"

### Observed behavior
* When unchecked, all rows have blue background, instead of alternating white and grey
(... but then, there isn't a UUID column, so I don't know what the checkmark is there for.)

![screen shot 2018-01-19 at 2 46 00 pm](https://user-images.githubusercontent.com/730388/35169033-07a0ee5e-fd29-11e7-934f-ee6d758a208f.png)
![screen shot 2018-01-19 at 2 46 19 pm](https://user-images.githubusercontent.com/730388/35169044-0edad1bc-fd29-11e7-8300-65749e867ed1.png)
![screen shot 2018-01-19 at 2 46 35 pm](https://user-images.githubusercontent.com/730388/35169054-16702792-fd29-11e7-8ba6-d7fa9704365a.png)

### Expected behavior
* Table is always alternating white and grey

**Comment by jkmarx** [comment]
Oops...UUID shouldn't be listed in the configs.
