### ISSUE TITLE
Why is analysis group centered in table?

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2512]
* Specific code commit: 8b2625abbe58f0bd0807aec82789c10a4c1152b6
* Version of the web browser and OS: Mac FF
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Test Prod

### Steps to reproduce
Please list all the actions and the input data used:

1. Look at the table for a data set.
2. Why is "Analysis Group centered? 

![screen shot 2018-01-19 at 3 04 49 pm](https://user-images.githubusercontent.com/730388/35169514-ca66b1b6-fd2a-11e7-92dd-0fa2f40c951e.png)

This seems to be the case on the handful I've checked.

**Comment by jkmarx** [comment]
No particular reason. We can change it to left-align.
