### ISSUE TITLE
If shortcut is reused, API fails, but UI does not update

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2514]
* Specific code commit: 8b2625abbe58f0bd0807aec82789c10a4c1152b6
* Version of the web browser and OS: Mac FF
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Test Prod

### Steps to reproduce
Please list all the actions and the input data used:

1. Bring up a dataset you own
2. Give it a shortcut of "asdf"
3. Bring up another dataset
4. Try to give it the same shortcut

### Observed behavior
* After hitting "Save", there is no change in the UI, though I can see in the console that the API failed with a 400.

**Comment by jkmarx** [comment]
Duplicate https://github.com/refinery-platform/refinery-platform/issues/2344
