### ISSUE TITLE
"Import into own space" should only be available for ISAtabs

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2519]
* Specific code commit: 8b2625abbe58f0bd0807aec82789c10a4c1152b6
* Version of the web browser and OS: Mac FF
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Prod Test

### Steps to reproduce
Please list all the actions and the input data used:

1. I'm on https://test.stemcellcommons.org/data_sets/7031a25c-9c2d-4e1e-b20d-443c7638bcea/#/about/, which is a CSV data set which I own.
2. There is a "Import into own space" button.

### Expected behavior

The button shouldn't be there: There is nothing in the metadata section, so this is not a ISATab, I believe.

(See also #2518)

**Comment by jkmarx** [comment]
This is an issue on the file browser.

**Comment by ilan-gold** [comment]
Using elaine-metadata.tsv (github wont let me upload :( it's on the hsci site), i got the following by logging in as an admin, uploading, changing permissions to be for public, and then logging in as guest and clicking through to it:

<img width="842" alt="Screen Shot 2019-09-18 at 8 59 11 AM" src="https://user-images.githubusercontent.com/43999641/65150823-e3487380-d9f2-11e9-85c1-ee03b8ca78d9.png">
<img width="1294" alt="Screen Shot 2019-09-18 at 8 59 15 AM" src="https://user-images.githubusercontent.com/43999641/65150824-e3487380-d9f2-11e9-9162-a9f27dc53e76.png">

**Comment by jkmarx** [comment]
Need to follow-up. This data set has a pre_isa_archive_uuid and a file_store_item.datafile, but is not an isatab. Thoughts on how to distinguish isatabs further?
