### ISSUE TITLE
File Browser: Discrepancy between Analyses and Visualization Tabs

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2528]
* Specific code commit: c8a9cb3f
* Version of the web browser and OS: Any
* Environment where the error occurred: https://test.stemcellcommons.org/

### Steps to reproduce
Please list all the actions and the input data used:

1. Navigate to the `File Browser` for a `DataSet` that you have `modify permissions` on, and launch an `Analysis` and a `Visualization`

### Observed behavior
* Notice that there is a ui indicator within the `Analyses` tab to show running `Analyses` exist while there isn't one for the `Visualizations` tab
![screen shot 2018-01-23 at 2 53 10 pm](https://user-images.githubusercontent.com/5629547/35297666-b896e174-004d-11e8-878a-f4043cd3baef.png)

### Expected behavior
* Not Sure. Maybe the `Visualizations tab` should have a similar indicator for consistency...? I could also imagine getting rid of the cog icon currently being shown in the `Analyses tab` since the `Global Analysis Popover` exists already.

**Comment by jkmarx** [comment]
Discussed in dev meeting, we do not need the vis running indicator.
