### ISSUE TITLE
Edit data sets

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#253]
Tasks:
- [x] Modify description
- [ ] Delete data set

Pivotal Tracker story 32467567 (Nils Gehlenborg - Jul 9, 2012)

**Comment by sjhosui** [comment]
Important to be able to at least edit the title because right now, all data sets imported in tab delimited format are called "untitled data set" which will be confusing for users.

**Comment by sjhosui** [comment]
Also a bug in the way "Sources" are being parsed and displayed.

**Comment by ngehlenborg** [comment]
Can you clarify that please?

**Comment by jkmarx** [comment]
Users can delete data sets via dashboard.
