### ISSUE TITLE
Remove visualization_manager Django app

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2540]
It appears to be unused, except for `igv_multi_species()` function in [core/views.py](https://github.com/refinery-platform/refinery-platform/blob/develop/refinery/core/views.py#L628)

See also #2393

**Comment by scottx611x** [comment]
@hackdna Dup of https://github.com/refinery-platform/refinery-platform/issues/2464 ?

**Comment by hackdna** [comment]
Yup, thanks. I couldn't find it because of the unusual spelling. I'll make the edits.
