### ISSUE TITLE
Better Organization for ToolPanel selection/ tool_definitions api response

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2544]
* Specific code commit: bea7f6d3995d227a4c553ef113a8ac8ff22c81ac

Currently there is no organization/ordering to the `api/v2/tool_definitions` response which is annoying, especially when the size of this list inevitably grows.

See:
![screen shot 2018-01-29 at 2 27 18 pm](https://user-images.githubusercontent.com/5629547/35529993-c11eb0da-0500-11e8-8e14-66583eac35a3.png)

I could imagine that we could either have some ordering on the backend or manipulate the response clientside 

@jkmarx thoughts?

**Comment by jkmarx** [comment]
@scottx611x Either way. If the list is going to get really long, we can add a search feature. Default would be Alphabetized??? Sorts into subgroups???

**Comment by scottx611x** [comment]
@jkmarx This came up again today, we should think about what the best approach would be.
