### ISSUE TITLE
Support for custom Tool launch names

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2545]
Back in the day, we were able to Launch Workflows with a custom name. As of now (bea7f6d3995d227a4c553ef113a8ac8ff22c81ac) this isn't the case.

I think with minimal ui and `/api/v2/tools` api tweaks this would be possible again.

### Potential Blockers:
- ~~~Legacy Analyses (Ones containing an `@` symbol in their name) [aren't currently able to be filtered in the File Browser](https://github.com/refinery-platform/refinery-platform/issues/2383). If we are to introduce this change we should fix that as well and be sure to properly validate any incoming custom names.~~~ Fixed by: https://github.com/refinery-platform/refinery-platform/pull/2733
- Allowing for custom names for `Tools` could create trouble when routing traffic to containers if we don't properly validate user input (currently we route traffic to docker containers with a url like: `/api/v2/tools/<tool_name_without_spaces>-<tool_uuid>/` which preserves uniqueness and remains a [compliant docker container name](https://github.com/moby/moby/issues/3138)). It would be better to just add a `display_name` field to the `Tool` model and store a user-defined name there.

**Comment by scottx611x** [comment]
Currently when Tools are launched its confusing in the current Tool Launch listing as to which entry corresponds to which Tool that was launched.

See: 
<img width="421" alt="screen shot 2018-05-14 at 2 36 47 pm" src="https://user-images.githubusercontent.com/5629547/40016489-7a2bbffc-5784-11e8-82ae-3a668f36278f.png">

This is mainly due to lack of custom name support

**Comment by jkmarx** [comment]
![screen shot 2018-05-18 at 8 27 16 am](https://user-images.githubusercontent.com/9956764/40234561-51225f78-5a75-11e8-859b-ba8a281a2dc8.png)
