### ISSUE TITLE
Do we need both Ontology models?

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2546]
Specific code commit: bea7f6d3995d227a4c553ef113a8ac8ff22c81ac

We currently have [`core.models.Ontology`](https://github.com/refinery-platform/refinery-platform/blob/v1.6.2/refinery/core/models.py#L2039) as well as [`data_set_manager.models.Ontology`](https://github.com/refinery-platform/refinery-platform/blob/v1.6.2/refinery/data_set_manager/models.py#L188)

It looks like they're both currently in use. We should figure out if they're trying to represent the same thing and update as necessary.

**Comment by jkmarx** [comment]
Removed https://github.com/refinery-platform/refinery-platform/pull/3330/files#diff-10b1a3c979459ad2810c191d2321daa3L1967
