### ISSUE TITLE
more detailed progress indicator (for power users?)

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#255]
show which "steps" (files) have finished

Pivotal Tracker story 46117463 (Nils Gehlenborg - Mar 13, 2013)

**Comment by jkmarx** [comment]
@ngehlenborg @hackdna Is this issue still relevant?

**Comment by hackdna** [comment]
I vote to close since we have not had any requests for this feature from users.

**Comment by jkmarx** [comment]
See above.
