### ISSUE TITLE
Clarify end-to-end story for heatmap-scatterplots

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2550]
I wanted to clarify the end-to-end user story, from experimental data coming in to Refinery, to starting a heatmap-scatterplot (and other visualizations down the line). Right now there's a little confusion about how to relate the columns of the CSV to the metadata.

@ngehlenborg : Can you say which of these is best? (I started with 4, but now think 1 is most likely to work. Or maybe 3.)

## scheme 1: vis input is multiple two-column CSVs.

Instead of taking a single CSV as input, there are multiple CSVs, each with just two columns: IDs and values. The machinery to merge these is already in place, and since Refinery metadata is file-based, we'll be able to connect the two.

## scheme 2: vis input is one multi-column CSV, metadata from refinery

Right now, metadata is per-file, and there's no necessary relationship between the columns of the csv and the metadata that Refinery knows about. Both would need to change... perhaps there's a preparatory workflow that would need to be run?

## scheme 3: vis input is one multi-column CSV, metadata from separate file

This was the impression I got at the meeting with core... but it's not Refinery-ish: The metadata should be refinery-metadata, not simply another data file. On the other hand, the route forward here is more clear than it is for other scenarios.

## scheme 4: vis input is one multi-column CSV, metadata from headers

I think this is where I was initially heading, but it doesn't match the data core currently provides, and it might make parsing harder. (ie, How do I know when I'm past the metadata rows/columns?)

**Comment by ngehlenborg** [comment]
Please put this on the agenda for the next team meeting. This is complicated!

**Comment by mccalluc** [comment]
Ok: we'll take two tracks in parallel:
- For the heatmap-vis, assume a stand-alone metadata file
- Also, research the more general problem:
  - Talk with Geoff and folks in Core to assemble a corpus of example inputs
  - Review the existing literature

In the end, the process might be something like:
- Identify the things to be joined
- Articulate the rules / algorithm to join them, and if user input is required, sort that out
- For each data set, these rules should be saved so they don't need to be re-articulated each time.

Started google doc.

@ngehlenborg : One thought is that this problem seems structurally analogous to the gene-ID mapping problem... but in the details it very different so it probably doesn't make sense to try to apply the same solutions to both, but I could be wrong? (10s vs 10Ks of entries / local vs global IDs / etc.)
