### ISSUE TITLE
Visualization Tab - loading bug

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#2552]
* Specific code commit: e859c8eb301a7aeb95222d36629e354d1bc4bb45
* Version of the web browser and OS: Safari
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): 
Beta site

### Steps to reproduce
Please list all the actions and the input data used:

1. Don't login
2. Navigate to a public data set which has visualizations, view the visualization tab.

### Observed behavior
Spinner keeps spinning

### Expected behavior
For it to time out with something informative or show visualizations.

**Comment by scottx611x** [comment]
Extra info:
We get a 403 back from the GET to `/api/v2/tools/?data_set_uuid=xxx-xxx-xxx-xxx&tool_type=visualization`

`{"detail":"Authentication credentials were not provided."}`

[This response is coming back from DRF](http://www.django-rest-framework.org/tutorial/4-authentication-and-permissions/#authenticating-with-the-api) and is not something I'm explicitly handling. I think there another question here regarding if we want Anonymous users to be able to view Visualizations on Public Datasets.

**Comment by jkmarx** [comment]
@scottx611x Yes, anonymous users can view Analyses & Visualizations on Public Datasets....w/ read_meta.

**Comment by jkmarx** [comment]
- [ ] Time out UI
- [ ] Update API
