### ISSUE TITLE
Non-idempotent test: `core.tests.test_get_analysis_list`

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2576]
* Specific code commit: 37306a03ffc7bf92233578a8c7cf442ef2bb514c
* Environment where the error occurred: Travis CI

### Steps to reproduce
See Travis Build here: https://travis-ci.org/refinery-platform/refinery-platform/builds/339035545#L5357-L5363

### Observed behavior
`test_get_analysis_list` has failed on one of my two builds
```
======================================================================
FAIL: test_get_analysis_list (core.tests.AnalysisResourceTest)
Test retrieving a list of Analysis instances that belong to a user
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/refinery-platform/refinery-platform/refinery/core/tests.py", line 222, in test_get_analysis_list
    self.assertEqual(data[0]['name'], analysis2.name)
AssertionError: u'a1' != 'a2'
----------------------------------------------------------------------
Ran 476 tests in 327.358s
FAILED (failures=1)
```
### Expected behavior
* For the test to be written in such a way that it passes every time its run

**Comment by scottx611x** [comment]
Related to: https://github.com/refinery-platform/refinery-platform/issues/2304

**Comment by hackdna** [comment]
You mean non-deterministic test? :)

**Comment by scottx611x** [comment]
@hackdna Sure. I've just observed that this test doesn't yield the same state every time that its run, hence my issue title.
