### ISSUE TITLE
add definitions to attribute values

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#258]
Tasks:
- [ ] write parser to load glossary table
- [ ] write API to serve glossary table (GET only, support bulk)
- [ ] implement in UI as tool tips

Pivotal Tracker story 40814119 (Nils Gehlenborg - Dec 6, 2012)

**Comment by jkmarx** [comment]
Closing, since we're removing the attribute definition model. #3008
