### ISSUE TITLE
Purge non-essential management commands

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2580]
* Specific code commit: https://github.com/refinery-platform/refinery-platform/commit/37306a03ffc7bf92233578a8c7cf442ef2bb514c

Currently we have a few management commands that we have found to not be needed anymore:
- @jmarx Could you add the ones you wrote down during our meeting today below?

There are also Management commands whose functionality we still need, but they would be better suited as a data migration.

 - [x] Investigate our current set of management commands

**Comment by scottx611x** [comment]
Ref #2583

**Comment by jkmarx** [comment]
@scottx611x We discussed this during the dev meeting. Were there other commands which needed to be reviewed?
