### ISSUE TITLE
add cartesian distortion to matrix view

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#260]
http://bost.ocks.org/mike/fisheye/

Pivotal Tracker story 41187699 (Nils Gehlenborg - Dec 13, 2012)

**Comment by jkmarx** [comment]
@ngehlenborg Is this feature still in the roadmap?

**Comment by ngehlenborg** [comment]
Eventually we should add this, but there is no rush.

**Comment by jkmarx** [comment]
Closing this issue for now, since matrix view is not integrated in the current file browser. We can reopen post integration.
