### ISSUE TITLE
Add VPC to Terraform infrastructure

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2600]
Avoid deploying into the default VPC

https://aws.amazon.com/answers/networking/aws-single-vpc-design/
http://harish11g.blogspot.com/2014/01/Amazon-Virtual-Private-Cloud-VPC-best-practices-tips-for-architecture-migration.html
https://charity.wtf/2016/03/23/aws-networking-environments-and-you/

Examples:
https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Scenario2.html
https://040code.github.io/2017/06/18/terraform-aws-vpc/
https://hackernoon.com/manage-aws-vpc-as-infrastructure-as-code-with-terraform-55f2bdb3de2a
https://nickcharlton.net/posts/terraform-aws-vpc.html

**Comment by mccalluc** [comment]
@hackdna:
- The article mostly made sense, but I wasn't sure what was meant by this line:
> We are past the point where you should default to using Terraform or CloudFormation for the bones of your infrastructure, for the things that rarely change. 
- Is #2597 moving in a direction that would satisfy this issue, or do you want something else?

**Comment by hackdna** [comment]
* I don't think that particular statement applies to Refinery.
* Yes.

**Comment by mccalluc** [comment]
@hackdna : Would it be ok to put this off until the main Refinery EC2 is being built by terraform? I think my problem right now is that there are two VPCs, the one I create, and the default, and that confuses things.

Or do you see a different approach?
