### ISSUE TITLE
RemovedInDjango19Warning for Tastypie

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2618]
* Specific code commit: ae273b9
* Version of the web browser and OS: N/A
* Environment where the error occurred: Vagrant

### Steps to reproduce
```bash
(refinery-platform)vagrant@refinery:/vagrant/refinery$ ./manage.py test data_set_manager
```

### Observed behavior
```
2018-02-22 18:37:21 WARNING  py.warnings:9 <module>() - /home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/tastypie/fields.py:7: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils import importlib
```

### Expected behavior
No warning

### Notes
Likely requires removal of Tastypie

#### Remove the following API/Resources -> Add DRF APIs for those which require it and add unit tests
data_set_manager
- [x] Attribute Resource
- [x] Node Resource
- [x] Investigation Resource
- [x] Protocol Resource
- [x] Protocol Reference Resource
- [x] Protocol Reference Parameter Resource
- [x] Publication Resource
- [x] Study Resource
- [x] Assay Resource

core
- [x] Sharable Resource API (base class)
- [x] User Resource
- [x] User Profile Resource
- [x] Data Set Resource
- [x] Workflow Resource
- [x] Analysis Resource
- [x] Group Management
- [x] User Authentication
- [x] Invitation Reosurce
- [x] Extended Group Resource

docs
- [ ] Update, https://github.com/refinery-platform/refinery-platform/wiki/API

**Comment by jkmarx** [comment]
Resolved by #3318
