### ISSUE TITLE
Upgrade to Python 3.x

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2619]
Required for #2918 

evaluate existing codebase for Python 3 compatibility:

* 3rd party modules (Run Python 3 travis builds)
* unicode string handling
* print statements
* urlparse -> urllib.parse (https://pymotw.com/3/urllib.parse/)

create a plan to make it compatible along with developing guidelines for writing new code

Tools:

* Six (https://pythonhosted.org/six/)
* Automated Python 2 to 3 code translation (https://docs.python.org/2/library/2to3.html)
* PyCharm can highlight problematic code (https://superuser.com/questions/920962/pycharm-turn-on-python-3-code-checking-in-a-python-2-project)

Reference:

* Two Scoops book, appendix F
* https://docs.python.org/3/howto/pyporting.html
* https://docs.djangoproject.com/en/1.8/topics/python3/
* http://python-future.org/compatible_idioms.html
* http://www.diveintopython3.net/porting-code-to-python-3-with-2to3.html
* https://medium.com/@anthonypjshaw/oh-no-this-package-is-python-2-only-8e6316f9a02
* https://blogs.dropbox.com/tech/2019/02/incrementally-migrating-over-one-million-lines-of-code-from-python-2-to-python-3/

Unicode string handling (http://python-future.org/unicode_literals.html); for example:

`updated_dict[curr_id]['uuid'] = unicode(str(uuid.uuid4()))`
or
`from django.utils.encoding import python_2_unicode_compatible`

3rd party modules:

* virtualenvwrapper depends on python 2.7 but can be used to create python 3 envs
* evaluate pyenv

Proposed Plan:

- [x] Update broken/missing Python code ahead of time 

Two phases (each roughly corresponding to a separate branch/merge):
**Python2 In-Place Updates**
- [x] Remove django-smtp-ssl
- [x] Remove djangular (#3452)
- [x] Replace librabbitmq with py-amqp

**Python3 Update**
- [ ] Syntax 

- dict iteration
- `unicode` -> `str`
- `raw_input` -> `input`
- `urlparse` -> `urllib`
- `urllib2` -> `urllib`
- getting rid of `from __future__ import unicode_literals`
- assertItemsEqual -> assertCountEqual (https://hg.python.org/cpython/rev/d9921cb6e3cd)
- content in responses needs to be cast to `str` where appropriate https://docs.djangoproject.com/en/1.8/ref/request-response/#django.http.HttpResponse.content
- comparison (https://portingguide.readthedocs.io/en/latest/comparisons.html, i.e https://github.com/refinery-platform/refinery-platform/blob/ilan-gold/python3-update/refinery/analysis_manager/tests.py#L405 returns an error without .save() because None is not comparable to integer in python3)
- remove .message references when handling exceptions https://www.python.org/dev/peps/pep-0352/#transition-plan
- StandardError -> Exception (https://portingguide.readthedocs.io/en/latest/exceptions.html#the-removed-standarderror)
- file reading for binary files needs to have 'b' flag for non-text (https://docs.python.org/2/howto/pyporting.html#text-versus-binary-data)
- rU is deprecated as a read option https://docs.python.org/3.5/library/functions.html#open
- traceback library has changed its API https://docs.python.org/3.7/library/traceback.html
- ordering of non-obviously orderable objects is disabled via TypeError https://stackoverflow.com/questions/47802245/why-is-ordereddict-not-implementing-comparison-operators
- urllib context response object's info()  method no longer returns a Message object (which has been deprecated) and thus has no getheader() method - need to use get() instead: https://docs.python.org/2/library/rfc822.html#rfc822.Message.getheader
- [ ] mockcache update to master branch (#3451)
- [ ] pysam update
- write a pysam test
- [ ] django-chunked-upload update
- [ ] upgrade python-memcached

**Comment by jkmarx** [comment]
https://pypi.org/project/pylint/

**Comment by jkmarx** [comment]
caniusepython3 https://pypi.org/project/caniusepython3/#description

Output:
You need 4 projects to transition to Python 3.
Of those 4 projects, 4 have no direct dependencies blocking their transition:
  django-chunked-upload 1.1.0
  djangular  0.3.0b1
  mockcache 1.0.2
  pysam 0.9.1.4

- [ ] Check which versions are compatible

**Comment by ilan-gold** [comment]
![python_transition(6)](https://user-images.githubusercontent.com/43999641/64983183-ed049680-d88d-11e9-9a0e-e49729c2e65d.png)
