### ISSUE TITLE
update TDF generation in SPP workflow 

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#264]
The "tile" command in IGVtools 2.2 has been deprecated and is now called "toTDF": https://raw.github.com/broadinstitute/IGV/master/docs/igvtools_readme.txt
Tasks:
- [ ] update IGVtools to 2.2
- [ ] change SPP workflow

Pivotal Tracker story 41708567 (Nils Gehlenborg - Dec 27, 2012)

**Comment by jkmarx** [comment]
Moved to web based IGV only.

**Comment by hackdna** [comment]
We can keep this closed since we no longer use SPP but for future reference, [igvtools](https://software.broadinstitute.org/software/igv/igvtools) is not the same as [IGV](http://software.broadinstitute.org/software/igv/).
