### ISSUE TITLE
No DELETE request to Galaxy library API in successful analyses

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2641]
* Specific code commit: 6972de6
* Version of the web browser and OS: Chrome 64 on OS X 10.12.6
* Environment where the error occurred: AWS

### Steps to reproduce
Run a ChIP-seq analysis

### Observed behavior
Analysis completes successfully but there is no DELETE request to the Galaxy library API. Galaxy UI shows the library marked as deleted but not purged. Galaxy main.log shows:
```
172.31.58.155 - - [01/Mar/2018:16:08:51 +0000] "DELETE /api/histories/a5e7909db9879e3a?key=<redacted> HTTP/1.0" 200 - "-" "python-requests/2.7.0 CPython/2.7.6 Linux/3.13.0-48-generic"
```

### Expected behavior
DELETE request issued to Galaxy library API

**Comment by scottx611x** [comment]
Is this a limitation of `bioblend`? 
We are utilizing their [`delete_library`](https://github.com/refinery-platform/refinery-platform/blob/master/refinery/core/models.py#L1322) code, and its being called, but it doesn't have a kwarg to `purge` like `delete_history` does.

**Comment by hackdna** [comment]
How do you know that it is actually called? Lack of DELETE request to library API is suspicious and is worth investigating. It was certainly happening before:
```
172.31.10.66 - - [31/Jan/2018:17:36:43 +0000] "DELETE /api/libraries/72ad249754f05d26?key=<redacted> HTTP/1.0" 200 - "-" "python-requests/2.7.0 CPython/2.7.6 Linux/3.13.0-48-generic"
```

**Comment by scottx611x** [comment]
I think it would be weird for Python to skip the line referenced, and proceed to delete the history on the next line. Was there any error in Refinery logs/Galaxy logs? Maybe from [here](https://github.com/refinery-platform/refinery-platform/blob/develop/refinery/galaxy_connector/models.py#L74)

**Comment by hackdna** [comment]
Closing since does not reproduce (using 81c58782):
```
192.168.50.50 - - [26/Apr/2018:15:30:45 -0400] "DELETE /api/libraries/24d84bcf64116fe7?key=<redacted> HTTP/1.1" 200 - "-" "python-requests/2.7.0 CPython/2.7.6 Linux/3.13.0-125-generic"
192.168.50.50 - - [26/Apr/2018:15:30:45 -0400] "DELETE /api/histories/ab124a85aef33434?key=<redacted> HTTP/1.1" 200 - "-" "python-requests/2.7.0 CPython/2.7.6 Linux/3.13.0-125-generic"
192.168.50.50 - - [26/Apr/2018:15:30:45 -0400] "DELETE /api/histories/33c1d4ca9f8bc33c?key=<redacted> HTTP/1.1" 200 - "-" "python-requests/2.7.0 CPython/2.7.6 Linux/3.13.0-125-generic"
```
