### ISSUE TITLE
Articulate Terraform architecture plans

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2647]
Finished a quick read of [*Terraform: Up and Running*](http://proquest.safaribooksonline.com.ezp-prod1.hul.harvard.edu/book/operating-systems-and-server-administration/virtualization/9781491977071): Besides simply getting the rest of our setup into Terraform, we need to think a little about how we use Terraform. None of these are dogma.

- [ ] Split it up: I think at the very least we might want at least three distinct sets of infrastructure:
  - S3 and other long-lived resources
  - production stack
  - staging stack... with both stacks referencing the same modules, and filling in different values for the parameters at a higher level. (Specifying variables though the CLI should be avoided.)
- [ ] State should be kept in S3, unless we are always building from the ground up. No information that matters should be on just one developer's machine.
- [ ] Separate repo: There could be a separate terraform repo, which refers to tagged versions of the main Refinery code
- [ ] If it has its own repo, we could have automated tests of deployment, going so far as to have Travis launch a stack with encrypted credntials.

also, less systematic

- I use a couple heredocs for user data: If these got bigger, the files should stand on their own, but my sense is that this kind of server set up will be done by puppet, so not worrying about the style here.
- The author is against the nested style for security groups. To me, I think the nesting makes the relationships more clear, but if it needs to be more parametric, that can change.

-----

I think the deliverable for this issue is to decide on our direction for each of these, and then close it and open new fine grained issues.

**Comment by hackdna** [comment]
* Infrastructure is already split up into modules (s3, cognito, etc). Dev/stage/prod separation is accomplished using workspaces.
* State is already stored in S3.
* Separate repo plus versioning will be useful after switch from CloudFormation is complete.
* Automated testing could be useful but is also non-trivial, so should probably be left as a nice to have.
* Yes to storing scripts in separate files.
* Not sure about nested SGs.
