### ISSUE TITLE
modify workflow definitions to include file type in input names

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#266]
Pivotal Tracker story 62716512 (Nils Gehlenborg - Dec 18, 2013)

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;lBRtRHS2&#x2F;2-266"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #266</a>

**Comment by scottx611x** [comment]
@ngehlenborg I believe this is addressed by the Intoduction of `ToolDefinitions`?

**Comment by scottx611x** [comment]
`ToolDefinitions` now have `FileType` information for their inputs.
