### ISSUE TITLE
Remove copy_dataset() task

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2662]
It [appears to be unused](https://github.com/refinery-platform/refinery-platform/search?utf8=%E2%9C%93&q=copy_dataset&type=). Also, remove all related items that are unused only in `copy_dataset()` (e.g., `copy_object()`, `copy_file()`, etc).

**Comment by jkmarx** [comment]
Resolved https://github.com/refinery-platform/refinery-platform/commit/cbf25b3e914628ef8f8c01035e2063cef8fd7aae
