### ISSUE TITLE
FileStoreItem pointing to tabular metadata file has incorrect source

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2669]
* Specific code commit: 4e4c04b
* Version of the web browser and OS: N/A
* Environment where the error occurred: any

### Steps to reproduce
Import a [data set](http://data.cloud.refinery-platform.org.s3.amazonaws.com/data/sample-data/human-chipseq/hg19-metadata-local.txt)

### Observed behavior
* Four FileStoreItem instances are created that correspond to the four files in the data set
* An additional FileStoreItem instance created with the field `source` set to `blob`

### Expected behavior
Only four FileStoreItem instances created that correspond to the four files in the data set

### Notes
See also #2547

**Comment by scottx611x** [comment]
So this `blob` corresponds to the tabular metadata file used to create a DataSet. We actually want this file to be available.
