### ISSUE TITLE
Start using Modernizr

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#267]
To replace IE detection code in base.html template.

Pivotal Tracker story 62423736 (Ilya Sytchev - Dec 12, 2013)

**Comment by ngehlenborg** [comment]
Is modernizr still an active project?

**Comment by hackdna** [comment]
Looks like it: https://github.com/Modernizr/Modernizr/releases

**Comment by jkmarx** [comment]
@hackdna This isn't a priority for the foreseeable future. I'm closing this issue for now, and we can revisit once we decide to be more open ended with our browser support. If you feel strongly otherwise, please reopen.
