### ISSUE TITLE
Unnecessary FileStoreItem instances created during analysis

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2670]
* Specific code commit: 4e4c04b
* Version of the web browser and OS: N/A
* Environment where the error occurred: any

### Steps to reproduce
1. Import a [data set](http://data.cloud.refinery-platform.org.s3.amazonaws.com/data/sample-data/human-chipseq/hg19-metadata-s3.txt)
1. Run a ChIP-seq analysis on a pair of samples

### Observed behavior
* Analysis completes successfully
* A total of five FileStoreItem instances are created:
 * three for returned results
 * two with no fields assigned except for `import_task_id`

### Expected behavior
A total of three FileStoreItem instances are created that correspond to the three returned analysis results

### Notes
See also #2669

**Comment by scottx611x** [comment]
Is this a dupe of: https://github.com/refinery-platform/refinery-platform/issues/2547?

**Comment by hackdna** [comment]
Yes, thanks. I'll close this and update the original issue.
