### ISSUE TITLE
Change annotation of workflows with single input.

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#268]
If a single input workflow is annotated properly as {"refinery_type": "analysis"}), it is still imported as having:

input_relationships: [
{
category: "1-1",
resource_uri: "/api/v1/workflowrelationships/123/",
set1: "Input Dataset",
set2: null
}
],

Pivotal Tracker story 62351270 (Ilya Sytchev - Dec 11, 2013)

**Comment by ngehlenborg** [comment]
Addressed in PR #2024.
