### ISSUE TITLE
After completion of tutorial, checkbox does not appear until page is re-loaded

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2696]
* Specific code commit: 07fa2fc90223e14336c5547c4d8238ec03fd648b
* Version of the web browser and OS: Mac FF
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): test prod

### Steps to reproduce
Please list all the actions and the input data used:

1. Run through one of the three tutorials under the help menu
2. Click on the menu again

### Observed behavior
* The box for the tutorial will not be checked.
* Reload the page, and check the menu again: now it's checked.

### Expected behavior
* Reload should not be necessary

**Comment by jkmarx** [comment]
Duplicate https://github.com/refinery-platform/refinery-platform/issues/1899

**Comment by scottx611x** [comment]
I was thinking: dupes of #1417, #2486
