### ISSUE TITLE
Text in third tutorial is centered

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2697]
* Specific code commit: 07fa2fc90223e14336c5547c4d8238ec03fd648b
* Version of the web browser and OS: Mac FF
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): test prod

### Steps to reproduce
Please list all the actions and the input data used:

1. Start the third tutorial of the three: "Start Collaboration tutorial"

### Observed behavior
* In every pop-over of this tutorial, but not in the preceding two, the text is centered
<img width="233" alt="screen shot 2018-03-23 at 11 20 54 am" src="https://user-images.githubusercontent.com/730388/37837824-aa56fc44-2e8c-11e8-8d17-b13feac9e0b0.png">

### Expected behavior
* left justified

**Comment by jkmarx** [comment]
![screen shot 2018-07-26 at 7 42 48 am](https://user-images.githubusercontent.com/9956764/43260464-8eddaab2-90a7-11e8-958a-aa80ee556d47.png)
![screen shot 2018-07-26 at 7 42 53 am](https://user-images.githubusercontent.com/9956764/43260465-8ee8ec60-90a7-11e8-9740-5e315a90bedc.png)
![screen shot 2018-07-26 at 7 42 57 am](https://user-images.githubusercontent.com/9956764/43260466-8ef4a1fe-90a7-11e8-9990-b458e0b4b5bc.png)
![screen shot 2018-07-26 at 7 43 00 am](https://user-images.githubusercontent.com/9956764/43260467-8f05c16e-90a7-11e8-8a9e-58239955d8f3.png)

All the text are centered now.
