### ISSUE TITLE
Add content-disposition to cross-dataset file browser downloads.

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2699]
* Specific code commit: 07fa2fc90223e14336c5547c4d8238ec03fd648b
* Version of the web browser and OS: Mac FF
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): prod test

### Steps to reproduce
Please list all the actions and the input data used:

1. In the cross-datasets browser, download a file by clicking the icon in the left-most column

### Observed behavior
The file loads in a new column

### Expected behavior
You get a prompt to download a file or open it with the appropriate application

(Compare to #2130: same issue, for workflows.)

**Comment by jkmarx** [comment]
@mccalluc "The file loads in a new ?tab"  Also duplicate of sorts -> https://github.com/refinery-platform/refinery-platform/issues/1350

**Comment by mccalluc** [comment]
Sorry not to see that one. closing.
