### ISSUE TITLE
Inability to Filter DataSets by Group in Firefox-Linux

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2701]
* Specific code commit: 8434c17
* Version of the web browser and OS: `Firefox 57.0.4 Ubuntu 16.04 LTS`
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): https://test.stemcellcommons.org

### Steps to reproduce
Please list all the actions and the input data used:

1. On the Dashboard, attempt to filter the `DataSet` listing by a `Group`

### Observed behavior
* Group selection disappears upon mouse hover **in Firefox**: ![can t-filter](https://user-images.githubusercontent.com/5629547/37926764-332c8798-3106-11e8-8051-1cc0cdb53529.gif)

### Expected behavior
* This behavior doesn't exist **in Chrome**: 
![can-filter](https://user-images.githubusercontent.com/5629547/37926845-719f5dfc-3106-11e8-8cdd-e29929ab88cd.gif)

**Comment by scottx611x** [comment]
Confirmed that this issue doesn't exist in `Firefox 59.0.1 macOS 10.12.6`

**Comment by jkmarx** [comment]
Latest firefox 61.0.1, we can filter by groups. 
![fixed-bug](https://user-images.githubusercontent.com/9956764/42855204-67444a6a-8a0d-11e8-87a8-3dbbc45cff3a.gif)
