### ISSUE TITLE
Index Files Not Being Generated for Newly Imported BAM Files

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2705]
* Specific code commit: 8434c17e95d854cbe4d3d4784fb2a8296adec79b
* Version of the web browser and OS: Any
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): https://test.stemcellcommons.org

### Steps to reproduce
Please list all the actions and the input data used:

1. Run a workflow that produces a `.bam` file as output
2. Launch IGV with said `bam` as input

### Observed behavior
* When zoomed in to the base-pair level there is a 404 when IGV tries to access the `.bai` file
![screen shot 2018-03-28 at 1 28 19 pm](https://user-images.githubusercontent.com/5629547/38045962-56ddffe6-328c-11e8-9c86-0fa07a818775.png)
```
Request URL: https://test.stemcellcommons.org/media/file_store/dd/6a/TopHat%20on%20data%203%3A%20accepted_hits_PWv0H1h.bam.bai
Request Method: GET
Status Code: 404 Not Found
Remote Address: 52.21.193.165:443
Referrer Policy: no-referrer-when-downgrade
```

### Expected behavior
* For said `.bai` to be available, and to be able to zoom in all the way in IGV

### Thoughts: 
- Since IGV is now a [self contained entity](https://github.com/refinery-platform/docker_igv_js), would it make sense to create these index files on docker container startup instead of from Refinery's back-end or would other VisualizationTools need this information?

Related to: #2210 &  #1378

**Comment by hackdna** [comment]
What do server logs say?

**Comment by scottx611x** [comment]
Repeatedly: `Something went wrong while trying to generate the auxiliary file for /data/media/file_store/xx/xx/xxxx. 'FileExtension' object has no attribute 'lower'`

Seems to be a side effect of the [`get_file_extension` changes](https://github.com/refinery-platform/refinery-platform/pull/2634/files#diff-6a2a2dc898d97897f0c0f69df20d7e3cL282) from #2634
