### ISSUE TITLE
Upgrade PostgreSQL to version 10

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2707]
* Currently used [version 9.3 will reach EOL in September 2018](https://www.postgresql.org/support/versioning/)
* [Amazon RDS for PostgreSQL now supports PostgreSQL major version 10](https://aws.amazon.com/about-aws/whats-new/2018/02/postgresql-10-now-supported-in-amazon-rds/)
* Version 10 is the new default when installing PostgreSQL using Homebrew in OS X
* A dump/reload of the database or use of the pg_upgrade module is required for major upgrades
* May require [upgrade to Ubuntu 18.04 LTS](https://github.com/refinery-platform/refinery-platform/issues/2616)
* Currently used version of PostgreSQL Puppet module (4.9.0) [works with PostgreSQL versions through 9.5 only](https://forge.puppet.com/puppetlabs/postgresql/4.9.0/readme#limitations), so will probably require an upgrade.
* [Upgrading the PostgreSQL DB Engine](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html)

Notice from AWS in July 2018:

This notification is being sent to you to as a reminder that Amazon RDS will be discontinuing support for version 9.3 of the PostgreSQL database in RDS, starting on September 5th, 2018. 

Amazon RDS has been supporting the PostgreSQL major version 9.3 since 2013. That release has since been replaced by subsequent major versions that contain significant improvements in functionality, security, reliability and performance. The PostgreSQL community has announced the end of life date for PostgreSQL 9.3 as September 2018 [1].  Aligning with the community support model, AWS will be ending support for the PostgreSQL major version 9.3 in Amazon RDS, including its minor engine versions including 9.3.10, 9.3.12, 9.3.14, 9.3.16, 9.3.17, 9.3.19, 9.3.20, and 9.3.22. We will continue to support 9.4 and more recent versions of the PostgreSQL database on Amazon RDS.

We recommend that you upgrade your Amazon RDS PostgreSQL database instances to either version 9.6 or version 10 at your earliest convenience. You can use the Major Version Upgrade feature of RDS to upgrade databases to the next higher version. You can initiate an upgrade by going to the Modify DB Instance page in the AWS Management Console and changing the database version setting to a newer major version of PostgreSQL. If you choose the "Apply Immediately" option, the upgrade will be initiated immediately after exiting the Modify page. If you choose not to apply the change immediately, the upgrade will be performed during your subsequent maintenance window.  To learn more about upgrading PostgreSQL major versions in RDS, review the Upgrading Database Versions page [2].

As part of the retirement plan for Amazon RDS PostgreSQL 9.3, starting the week of August 6th 2018, you will no longer be able to create any new PostgreSQL 9.3 instances using the AWS console. **In November 2018, your remaining 9.3 instances will be force upgraded to the most recent minor version of PostgreSQL 9.4. Once this occurs, any instance restored from a snapshot of a deprecated version will automatically and immediately be upgraded to a currently supported version.** The exact dates and details on force upgrades will be communicated in September 2018.

**Comment by jkmarx** [comment]
Note: Need to upgrade to a higher version, at least 9.6 (recommended by AWS).

**Comment by jkmarx** [comment]
Started to compile a doc here
https://docs.google.com/document/d/1FQBIHgVkovw5MR-L1MHmnj94dFWE9KHqjMAcws-Ykos/edit
