### ISSUE TITLE
Avoid generating BAM index file under FILE_STORE_BASE_DIR tree

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2713]
* Specific code commit: v1.6.3
* Version of the web browser and OS: N/A
* Environment where the error occurred: any

### Steps to reproduce
Run a workflow that generates a BAM file

### Observed behavior
A `.bai` file is [generated directly in the same directory as the BAM file](https://github.com/refinery-platform/refinery-platform/blob/v1.6.3/refinery/data_set_manager/tasks.py#L471)

### Expected behavior
A `.bai` file should be added using the file_store API or in a temporary directory

### Notes
This functionality will break when file_store is updated to use S3 as a storage backend
See also #2718

**Comment by scottx611x** [comment]
@hackdna I'm not going to be able to address this in `1.6.4` I'm going to move it to Next
