### ISSUE TITLE
Dashboard Results differ from Launch Pad

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#2759]
* Specific code commit: 61bd4dbffde36c7c7f816af9e6716e995c2ff414
* Version of the web browser and OS: Chrome
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Test Site

### Steps to reproduce
Please list all the actions and the input data used:

1. Dashboard, type RNA or RNA in search
2. On launch pad, type RNA or rna in search

### Observed behavior
Results don't match in the UI even though the API call results do.

### Expected behavior
* Matching results

**Comment by jkmarx** [comment]
I think it's a timing issue with multiple api calls

**Comment by scottx611x** [comment]
Closed in https://github.com/refinery-platform/refinery-platform/commit/c74927404cdb5e88a473d7b70c8fb2cd7b312abf
