### ISSUE TITLE
"Hamburger" flicker on expand / collapse

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2764]
* Specific code commit: 61bd4dbffde36c7c7f816af9e6716e995c2ff414
* Version of the web browser and OS: FF on Mac
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Testing production

### Steps to reproduce
Please list all the actions and the input data used:

1. If the window is a bit narrow, the header menu is compressed into a hamburger. There is a bit of flicker when it expands, at first being split across two lines.

<img width="679" alt="screen shot 2018-05-14 at 12 56 02 pm" src="https://user-images.githubusercontent.com/730388/40014510-c455c178-577e-11e8-892c-37f1c5dc7a52.png">

### Expected behavior
* No flicker.

**Comment by jkmarx** [comment]
Only at certain widths.

![hamburger-flicker](https://user-images.githubusercontent.com/9956764/42700977-4f73a16a-8693-11e8-8e07-dc9f635fdd23.gif)

**Comment by jkmarx** [comment]
Checks on FF and Chrome. There are other spacing issues, but the flicker is gone.

![no-flicker](https://user-images.githubusercontent.com/9956764/47853583-90070b80-ddb5-11e8-87dd-8390c86a1685.gif)
