### ISSUE TITLE
Dashboard Alpha: History panel dates out of order

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2768]
* Specific code commit: 3e7036c6f8c02c3ebe8cc119f913e3dc288724c5
* Version of the web browser and OS: `Ubuntu 16.04 LTS Chrome`
* Environment where the error occurred:  test.stemcellcommons.org

### Steps to reproduce
Please list all the actions and the input data used:

1. Launch some VisualizationTools
2. After some are automatically purged, relaunch a few again

### Observed behavior
* The history panel shows dates that are out of order:

![screen shot 2018-05-15 at 10 06 07 am](https://user-images.githubusercontent.com/5629547/40061886-f22f67e4-5827-11e8-9533-d930a34987e4.png)

### Expected behavior
* For the listing to be chronological?
* Maybe we are listing by modification date and not creation date?

**Comment by scottx611x** [comment]
The dates in the Visualizations tab are also out of order:
![screen shot 2018-05-15 at 10 13 41 am](https://user-images.githubusercontent.com/5629547/40062205-babda310-5828-11e8-86d8-e50395ad2f9a.png)

**Comment by jkmarx** [comment]
- Better solution is to let the drf serializer order it. We need to add the django-filter library. http://www.django-rest-framework.org/api-guide/filtering/#orderingfilter @scottx611x

**Comment by scottx611x** [comment]
@jkmarx Is this still an issue?
