### ISSUE TITLE
Perms Auditing: Events API

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#2779]
### Perms Auditing
- Events API

_________
from Nils: create/update/delete operations on data set/visualization/analysis (that i have *at least* read access on *unless it is through public*) and groups (that i am member of *unless it is public*)

i want to know when it happened and who did it (maybe we also want to track ip addresses if it is easy, although that will rarely be relevant for research purposes) 

I want to be able to filter these events by: user, time, operation, entity type (i.e. show me all events related to visualization, analysis, data set, group) and entity (i.e. a specific data set, visualization, analysis, or group)

for update operations it would be useful to have subclasses (data set: shared with group X, edited meta data, added external file, …, group: added users X, removed user Y, promoted user Z to manager, shared new data set, etc.)
_______________

**Comment by mccalluc** [comment]
Reviewing some of the packages that are out there:
- https://github.com/pinax/pinax-eventlog : does not support django < 1.11
- https://github.com/vvangelovski/django-audit-log : Adds extra fields to each table which is watched... harder to aggregate events across models
- https://github.com/jjkester/django-auditlog : Events get their own table... could always log manually if necessary?

(Slightly biased [comparison](https://github.com/jjkester/django-auditlog/issues/109) of the last two.)

**Comment by hackdna** [comment]
[django-simple-history](http://django-simple-history.readthedocs.io/en/latest/) appears to be the most robust implementation

**Comment by mccalluc** [comment]
[Current plan](https://docs.google.com/document/d/1lq8zBVT4mlQegqtTvOjL8UFTJ0fKe0uPIafRsLYxQI0/edit?usp=sharing)
- Simpler data model than Nils would like, but it's more likely that we'll actually get something done.
- Not using an existing library, because we want to aggregate results for a range of low-level objects, with query results based on parent: More clear if we identify the parent object at the time of the event.
- Events are polymorphic: Rather than multiply the number of fields, or precompose the message in the database, store a blob of json.

**Comment by scottx611x** [comment]
@mccalluc Not sure what should be done with this issue for now. https://github.com/refinery-platform/refinery-platform/pull/2816 added the per-user access control, but I believe theres still quite a few Events that we want logged that haven't been implemented yet. Are we to implement these extra Event creations in this current milestone?

**Comment by mccalluc** [comment]
@scottx611x: I would say keep it open until it's done-done, unless it would be useful to open new more granular issues.

**Comment by jkmarx** [comment]
@mccalluc I'd say close and open new granular issues.
