### ISSUE TITLE
Handle ConnectionError in import_workflows command.

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#278]
Refinery crashes when Galaxy is unreachable.

There is no exception handling in this section of code.

Pivotal Tracker story 55721796 (Ilya Sytchev - Aug 23, 2013)

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;mawwY6aC&#x2F;3-278"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #278</a>

**Comment by jkmarx** [comment]
Resolved by #2583
