### ISSUE TITLE
Add Tools

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#2782]
- [x] deep Tools
- [x] quali map
* @gmnelson @sjhosui @ngehlenborg Discuss scope

**Comment by sjhosui** [comment]
I’d like to invite Meeta to this discussion as she has used Deeptools extensively.

**Comment by scottx611x** [comment]
Closing as we are close to deploying these tools, and there's no refinery-platform associated code changes necessary for their introduction.
