### ISSUE TITLE
Galaxy workflow import fails when Galaxy returns HTTP 500 error.

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#280]
If a workflow is using missing tools Galaxy refuses to export it.  It reports HTTP 400 when trying to download it using the GUI and HTTP 500 when using the API.
Need to handle galaxy_connector.exceptions.ServerError.

Pivotal Tracker story 55489388 (Ilya Sytchev - Aug 20, 2013)

**Comment by scottx611x** [comment]
Related to #278

**Comment by jkmarx** [comment]
Load_tools command handles this scenario
