### ISSUE TITLE
Error in browser console on GET requests

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2832]
* Specific code commit: 3c97f2e
* Version of the web browser and OS: Chrome 67 on OS X 10.12.6
* Environment where the error occurred: Vagrant VM

### Steps to reproduce
Load the home page in a web browser

### Observed behavior
Error in browser console:
`GET blob:http://192.168.50.50:8000/42d058ae-cdda-490c-8e85-7236092d5b4a 0 ()`

### Expected behavior
No error

### Notes
* all other pages seem to affected as well
* UUID in URL changes when page is reloaded

**Comment by jkmarx** [comment]
@hackdna I believe this issue was related to how we handled routing in the previous homepage/launchpad.  If you're still seeing this issue on the current new homepage, please reopen. Closing because no longer an issue with v1.6.9 Explore/Satori removal.
