### ISSUE TITLE
Node functionality is split between core and data_set_manager

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2837]
* [Node](https://github.com/refinery-platform/refinery-platform/blob/c31b92d29a4c541c383299b96dda2e8d8dedc3d7/refinery/data_set_manager/models.py#L364) model is in `data_set_manager/models.py`
* Node API (v1 and v2) is in the core Django app:
  * [NodeResource](https://github.com/refinery-platform/refinery-platform/blob/c31b92d29a4c541c383299b96dda2e8d8dedc3d7/refinery/core/api.py#L1057) is in `core/api.py`
  * [NodeViewSet](https://github.com/refinery-platform/refinery-platform/blob/c31b92d29a4c541c383299b96dda2e8d8dedc3d7/refinery/core/views.py#L696) is in `core/views.py`
  * [NodeSerializer](https://github.com/refinery-platform/refinery-platform/blob/c31b92d29a4c541c383299b96dda2e8d8dedc3d7/refinery/core/serializers.py#L112) in `core/serializers.py`
* [NodeApiV2Tests](https://github.com/refinery-platform/refinery-platform/blob/c31b92d29a4c541c383299b96dda2e8d8dedc3d7/refinery/data_set_manager/tests.py#L1752) is in the `data_set_manager/tests.py`

This violates Django design principles and makes the code difficult to understand and maintain.

**Comment by jkmarx** [comment]
It should go in data_set_manager?  @hackdna @scottx611x

**Comment by scottx611x** [comment]
@jkmarx I would say so. It would be much tougher to move the model/migrations into `core/`

**Comment by hackdna** [comment]
Also, `core` Django app should be reduced in size and ideally, just be used for bit and pieces that don't belong to any particular app (Two Scoops 29.1).
