### ISSUE TITLE
*[8]* create video to explain Refinery

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#284]
Tasks:
- [ ] _8h_ create screencasts

Pivotal Tracker story 46999265 (Nils Gehlenborg - Mar 27, 2013)

**Comment by jkmarx** [comment]
This issue is from 2014. I'm closing for now and if the team decides to prioritize creating a new video (vs the current short one on stemcellcommons youtube channel), we can create a new issue with more details.
