### ISSUE TITLE
"Invite New Member" modal should have 2nd phase with only one button

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2883]
* Specific code commit: c5a87d6f95eb85f8350479f1a7e87f0a1aab34aa
* Version of the web browser and OS: FF Mac
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Production test

### Steps to reproduce
Please list all the actions and the input data used:

1. Log in and go to the dashboard
2. In the collaboration pane, click to send an invitation to a group where you are manager
3. Supply an email and click "Send Invite"

### Observed behavior
* After the email is sent, there's a message, but the buttons remain the same.

### Expected behavior
* After the email is sent, there should only be one button to close the modal. The way it is, sending duplicate invites is likely.
<img width="607" alt="screen shot 2018-07-18 at 9 23 51 am" src="https://user-images.githubusercontent.com/730388/42886659-1b0ccdec-8a72-11e8-9ccc-f979c7c106b7.png">

**Comment by jkmarx** [comment]
@mccalluc Design choice with user sending multiple invites when creating a new group. Perhaps we can enhance the modal and gray out the send_invite after successful sent until a new email is added.  Low priority and can be added to the collaboration enhancement issue. https://github.com/refinery-platform/refinery-platform/issues/2332
