### ISSUE TITLE
UI does not update after group delete

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2889]
* Specific code commit: 4d61e103e74af0726defef792e2556f60d2d3a99
* Version of the web browser and OS: safari and ff on mac
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Production test

### Steps to reproduce
Please list all the actions and the input data used:

1. From the collaboration page, delete a group

### Observed behavior
The list of groups does not update immediately: Instead the group remains on the list until the next interaction with the list.

**Comment by jkmarx** [comment]
Probably won't get to this issue, since the collaboration page will be removed at some point soon.
