### ISSUE TITLE
New dashboard doesn't show Analysis information in DataSet Delete modal

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2894]
* Specific code commit: 907304880e62d9dcf01008fbf9667ec3e679aaec
* Version of the web browser and OS: Any
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): `test.stemcellcommons.org`

### Steps to reproduce
1.  Navigate to the new dashboard (`/dashboard/`)
2. Click the delete icon (trash can) for a Dataset that you own that has had at least one `Analysis` run on it

### Observed behavior
* New dashboard doesn't show any info about corresponding `Analyses`
![jul-20-2018 13-06-27](https://user-images.githubusercontent.com/5629547/43015648-dfb2da86-8c1d-11e8-952e-4961b226045a.gif)

* Old dashboard shows `Analysis` information
![jul-20-2018 13-07-59](https://user-images.githubusercontent.com/5629547/43015667-f6c47e3c-8c1d-11e8-96d6-23a7a667e727.gif)

### Expected behavior
* For information about a `DataSet's` `Analyses` to be displayed in this modal

### General Notes:
* The [`/api/v1/data_sets` response](https://github.com/refinery-platform/refinery-platform/blob/master/refinery/core/api.py#L534-L555) includes analysis info which [`/api/v2/data_sets`](https://github.com/refinery-platform/refinery-platform/blob/master/refinery/core/views.py#L698) would have to mirror

**Comment by gmnelson** [comment]
Relatedly, the new dashboard does not show how many analyses have been run on a data set:

Old
![image](https://user-images.githubusercontent.com/23487494/43402365-941b7964-93e0-11e8-827a-7fdfe839b203.png)

New
![image](https://user-images.githubusercontent.com/23487494/43402453-c321fe72-93e0-11e8-8e5e-19f89b7d2413.png)

**Comment by jkmarx** [comment]
Ref: https://github.com/refinery-platform/refinery-platform/issues/3250 

The issue above was fixed 
<img width="601" alt="Screen Shot 2019-04-28 at 8 50 16 PM" src="https://user-images.githubusercontent.com/9956764/56872463-7c9ccc00-69f7-11e9-89ad-384fd19bbc0b.png">
