### ISSUE TITLE
Allow for deletion of VisualizationTools from the UI

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2897]
- Extend `/api/v2/tools` to be able to DELETE (`VisualizationTools` only, `WorkflowTools` are deleted when `Analyses` are deleted)
- Add ui component to aid in deletion
- Make sure corresponding `Events` are deleted as well?

**Comment by mccalluc** [comment]
> Make sure corresponding Events are deleted as well?

We'd actually prefer to keep more history, rather than less, I think?
