### ISSUE TITLE
Make it less likely that users invite people to the wrong group

### ISSUE THREAD

**Issue by gmnelson** [refinery-platform/refinery-platform#2906]
* Specific code commit: 30567f8
* Version of the web browser and OS: macOS
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): hsci.stemcellcommons.org

### Steps to reproduce
Please list all the actions and the input data used:

1. Click 'Invite user to group' from My Dashboard

### Observed behavior
* The current UI makes it somewhat likely that user could accidentally click the 'Invite user' icon for the wrong group
* The resulting 'Invite New Member' modal does not tell you for which group you clicked
![image](https://user-images.githubusercontent.com/23487494/43281503-dd0b1d5c-90e1-11e8-8ad6-99618809d82a.png)

### Suggested solutions
- [x]  Display the group name in the 'Invite New Member' modal (I might start with this, if it's easy to do)
- [x]  Visually separate groups in Collaboration card (horizontal lines as in Data Sets, alternate shading)
~- [ ]  Move Edit icons closer to Group names~

**Comment by jkmarx** [comment]
@gmnelson For task 3, did you mean swap the role and edit column OR should we look into a new layout?

**Comment by gmnelson** [comment]
@jkmarx For task 3, I think a more effective option might be to remove the Edit column and move the settings/invitation icons right next to the Group name (e.g. similar to the open folder icons for data sets).

That said, I'm not sure all three tasks are necessary to address this issue. You've already given users the ability to double-check their selection via task 1. Also, I've had no trouble correctly selecting member names within groups due to the horizontal lines -- if this is simple to add to the group level as well (i.e. task 2), I think we'd be in a good spot. Redesigning the layout (task 3), which I don't imagine is a quick project, is unnecessary at the moment, in my opinion.
