### ISSUE TITLE
create workflow: BAM replicate merging

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#292]
Pivotal Tracker story 46998847 (Nils Gehlenborg - Mar 27, 2013)

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;5yIwO9Dw&#x2F;193-install-galaxy-tools-for-bam-replicate-merging-workflow-on-scc-dev"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Install Galaxy tools for BAM replicate merging workflow on scc-dev</a>
