### ISSUE TITLE
Filtering down to empty set causes facet sidebar to disappear

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2958]
* Specific code commit: f6b5665211815395d5ee7246a3e3574b1692eb72
* Version of the web browser and OS: FF on MacOS
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Production Test

### Steps to reproduce
Please list all the actions and the input data used:

1. Start at https://test.stemcellcommons.org/data_sets/3165e320-c6dc-42b0-b225-87d36d6dbf85/#/files/
2. Select the "Raw Data File" facet
3. Many other facets now have a count of "0": Pick one, like "Text file" for "File Type"
4. The facet picker disappears
![screen shot 2018-08-28 at 11 38 30 am](https://user-images.githubusercontent.com/730388/44740255-f4f96900-aac7-11e8-9290-ab0d2ff7fee8.png)

### Expected behavior
The UI shouldn't disappear... maybe the zero-valued facets shouldn't have been selectable? I'm not sure.

**Comment by mccalluc** [comment]
(For comparison, the cross file browser does not show zero-valued facets... but you can still produce the same behavior there if you select one facet, and then quickly select a second whose intersection is empty before the page refreshes.)

**Comment by jkmarx** [comment]
@mccalluc I'm going to tag this issue as non-critical for this milestone. I'd expect users to not select an empty facet. It's worth looking into, especially with the filtering enhancements coming up. Would you agree?

**Comment by mccalluc** [comment]
@jkmarx : Sounds good: This isn't critical.
