### ISSUE TITLE
Missing comma in list (but maybe change it to <br>s?)

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2961]
There's a missing comma at the end of [this line](https://github.com/refinery-platform/refinery-platform/blob/2b41548cc8fed78cd73a25ae2645cd18fdfea4b5/refinery/ui/source/js/data-set-about/partials/details.html#L359):
```
    <span ng-if="assay.measurement_accession">
      Measurement Accession: {{ assay.measurement_accession }} <-- here
   </span>
```
... but maybe change it to `<br>` for readability? Not worth bike shedding.

**Comment by jkmarx** [comment]
@mccalluc I'm going to resolve this issue with just a comma now, but good point. The whole details page could use some reformatting. I'm hoping to revisit and enhance the file browser before the end of the year so I will keep this in mind.
