### ISSUE TITLE
Error importing tabular metadata file - no samples displayed

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2962]
* Specific code commit: f6b5665211815395d5ee7246a3e3574b1692eb72
* Version of the web browser and OS: MacOS FF
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Production Test

### Steps to reproduce
Please list all the actions and the input data used:

1. Uploaded this CSV, accepted default column assignments, and associate a file for each row (Does the Data File Column refer to local files? --> Yes):
```
a,b,c
1,2,3
4,5,6
```

- But Scott says non trivial files work too.
- And I had thought I saw this when data was not associated, too.
- It can be reproduced on beta: 30567f8a2b1207f2e24fab92a744c151b64f88db

### Observed behavior
Empty table, and no facets:
![screen shot 2018-08-28 at 5 21 54 pm](https://user-images.githubusercontent.com/730388/44756470-d1024b80-aaf8-11e8-97c5-be5d7f25a972.png)

In the console:
```
angular.js:14110 TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at angular.js:38
    at angular.js:30441
    at angular.js:17617
    at m.$digest (angular.js:17755)
    at m.$apply (angular.js:18021)
    at angular.js:18322
    at e (angular.js:6035)
    at angular.js:6314
(anonymous) @ angular.js:14110
3angular.js:14110 TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at angular.js:38
    at angular.js:30441
    at angular.js:17615
    at m.$digest (angular.js:17755)
    at m.$apply (angular.js:18021)
    at angular.js:18322
    at e (angular.js:6035)
    at angular.js:6314
```
Click to another tab and click back and it's there: Only a problem on initial load.

Assay/Files api returned duplicate attributes obj

**Comment by jkmarx** [comment]
Not an UI issue. Took a look at the api response and there's a duplicate attribute being returned. For some reason REFINERY_DATAFILE_s is being returned twice which is causing the circular import. Internal names should be unique and they are being used at keys.

**Comment by jkmarx** [comment]
- [ ] check if reproduced locally
- [ ] why a duplicate DATAFILE attribute is being associated (indexing issue?)

**Comment by hackdna** [comment]
I just got this behavior in Vagrant environment using [hg19-metadata-local.txt](http://data.cloud.refinery-platform.org.s3.amazonaws.com/data/sample-data/human-chipseq/hg19-metadata-local.txt) and a single uploaded data file.

**Comment by hackdna** [comment]
Still an issue in 42634ad (using [hg19-metadata-local.txt](http://data.cloud.refinery-platform.org.s3.amazonaws.com/data/sample-data/human-chipseq/hg19-metadata-local.txt) and no data files).

**Comment by jkmarx** [comment]
@scottx611x Is the error from a newly uploaded data set or a revised uploaded data set?

**Comment by scottx611x** [comment]
@jkmarx Tennen Lab was for a revised, but the original issue is for a fresh upload. I think they're closely related.

**Comment by gmnelson** [comment]
@jkmarx have not seen this recently
