### ISSUE TITLE
CPU utilization continuously high

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2965]
* Specific code commit: v1.6.5
* Version of the web browser and OS: N/A
* Environment where the error occurred: AWS

### Steps to reproduce
Unknown

### Observed behavior
CPU utilization of beta.stemcellcommons.org stayed above 30% continuously over the past two weeks.

![screen shot 2018-08-29 at 10 44 38](https://user-images.githubusercontent.com/452575/44796222-8cb78f80-ab7a-11e8-8366-e8e27e9e6411.png)
![screen shot 2018-08-29 at 10 45 06](https://user-images.githubusercontent.com/452575/44796240-93de9d80-ab7a-11e8-808b-ddbd883d08b0.png)

### Expected behavior
CPU utilization should be close to zero when the site is idle.

Ref: #2789

**Comment by hackdna** [comment]
Still an issue in v1.6.6.

**Comment by hackdna** [comment]
RDS CPU utilization is also high.

scc-prod running v1.6.6 (~10%):
![screen shot 2018-11-14 at 10 34 07](https://user-images.githubusercontent.com/452575/48493167-5ee8fb00-e7f9-11e8-8c41-dae611a00629.png)
vs rds-refinery-of963ie running an earlier version (~1.75%):
![screen shot 2018-11-14 at 10 36 32](https://user-images.githubusercontent.com/452575/48493215-6f997100-e7f9-11e8-931c-16bb6d915356.png)

**Comment by hackdna** [comment]
The baseline CPU utilization has now climbed to over 50% on the production SCC instance.

![screen shot 2019-01-16 at 10 38 21](https://user-images.githubusercontent.com/452575/51259901-14136d00-197b-11e9-8ce3-18b3fa1cdcd0.png)
![screen shot 2019-01-16 at 10 38 45](https://user-images.githubusercontent.com/452575/51259902-14136d00-197b-11e9-832e-d313f3e1467a.png)

**Comment by ngehlenborg** [comment]
CPU utilization is hovering around 5% as of today. Can we close this?

**Comment by ngehlenborg** [comment]
Let’s close and create a new issue to set up a CloudWatch monitor.



On Oct 28, 2019, at 11:54 AM, Ilya Sytchev <notifications@github.com> wrote:

﻿

OK but before closing it would be great to set up some CloudWatch alerts to keep an eye on this.

**Comment by ilan-gold** [comment]
I'll set this up in Terraform for deployments going forward and for the current production instance as well
