### ISSUE TITLE
FF only: Unable to add files during upload

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2987]
* Specific code commit: 2a63aec2f77e0fed74b7a61787b0166904214b58
* Version of the web browser and OS: FF on Mac (Chrome works fine)
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance):  production

### Steps to reproduce
Please list all the actions and the input data used:

1. Upload this csv (surprised if it matters?)
```
identifier,file,code
Myotube,Myotube.genes,human
Th-cell,Th-cell.genes,human
mESC,mESC.genes,human
pro-B,pro-B.genes,human
```
2. Defaults for all the column assignments
3. Click "Yes" for local files, and then flick "Add files"

### Observed behavior
Nothing happens: I don't see any JS errors, or any requests being sent to the server.

**Comment by jkmarx** [comment]
@mccalluc Can you please add the FF version?

**Comment by jkmarx** [comment]
Ref #3185
