### ISSUE TITLE
*[8]* select assay (via study) to view in sample selection interface

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#299]
Tasks:
- [x] 4h need data set API to query for studies and assays in a data set
- [ ] 4h UI to make selection on sample selection page

Pivotal Tracker story 46989329 (Nils Gehlenborg - Mar 27, 2013)

**Comment by jkmarx** [comment]
Drop down menu in files tab showing studies and assay. #895

**Comment by jkmarx** [comment]
Ref #1001 Duplicate issue
