### ISSUE TITLE
Can't change permissions on dataset

### ISSUE THREAD

**Issue by jnhutchinson** [refinery-platform/refinery-platform#3016]
* Specific code commit: v1.6.6
* Version of the web browser and OS: Firefox 62.0.2, OSX 10.13.6
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): AWS 

### Steps to reproduce
1. Select data set that you have uploaded "Vaidya - Uretereal obstruction effect on kidney in Smoc2 knockout mice RNA-seq"
1. Click "Share"
1. Select "Modify" radio button for "Core-Refinery collaboration"
1. Click "Save"

### Observed behavior
Dialog box remains open, pulsing circle remains for at least 10 minutes.

### Expected behavior
Modification saves.

**Comment by jkmarx** [comment]
Ref #30 Updated his permission via admin console. Will be prevented with the fix of 3045
