### ISSUE TITLE
prevent IGV from receiving non-genome-browser data

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#302]
Tasks:
- [ ] 1h create whitelist in settings for (file type, file size)
- [ ] 3h create warning message that files were removed from users selection because of whitelist

Pivotal Tracker story 46988993 (Nils Gehlenborg - Mar 27, 2013)

**Comment by jkmarx** [comment]
Removed stand-alone igv from ui.
