### ISSUE TITLE
Upgrade Puppet to version 4.10 or greater

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#3096]
Current Puppet version: 3.4.3 (as of Refinery release v1.6.6)
Puppet >= 4.10.0 is required for [upgrading to puppet-rabbitmq v8.4.0](https://github.com/refinery-platform/refinery-platform/issues/1185)
[Puppet documentation for version 3 has been archived](https://docs.puppet.com/puppet/3/index.html) and is no longer easily accessible

Upgrading Puppet will require changes to the existing manifests (see below).

Alternatively, replace Puppet with Ansible:
* Ansible appears to be better suited for immutable deployments
* CloudMan uses Ansible
* Ansible has an easier syntax than Puppet

### Notes

This will probably require [upgrading to Ubuntu 16.04](https://github.com/refinery-platform/refinery-platform/issues/3118) or later (16.04: puppet (3.8.5-2) and 18.04: puppet (5.4.0-2ubuntu3)). It might be possible to [install Puppet 4 on Ubuntu 16.04](https://www.digitalocean.com/community/tutorials/how-to-install-puppet-4-on-ubuntu-16-04).

Installing Puppet 4.x on Ubuntu 14.04: https://stackoverflow.com/a/46822371 (binaries added to `/opt/puppetlabs/bin`)
Error after upgrading Puppet to v4.10.12:
```
ubuntu@ip-172-25-0-7:/srv/refinery-platform/deployment$ /usr/local/bin/librarian-puppet install
Unable to load puppet. Please install it using native packages for your platform (eg .deb, .rpm, .dmg, etc).
No such file or directory - puppet
```
Fixed by `export PATH=/opt/puppetlabs/bin:$PATH`
Error running Puppet v4.10.12:
```
/opt/puppetlabs/bin/puppet apply --modulepath=/srv/refinery-platform/deployment/modules /srv/refinery-platform/deployment/manifests/aws.pp
Warning: /etc/puppetlabs/puppet/hiera.yaml: Use of 'hiera.yaml' version 3 is deprecated. It should be converted to version 5
   (in /etc/puppetlabs/puppet/hiera.yaml)
Error: Evaluation Error: Error while evaluating a Function Call, Could not find class ::ui for ip-172-25-0-7.ec2.internal at /srv/refinery-platform/deployment/modules/refinery/manifests/init.pp:152:1 on node ip-172-25-0-7.ec2.internal
```

**Comment by jkmarx** [comment]
@scottx611x

**Comment by scottx611x** [comment]
For reference, I got up to [puppet 5.5.6](https://github.com/refinery-platform/refinery-platform/compare/scottx611x/postgres_upgrade#diff-639721f389be24b97df64ed12bd5f79fR11) in this branch: https://github.com/refinery-platform/refinery-platform/compare/scottx611x/postgres_upgrade
