### ISSUE TITLE
ISATab Metadata Import "Submit" button should be disabled after initial click

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#3097]
* Specific code commit: 789709b78b8777532d100211d9affde2cfdb6c88
* Version of the web browser and OS: `Chrome Version 70.0.3538.77 macOS 10.12.6`
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance):  https://test.stemcellcommons.org

### Steps to reproduce
Please list all the actions and the input data used:

1.  Import an ISATab-based metadata file
2. While it is importing click on the "Submit" button multiple times

### Observed behavior
* The "Submit" button isn't disabled and allows for one to make many POSTs to `/isa-tab-form`, which causes a full re-parse of the ISATab which is a costly operation on our system currently 
  * DataSet creation triggers the Neo4J performance bug Ref: #2789 & the ISATab parser isn't very performant either Ref: #463
* ![nov-07-2018 13-41-29](https://user-images.githubusercontent.com/5629547/48153025-4b86de80-e293-11e8-9223-9833ebf5270c.gif)

### Expected behavior
*  For the button to be disabled after its initial click

**Comment by jkmarx** [comment]
Not a new bug, from the hsci site. 
<img width="664" alt="screen shot 2018-11-09 at 7 12 27 am" src="https://user-images.githubusercontent.com/9956764/48261995-e942f080-e3ee-11e8-9f44-6dad0d2720be.png">

**Comment by hackdna** [comment]
See also #3114
