### ISSUE TITLE
Update Tutorial.md

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#3108]
- Ref #2680 

Needs to be updated:
- Removal of collaboration page
- New dashboard
- New location for explorer (old launch page)

**Comment by jkmarx** [comment]
@gmnelson Is this used to generate https://stemcellcommons.github.io/cscb-website/  and is it worth trying to update in this milestone?

**Comment by gmnelson** [comment]
@jkmarx The tutorial is now generated from https://github.com/stemcellcommons/cscb-website/blob/gh-pages/_tutorial/01_tutorial.md. That version also needs updating but, as it's independent from this codebase, I guess it doesn't need to be formally attached to a release.
