### ISSUE TITLE
Prevent submitting data set until all data files have been uploaded

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#3114]
* Specific code commit: v1.6.7
* Version of the web browser and OS: Chrome 70 on OS X 10.13.6
* Environment where the error occurred: AWS

### Steps to reproduce
1. Navigate to `data_set_manager/import/`
1. Add either tabular or ISA-Tab metadata file
1. Add some data files

### Observed behavior
Submit button is enabled
![screen shot 2018-11-14 at 18 12 18](https://user-images.githubusercontent.com/452575/48567915-3e3da580-e8cc-11e8-9583-ae01d4777d2c.png)

### Expected behavior
Submit button is disabled until all added data files have been uploaded

**Comment by jkmarx** [comment]
Not seeing this behavior in the tabular metadata.
<img width="1128" alt="screen shot 2019-01-08 at 7 21 02 am" src="https://user-images.githubusercontent.com/9956764/50830519-07a56980-1316-11e9-8c4b-7fb5b87e1f0b.png">

**Comment by jkmarx** [comment]
Also here's the chrome behavior in ISATAB-Metadata
<img width="298" alt="screen shot 2019-01-08 at 7 22 42 am" src="https://user-images.githubusercontent.com/9956764/50830602-45a28d80-1316-11e9-8709-72859aba7b72.png">

**Comment by hackdna** [comment]
Which commit?

**Comment by jkmarx** [comment]
771c8dd86ab85932b01b46c8f3cb38e9dbfbbe3a

**Comment by hackdna** [comment]
Still an issue in Vagrant and on AWS as of 9750a3e:

![screen shot 2019-01-08 at 16 57 39](https://user-images.githubusercontent.com/452575/50861733-98586580-1367-11e9-8323-4fbb425d80ed.png)

Also, Submit button should probably be disabled by default even if no files were added but local files is set to Yes:

![screen shot 2019-01-08 at 11 08 01](https://user-images.githubusercontent.com/452575/50861775-b6be6100-1367-11e9-80d2-17de38f58a8a.png)

**Comment by jkmarx** [comment]
Locally with 9750a3e61fbcd63c42dfd33f9a25dbc22bb6b60b did not see the issue. Version 71.0.3578.98 (Official Build) (64-bit). 
<img width="1347" alt="screen shot 2019-01-08 at 6 50 29 pm" src="https://user-images.githubusercontent.com/9956764/50866066-8a5e1100-1376-11e9-9d85-3c29b78ef7af.png">

**Comment by jkmarx** [comment]
Seen on the test-instance 001d84cae54ddbcc46ba04bc0d8048a0b7559ee0

![screen shot 2019-02-13 at 10 40 08 am](https://user-images.githubusercontent.com/9956764/52723614-d9055900-2f7b-11e9-99a6-1e838b870ba2.png)
