### ISSUE TITLE
Upgrade to Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#3118]
Currently used version 14.04.5 LTS has end of life date April 2019
Ubuntu 16.04.5 LTS has end of life date April 2021
https://wiki.ubuntu.com/Releases

[Travis CI has 16.04 available now](https://blog.travis-ci.com/2018-11-08-xenial-release)

See also: #1813 and #2616 

- https://wiki.ubuntu.com/XenialXerus/ReleaseNotes

**Comment by jkmarx** [comment]
https://www.vagrantup.com/docs/boxes.html

They officially recommend the bento boxes https://app.vagrantup.com/bento
Travis xenial-release https://blog.travis-ci.com/2018-11-08-xenial-release
