### ISSUE TITLE
Rename add_nodeset permission to something like own_nodeset

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#312]
add_nodeset is a instance level permission that is used to indicate the owner of that instance, so the name should reflect that.

need to find out the impact since name may not just be a label, so it could be affecting every model in the core app.

Pivotal Tracker story 46665801 (Ilya Sytchev - Mar 21, 2013)

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Qj1X5Ige&#x2F;5-312"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #312</a>

**Comment by jkmarx** [comment]
Ensure this issue is not found in node group.

**Comment by jkmarx** [comment]
Not an issue in node groups. Also, node sets will be removed with the file browser 2 integration.
