### ISSUE TITLE
Upgrade PostgreSQL to v10.6

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#3180]
The latest PostgreSQL version available is 10.6 ([as of November 8, 2018](https://www.postgresql.org/about/news/1905/)). 10.6 is also the version that is provisioned on Vagrant.

Currently (v.1.6.8), RDS instance with PostgreSQL version `10.5` is [provisioned on AWS](https://github.com/refinery-platform/refinery-platform/blob/v1.6.8/deployment/terraform/modules/rds/main.tf#L30). However, server version is [set](https://github.com/refinery-platform/refinery-platform/blob/v1.6.8/deployment/puppet/refinery/manifests/postgresql.pp#L4) to `10` in Puppet which results in both on AWS and in Vagrant:
```shell
$ psql --version
psql (PostgreSQL) 10.7 (Ubuntu 10.7-1.pgdg14.04+1)
$ pg_config --version
PostgreSQL 11.2 (Ubuntu 11.2-1.pgdg14.04+1)
```

This can cause issues when AWS upgrades PostgreSQL to the next minor version. Either PostgreSQL version should be fixed to a particular minor version everywhere or minor version upgrades should be allowed everywhere.

Also, look into enabling Performance Insights and Enhanced Monitoring with RDS.

**Comment by ngehlenborg** [comment]
As discussed, we should allow minor version upgrades across the board.
