### ISSUE TITLE
Delete button appears active for visualizations owned by others

### ISSUE THREAD

**Issue by gmnelson** [refinery-platform/refinery-platform#3186]
* Specific code commit: 1a93a1b
* Version of the web browser and OS: Chrome, macOS
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): hsci.stemcellcommons.org

### Observed behavior
* Delete button seemingly active for visualizations I don't own. Clicking the button appears to do nothing for those visualizations owned by other users.

![image](https://user-images.githubusercontent.com/23487494/52012311-48714800-24a8-11e9-80e9-b5b3dc94d1d1.png)

### Expected behavior
* Delete button should either be inactive or absent for visualizations belonging to other users

**Comment by scottx611x** [comment]
@gmnelson I believe @jkmarx has already addressed this with https://github.com/refinery-platform/refinery-platform/pull/3158

**Comment by jkmarx** [comment]
@scottx611x Thanks, I couldn't locate the issue.
