### ISSUE TITLE
Site_profiles API returns HTTP 404

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#3203]
* Specific code commit: 14e31136
* Version of the web browser and OS: Chrome 72 on OS X 10.14.3
* Environment where the error occurred: Vagrant

### Steps to reproduce
1. Provision a Vagrant VM from scratch
1. Open the home page in a web browser  

### Observed behavior
Browser console shows:
```
GET http://192.168.50.50:8000/api/v2/site_profiles/ 404 (NOT FOUND)
```
Refinery log shows:
```
[07/Feb/2019 10:33:08] "GET /api/v2/site_profiles/ HTTP/1.1" 404 42
```

### Expected behavior
No error

### Notes
Possibly related to #3200

**Comment by jkmarx** [comment]
That's an expected error msg, doesn't interfere with the user experience.

**Comment by hackdna** [comment]
Why is this error expected?

**Comment by jkmarx** [comment]
Because, there's no site profile associated with your fresh vm.

**Comment by hackdna** [comment]
I see. However, this error seems to indicate that `/api/v2/site_profiles/` URL does not exist. Shouldn't this simply return HTTP 200 with an empty list instead?
https://stackoverflow.com/questions/13366730/proper-rest-response-for-empty-table

**Comment by jkmarx** [comment]
Disagree on the 200. I'll add this issue to the developer's agenda.

**Comment by jkmarx** [comment]
@scottx611x and I discussed the confusion regarding a 404 from the site_profiles api. The solution: update the url to site_profiles/{'current'} . There is a possibility of multiple site profiles being associated with a site.

**Comment by ilan-gold** [comment]
@hackdna  do you have a preferred method here? should we go with jennifer's suggestion that we use a {'current'} value of sorts to indicate that it is just the hostname site-profile or is there a solution that involves storing an identifier for the site profile in the webpage that you'd prefer?

**Comment by jkmarx** [comment]
@ilan-gold https://github.com/refinery-platform/refinery-platform/wiki/coding-style-guide#rest-api   A query, site_profiles/?'current'  Unsure if current is the word we want to use, perhaps  /?current_site

**Comment by ilan-gold** [comment]
we haven gone with current_site and a true/false flag.  if false (or without a current_site parameter), it will return a list of all profiles.
