### ISSUE TITLE
IGV unable to access input files

### ISSUE THREAD

**Issue by gmnelson** [refinery-platform/refinery-platform#3219]
* Specific code commit: a4191bd
* Version of the web browser and OS: mac OS, Firefox
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): https://test.stemcellcommons.org

### Steps to reproduce
Please list all the actions and the input data used:

1. Launch IGV on an accepted input file(s) (e.g. bigwig)

### Observed behavior
![image](https://user-images.githubusercontent.com/23487494/53108855-be942800-3505-11e9-95a7-a192267eceaf.png)

### Expected behavior
* IGV launches without error and displays the input tracks

**Comment by jkmarx** [comment]
```Access to XMLHttpRequest at 'https://test-release-v168-media.s3.amazonaws.com/vfRGJZM/1_MACS2_bigwig_d00KMLL.bigwig' from origin 'https://test.stemcellcommons.org' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.```

**Comment by hackdna** [comment]
https://github.com/igvteam/igv.js/wiki/Data-Server-Requirements#cross-origin-resource-sharing-cors
