### ISSUE TITLE
Bring unit tests for file server up to date

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#322]
Expand unit test coverage.

**Comment by jkmarx** [comment]
@hackdna Is this still relevant? I noticed there are some unit tests already in the file servers tests.py

**Comment by hackdna** [comment]
I'd say yes: https://codecov.io/gh/parklab/refinery-platform/tree/ea729f877e1f4c69f9162134087280c329b56aa0/refinery/file_server

**Comment by jkmarx** [comment]
@hackdna Sorry, I misread your message.

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;wMXyJ6gT&#x2F;7-322"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #322</a>

**Comment by jkmarx** [comment]
No longer an issue, removing file server.
