### ISSUE TITLE
deploy IGV WebStart directly from Refinery site 

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#325]
Instead of deploying IGV from the Broad Institute website using the JNLP creator script at http://www.broadinstitute.org/igv/projects/current/igv.php Refinery should have built in support to create such JNLP files through a view. 

Refinery admins should only have to download an IGV version from http://www.broadinstitute.org/igv/projects/downloads (the IGV_x.x.xx.zip files are sufficient as far as I can tell, the distros contain a bunch of files that are not required for launching), put it into a directory and add the path to the settings. Additionally, they should provide the URL to be used for launching IGV (by default per settings.py this should be the Broad site but it can be overwritten with the "local" URL).
Tasks:
- [ ] create IgvLauncher app
- [ ] create settings for IgvLauncher
- [ ] create template for JNLP file
- [ ] figure out how to add the IGV directory to the list of static directories so that collectstatic will copy the files to a location where they can be accessed through the web server (required for Java WebStart)

Pivotal Tracker story 41716491 (Nils Gehlenborg - Dec 27, 2012)

**Comment by jkmarx** [comment]
Removed stand-alone igv from ui.
