### ISSUE TITLE
provide list of download URLs for selection

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#326]
- [ ] Instead of creating an archive we provide a list of URLs for bulk downloading with a script. Offer option to also include the meta data.

- [ ]  Currently have to download files one by one using the down arrow icon. Would like to select multiple files and hit download. Added from Issue #1253 

Pivotal Tracker story 41429707 (Nils Gehlenborg - Dec 18, 2012)

**Comment by scottx611x** [comment]
Resolved as of #2369
