### ISSUE TITLE
start discussion about "stop/pause" job API extension with Galaxy team

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#330]
Pivotal Tracker story 41355211 (Nils Gehlenborg - Dec 17, 2012)

**Comment by jkmarx** [comment]
@ngehlenborg @hackdna @scottx611x Is this issue still relevant?

**Comment by hackdna** [comment]
I vote to close. I'm not aware of any real use cases for this functionality and we already can stop running analyses in Galaxy by deleting their histories.

**Comment by jkmarx** [comment]
See above.
