### ISSUE TITLE
create optimized packages for jquery UI

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#334]
download custom JS that only contains the sortable UI features from jquery UI website.

Pivotal Tracker story 40912063 (Nils Gehlenborg - Dec 9, 2012)

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ZsjVE0l9&#x2F;8-334"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #334</a>

**Comment by jkmarx** [comment]
With the data set 2 browser, we will not be using the jquery UI library.
