### ISSUE TITLE
Fix names of REST API view classes

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#3345]
Several REST API view class names don't correspond to their respective base classes.

The following "viewsets" are derived from `APIView`:
- [x] `EventViewSet`
- [x] `AnalysisViewSet`
- [x]  `SiteProfileViewSet`
- [x]  `UserProfileViewSet`
- [x]  `StudyViewSet`
- [x]  `FileStoreItems`
- [x] `UserFiles`

They should be renamed.

**Comment by jkmarx** [comment]
Closed with #3381
