### ISSUE TITLE
allow searching in facet values

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#336]
Either search on client with type ahead or use solr to do a more thorough search.

Pivotal Tracker story 40911635 (Nils Gehlenborg - Dec 9, 2012)

**Comment by jkmarx** [comment]
Also the attribute filters order should match column.

**Comment by mccalluc** [comment]
@ngehlenborg : Do you want the facet searching from the cross-dataset browser brought over to within-dataset? I don't think it would be hard.

**Comment by ngehlenborg** [comment]
That would be fantastic if that doesn't extend the timeline for the 1.6.0 release.
