### ISSUE TITLE
allow lexicographical or alphanumeric sorting of facet attribute values

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#337]
K9 before K36 if possible. Sorting could be done on client or server.

Pivotal Tracker story 40911623 (Nils Gehlenborg - Dec 9, 2012)

**Comment by mccalluc** [comment]
@ngehlenborg : Do you want the facet sorting from the cross-dataset browser brought over to within-dataset? I don't think it would be hard.
