### ISSUE TITLE
Applying site updates using Fabric is broken

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#3403]
* Specific code commit: cd982a54
* Version of the web browser and OS: OS X 10.14.5
* Environment where the error occurred: Vagrant VM

### Steps to reproduce
Run `fab vm update`

### Observed behavior
Update is stuck at the password prompt:
```
[vagrant@127.0.0.1:2222] Executing task 'update'
[vagrant@127.0.0.1:2222] Updating Refinery
[vagrant@127.0.0.1:2222] run: git pull
No handlers could be found for logger "paramiko.transport"
[vagrant@127.0.0.1:2222] Login password for 'ubuntu':
```

If a password is entered:
```
Fatal error: Incompatible ssh peer (no acceptable kex algorithm)

Underlying exception:
    Incompatible ssh peer (no acceptable kex algorithm)

Aborting.
```

### Expected behavior
No error message. Updating works without asking for a password.

### Notes
This is probably connected to upgrade to Ubuntu 16.04 (#3391)

**Comment by hackdna** [comment]
Resolved by running `pip install -U -r deployment/requirements.txt`. @jkmarx this should be added to the release notes for v1.7.0.

**Comment by jkmarx** [comment]
Thanks!
