### ISSUE TITLE
introduce requireJS to handle JS libraries and scripts

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#342]
http://requirejs.org/docs/jquery.html

Pivotal Tracker story 40497729 (Nils Gehlenborg - Dec 2, 2012)

**Comment by ngehlenborg** [comment]
@flekschas: Is this worth pursuing?

**Comment by flekschas** [comment]
Definitely! There it's not super urgent but it will be in the future. Right now we load all the JavaScript needed for the whole website at once. This is usually beneficial for smaller to medium websites but it makes large JS-based websites slow. There are a bunch of different async script loaders and things will potentially become more easy with ES2015 alias ES6 alias JS6.

We should maybe investigate, which loader compile a small comparison to figure out the most future proof script loader.

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;GO0avmU0&#x2F;10-342"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #342</a>
