### ISSUE TITLE
Pass in Context for ToolSerializer

### ISSUE THREAD

**Issue by ilan-gold** [refinery-platform/refinery-platform#3455]
Noticed while working on #2619 
* Version of the web browser and OS: 
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Any

### Steps to reproduce
Please list all the actions and the input data used:

1.  Launch an analysis and look in the logs for a caught error about the user being None https://github.com/refinery-platform/refinery-platform/blob/37a93141a777a2ae61e21050982dd72af8d28a9c/refinery/core/serializers.py#L78

### Observed behavior
* AttribtueError

### Expected behavior
* Our handling of context should be {'request':request} here to prevent the error

**Comment by jkmarx** [comment]
@ilan-gold How are you/user hitting this error? Could you give a specific example. What do the DRF docs say? In general, I thought we wanted to minimize passing the context to the serializer but we have some use cases.

**Comment by ilan-gold** [comment]
@jkmarx https://github.com/refinery-platform/refinery-platform/blob/develop/refinery/tool_manager/views.py#L118 calls DatSetSerializer (via ToolSerliazer) without context.  When I was looking in to it, I noticed that the convention was inconsistent - the example on DRF's website uses context={'request' = request} and i think this makes sense.  but we, for example, do something different sometimes (like in https://github.com/refinery-platform/refinery-platform/blob/0683eba983b771f3941c7c13a1a2e0b9e316fd76/refinery/core/views.py#L1056)

**Comment by jkmarx** [comment]
@ilan-gold For the data_set example above, the context required more than the request in the context. 

https://www.django-rest-framework.org/api-guide/serializers/#including-extra-context

From the docs, "You can provide arbitrary additional context by passing a context argument when instantiating the serializer. " The purpose of context is to provide additional information not necessarily the request.
