### ISSUE TITLE
Bam File IGV Not Working

### ISSUE THREAD

**Issue by ilan-gold** [refinery-platform/refinery-platform#3465]
* Specific code commit: 
* Version of the web browser and OS: Any and Mac
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): 
AWS

### Steps to reproduce
This could potentially be related to #2718 but it is unclear at the moment.

Login as admin and navigate to https://hsci.stemcellcommons.org/data_sets/e3bee913-4b0c-4e61-961e-022086a42619/#/files/

Then launch an IGV on one of the .bam files available.

### Observed behavior
This log error seems suspicious
<img width="1436" alt="Screen Shot 2019-10-11 at 2 55 00 PM" src="https://user-images.githubusercontent.com/43999641/66682984-62bd1180-ec44-11e9-9083-bfeba061ce85.png">

No Data
![image](https://user-images.githubusercontent.com/43999641/66683552-c09e2900-ec45-11e9-9206-3880ca4c0f92.png)

### Expected behavior
No error

**Comment by ilan-gold** [comment]
there are two parts as to why this likely is not working:
1) #2718 is problematic in so far as the file is inaccessibly
2) igv appears to need an indexURL parameter for indexed files needed for certain visualizations in igv-js (https://github.com/igvteam/igv.js/wiki/Tracks-2.0)

i am investigating/working on both

**Comment by ilan-gold** [comment]
testing has completed and have confirmed this to be working - once #3471 and #3475 are resolved i will make the pull request against this and #2718.  i was unable to reproduce the issue seen in the log (although even when talking to geoff, it didn't actually affect the launch of the visualization).

**Comment by hackdna** [comment]
See also #2713
