### ISSUE TITLE
implement periodically running test workflow to monitor system performance and readiness

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#347]
Perform:
- file download from remote
- file import into galaxy
- file processing in galaxy workflow
- file download from galaxy
- history and dataset clean up
  Monitor:
- failures
- performance: time to completion

Pivotal Tracker story 38812795 (Nils Gehlenborg - Nov 1, 2012)

**Comment by scottx611x** [comment]
Planemo is close to being able to help us achieve this: https://github.com/galaxyproject/planemo/pull/770 We should probably do this integration testing in https://github.com/refinery-platform/galaxy-tools & https://github.com/stemcellcommons/scc-galaxy-tools though

**Comment by hackdna** [comment]
Vote to close in favor of using [Cloudwatch](https://aws.amazon.com/cloudwatch/) for resource monitoring.

**Comment by scottx611x** [comment]
@hackdna what if I renamed this to `Galaxy Workflow Integration Tests`?

**Comment by hackdna** [comment]
I don't think this is going to be worth the effort to automate. Interaction with Galaxy is via Bioblend (no need to test a 3rd party library). The only time testing is needed is during Galaxy version upgrades that don't happen often.

**Comment by scottx611x** [comment]
Okay will close then
