### ISSUE TITLE
implement user authentication via API keys or tokens

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#359]
provide API for eXframe to submit ISA-Tab files as the first step of running analyses

Pivotal Tracker story 32561513 (Ilya Sytchev - Jul 10, 2012)

**Comment by jkmarx** [comment]
@hackdna Is this something we're still interested in?

**Comment by hackdna** [comment]
No, we'll be retiring that system (currently serving http://stemcellcommons.org) some time this year, so closing.
