### ISSUE TITLE
incorporate support for messaging 

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#360]
Users should receive messages when analyses finish or other things change that are relevant to them (e.g. starred projects or data sets), when something is un/shared with them, etc.
Tasks:
- [ ] define message categories
- [ ] review available message packages for django
- [ ] implement messages

Pivotal Tracker story 32490527 (Nils Gehlenborg - Jul 9, 2012)

**Comment by jkmarx** [comment]
Is this still an enhancement we'd like to incorporate?
