### ISSUE TITLE
Sample names from ISA-Tab are not being displayed

### ISSUE THREAD

**Issue by sjhosui** [refinery-platform/refinery-platform#441]
Name field in refinery currently contains the file name. Sample names are also informative and help us map back to the original data.

**Comment by jkmarx** [comment]
If there's a column with sample_names, they should show up in the file_browser & user_files.

**Comment by jkmarx** [comment]
![screen shot 2018-03-14 at 8 52 01 am](https://user-images.githubusercontent.com/9956764/37403399-1bb593f2-2765-11e8-90a0-1a86c5f66e90.png)
