### ISSUE TITLE
Add support for Galaxy dataset collections

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#444]
Multiple dataset processing is implemented by workflow expansion from templates in Refinery. Galaxy now supports this internally via dataset collections.
https://wiki.galaxyproject.org/News/2014_06_02_Galaxy_Distribution
http://bit.ly/gcc2014workflows
https://github.com/jmchilton/gcc2014_demo

---

- [x] Add `WorkflowTool` method to create collection descriptions, and the collections themselves regardless of nesting depths (addressed by #1980)
    - See : OO approach to this [here](https://github.com/galaxyproject/bioblend/blob/14fe59350192d799fbbcaf0b687c7d6780933d50/bioblend/_tests/TestGalaxyDatasetCollections.py#L42-L63)

- [x] Retrieve output after DSC -based Workflow runs and reassociate with their respective Refinery Dataset

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;2JPOEbhC&#x2F;11-444"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #444</a>

**Comment by scottx611x** [comment]
Hi @jmchilton, We are currently getting around to this work in Refinery. 

Just for some context, We are building a generic tool interface where a user can specify some metadata about their Workflow's inputs, outputs, and tool parameters (including arbitrary levels of nested `list`/`paired` to build DataSet Collections off of).

I've messed around with bioblend, and have been able to create Collections with at least 3 levels of nesting, but if my memory serves me right, things start getting a little wonky Galaxy-side past this point. I have an `.ipynb` lying around somewhere if an example is needed.

I've seen some issues in galaxy regarding collections and lately: https://github.com/galaxyproject/galaxy/issues/4013 has really peaked my interest.

Could you give a short summary on your findings/plans for Collections in the future?! :)
