### ISSUE TITLE
Replace optparse with argparse.

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#459]
"Deprecated since version 2.7: The optparse module is deprecated and will not be developed further; development will continue with the argparse module." (https://docs.python.org/2/library/optparse.html)

https://docs.python.org/2/library/argparse.html#upgrading-optparse-code

**Comment by jkmarx** [comment]
https://argparse.googlecode.com/svn/trunk/doc/argparse-vs-optparse.html

**Comment by flekschas** [comment]
I notice one limitation. Django 1.5 comes with predefined optparse option for management commands so until we updated Django we cannot completely get rid of optparse.

> Changed in Django 1.8:
> Before Django 1.8, management commands were based on the optparse module, and positional arguments were passed in *args while optional arguments were passed in **options. Now that management commands use argparse for argument parsing, all arguments are passed in **options by default, unless you name your positional arguments to args (compatibility mode). You are encouraged to exclusively use **options for new commands.

https://docs.djangoproject.com/en/1.8/howto/custom-management-commands/

**Comment by jkmarx** [comment]
In reference to the above comment by Fritz, we'll hold on updating the module until we're using Django 1.8.

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;hUfktAI6&#x2F;12-449-459"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #449, #459</a>

**Comment by jkmarx** [comment]
- [ ] core
    - [ ] activate_user
    - [ ] add_users_to_public_group
    - [ ] clear_annotations
    - [ ] create_public_group
    - [ ] create_user
    - [ ] create_workflowengine
    - [ ] import_annotations
    - [ ] import_ontology
    - [ ] install_solr_synonym_plugin
    - [ ] set_up_site_name
    - [ ] solr_synonyms
    - [ ] uninstall)solr_synonym_plugin
- [ ] data_set_manager
    - [ ] mage2isa_convert
    - [ ] process_arrayexpress_isatab
    - [ ] process_isatab
    - [ ] process_metadata_table
- [ ] tool_manager: load_tools
