### ISSUE TITLE
Set up search query logger

### ISSUE THREAD

**Issue by flekschas** [refinery-platform/refinery-platform#509]
To collect feedback and evaluate the performance of our search, it would be good to have an search query logger. This could be set up manually via Google Analytics once Refinery is deployed or we install a local Piwik instance that runs within the VM.

**Comment by flekschas** [comment]
Instructions for Google Analytics: https://support.google.com/analytics/answer/1012264?hl=en

@hackdna could we quickly set this up together after the next meeting? It should take long.

**Comment by jkmarx** [comment]
@hackdna Did y'all meet on this issue?

**Comment by hackdna** [comment]
I don't think we had a meeting to discuss this - probably because there is limited interest in this functionality.

**Comment by jkmarx** [comment]
@hackdna Then, I'm going to close this issue for now.
