### ISSUE TITLE
Check if certifi and pycparser packages are necessary

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#532]
Introduced in dc9cd8b. Remove from requirements.txt if not necessary.
https://pypi.python.org/pypi/certifi
https://pypi.python.org/pypi/pycparser

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;pkLZ49l1&#x2F;15-532"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #532</a>

**Comment by jkmarx** [comment]
@ngehlenborg Could you comment? I did a quick search and did not see these libraries being utilized.

**Comment by hackdna** [comment]
They might be dependencies of another Python package that's required. I don't think there is an easy way to check what packages require a given module. To get this info you'd need to run `pip show <package_name>` for each of the packages listed by `pip list` or `pip freeze`. For example, Bioblend requires requests, poster, boto, pyyaml:
```
(refinery-platform)vagrant@refinery:/vagrant/refinery$ pip show bioblend
---
Metadata-Version: 1.1
Name: bioblend
Version: 0.5.0
Summary: CloudMan and Galaxy API library
Home-page: http://bioblend.readthedocs.org/
Author: Enis Afgan
Author-email: afgane@gmail.com
License: MIT
Location: /home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages
Requires: requests, poster, boto, pyyaml
Classifiers:
  Development Status :: 3 - Alpha
  Intended Audience :: Developers
  License :: OSI Approved :: MIT License
  Operating System :: OS Independent
  Topic :: Internet
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
```

**Comment by jkmarx** [comment]
@hackdna FYI. Tornado has certifi as a dependency. Cryptography has cffi which has pycparser as a dependency.
