### ISSUE TITLE
Remove bitstring package and related code

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#569]
No longer used: tdf_file.py

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;akalwNfY&#x2F;18-569"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #569</a>

**Comment by jkmarx** [comment]
File server code, original implementation had bit string code. No longer used. Should be quick to do.

**Comment by hackdna** [comment]
Closed in #2635
