### ISSUE TITLE
Test `core.NodeSetListResourceTest.test_get_nodeset_list` fails.

### ISSUE THREAD

**Issue by flekschas** [refinery-platform/refinery-platform#586]
The nodeset API's authorization is not working. For that reason the test fails.

I commented out the test for now until authorization works. See fc6c88.

**Comment by flekschas** [comment]
`core.NodeSetResourceTest.test_get_nodeset_list` is almost the same test and fails for exactly the same reason so I'll comment it out as well.

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;9PmnKWFQ&#x2F;19-586"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #586</a>

**Comment by jkmarx** [comment]
Ensure there's a separate issue for nodeset authorization.

**Comment by jkmarx** [comment]
Node sets will be obsolete after the file browser 2 upgrade. Closing this issue for now.
