### ISSUE TITLE
settings.CONVERSION_DIR is used but not set in Django settings

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#588]

**Comment by ngehlenborg** [comment]
`settings.CONVERSION_DIR` is used for conversion of (ArrayExpress) MAGE-Tab archives to ISA-Tab. This should be set to a directory outside the git repo, e.g. `vagrant`. @hackdna, what do you think?

**Comment by hackdna** [comment]
OK. There are already a few directories that are used for data storage. They exist at the top level and are excluded from version control in the top level `.gitignore`:
```
/isa-tab/
/import/
/transfer/
```
There is also a `/media/` directory which is tracked in git. So, I suggest we consolidate at least the first three under one directory (`/data/`?) and then add a `CONVERSION_DIR` there.

**Comment by ngehlenborg** [comment]
Yes, let's do that. `/data/` it is.

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Tuz3ExnV&#x2F;21-616"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Move isa-tab, import and transfer dirs into data dir</a>

**Comment by jkmarx** [comment]
@hackdna I couldn't find this setting used. Can you confirm?

**Comment by hackdna** [comment]
Removed in #3171.
