### ISSUE TITLE
DataSet API returns different types of objects

### ISSUE THREAD

**Issue by flekschas** [refinery-platform/refinery-platform#594]
The DataSet API, and possible others too, return two different types of objects: `QuerySet`s and `list`s.

**Lists**:
`http://192.168.50.50:8000/api/v1/data_sets/?offset=0` returns a `list`.

**QuerySets**:
`http://192.168.50.50:8000/api/v1/data_sets/` returns a `QuerySet` complaining that `'QuerySet' object has no attribute 'sort'`. While the error is expected, it's unclear why a `QuerySet` is return.

In practice the error is never thrown as `uiScroll` always passes `offset` and `limit` to the API but the architecture is confusing.

**Comment by jkmarx** [comment]
Transitioning to data set api v2, so not an issue which needs to be addressed directly.
