### ISSUE TITLE
analysis titles swapped when two analyses are launched simultaneously

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#631]

**Comment by ngehlenborg** [comment]
The problem is related to the _Current Selection_ node set and there seem to be two issues: 

1. Since it is stored in the database by default, the _Current Selection_ node set is overwritten if the same user has two tabs open two set up analyses/visualizations and changes the selection in one. This also leads to an issue with the "Launch Analysis" button being disabled when although some files are selected in the current browser tab if the user deselected all files in a second tab after making a selection in the first tab.
1. The node set selector on the data set page seems to disregards the node set owner for the _Current Selection_ (and all others?)

**Comment by mccalluc** [comment]
@scottx611x : With all the changes you've put into workflows and analysis, I'd be surprised if this is still an issue?

**Comment by scottx611x** [comment]
@mccalluc I agree that this isn't an issue anymore, we aren't utilizing the `Current Selection` in FB2

**Comment by ngehlenborg** [comment]
We should test it.
