### ISSUE TITLE
Study API takes long time when the dataset has many files associated to it

### ISSUE THREAD

**Issue by flekschas** [refinery-platform/refinery-platform#738]
Example: http://ec2-54-85-203-7.compute-1.amazonaws.com/#/
Dataset: Single cell RNA-seq of primary human glioblastomas

http://192.168.50.50:8000/api/v1/data_sets/YOUR-FANCY-UUID/studies/

Related code:
https://github.com/parklab/refinery-platform/blob/develop/refinery/core/api.py#L461-L470

**Comment by flekschas** [comment]
The actual query that takes up so much time is this: https://github.com/parklab/refinery-platform/blob/develop/refinery/data_set_manager/api.py#L145-L156

**Comment by jkmarx** [comment]
@scottx611x Is this related to your data set api performance improvement?

**Comment by scottx611x** [comment]
@jkmarx Nope this is different. I believe we hit this issue recently with the BII instance. I think things start getting noticeably slow when a DataSet starts encroaching on 1000 Nodes

**Comment by jkmarx** [comment]
Removed old data set and study api. The current study api does not return a nodes list.
