### ISSUE TITLE
Remove unused templates?

### ISSUE THREAD

**Issue by flekschas** [refinery-platform/refinery-platform#783]
While trying to make sure that we use the up-to-date version of D3 I came across templates that seem to be used.
For example:
- `data_set_manager/contents.html`
- `data_set_manager/contents_backbone.html`

**Comment by ngehlenborg** [comment]
You can delete the above templates.

**Comment by jkmarx** [comment]
Also the data set import templates.

**Comment by mccalluc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;iBue2GtS&#x2F;27-783"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #783</a>
