### ISSUE TITLE
Dataset page wastes space on small screens

### ISSUE THREAD

**Issue by flekschas** [refinery-platform/refinery-platform#786]
I notice that there is an unnecessary offset between the orange buttons and tabs on small screen sizes. This is the case for both versions, bootstrap 2 and bootstrap 3.

Also the filters use lots of space on small screen sizes.

![bildschirmfoto 2015-11-27 um 15 01 23](https://cloud.githubusercontent.com/assets/932103/11447660/12755534-9518-11e5-9636-59806fffc85a.png)

![bildschirmfoto 2015-11-27 um 14 59 04](https://cloud.githubusercontent.com/assets/932103/11447662/17734f46-9518-11e5-988b-307d20948a4e.png)

**Comment by jkmarx** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;cjreEMIT&#x2F;180-786-dataset-pages-layout-when-minimized"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #786 Dataset Pages Layout when minimized</a>

**Comment by jkmarx** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Hs21FuIF&#x2F;191-dataset-browser-enhancements"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Dataset Browser Enhancements</a>

**Comment by jkmarx** [comment]
This issue is resolved in the data set2 browser, so closing it for now.
