### ISSUE TITLE
Migrate Travis CI config to Trusty build environment

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#800]
Ubuntu Precise is used currently by Travis CI. This change will match the Ubuntu version used by the Vagrant VM.
It might also help with this build error:

```
2015-12-04 12:24:05 ERROR    core.utils:152 add_read_access_in_neo4j() - Failed to add read access for users ([-1]) to data sets (uuids: []) to Neo4J. Exception: Transaction support not available from this Neo4j server version
```

[The Trusty beta Build Environment](https://docs.travis-ci.com/user/trusty-ci-environment/)

**Comment by mccalluc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;JqIF2w5D&#x2F;28-800"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #800</a>

**Comment by scottx611x** [comment]
@mccalluc I believe this can be closed as of: https://github.com/refinery-platform/refinery-platform/pull/1930 correct?

**Comment by mccalluc** [comment]
sure
