### ISSUE TITLE
provenance graph timeline can be shifted

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#816]
**Reproduce**
Click and drag time line control in provenance graph info panel.

**Observed**
![dec 10 2015 05 13](https://cloud.githubusercontent.com/assets/1216518/11712745/fe118092-9efc-11e5-94dc-66e116450b03.gif)
(time line can be shifted left/right by clicking and dragging it)

**Expected**
No shifting!

**Comment by sluger** [comment]
This is intended and is really more like a feature than a bug as it is needed for semantic zoom. When you zoom into the timeline, the context gets occluded by the constrained drawing space so pan is necessary.

**Comment by jkmarx** [comment]
Encapsulated in larger issue. Ref #1338
