### ISSUE TITLE
Ui-scroll list is blocked during API calls

### ISSUE THREAD

**Issue by flekschas** [refinery-platform/refinery-platform#819]
As long as the ui-scroll list loads more data the list is kind of blocked or frozen, i.e. scrolling or other actions are not possible anymore. This is noticeable when the API calls take a bit longer.

Expected:
The API call shouldn't freeze the list.

This could be an issue related to our `ui-scroll-source` or the plugin itself.

I've delayed the API response manually by freezing the related JS service and the corresponding ui-scroll-list will freeze for exactly the same time span.

**Comment by jkmarx** [comment]
With the API improved performance, this should relieve this problem. Ref #2757

**Comment by hackdna** [comment]
So if the site experiences a high CPU load and thus slower API responses then scrolling would be still affected?
