### ISSUE TITLE
Dataset API always returns is_owner=true

### ISSUE THREAD

**Issue by flekschas** [refinery-platform/refinery-platform#826]
**Reproduce:**
1. Login as non-admin user A
2. Upload dataset X
3. Share dataset X with the public
4. Login as non-admin user B
5. API will return dataset X with `is_owner=true` for user B.

**Observed:**

> 1. API will return dataset X with `is_owner=true` for user B.

**Expected:**

> 1. API will return dataset X with `is_owner=false` for user B.

**Comment by flekschas** [comment]
I guess this is currently an expected behavior because when sharing a dataset with somebody we are giving that group `add` permission, which in our case is equivalent to sharing the ownership.

See ownership definitions:
https://github.com/parklab/refinery-platform/blob/develop/refinery/core/models.py#L260

See sharing definition:
https://github.com/parklab/refinery-platform/blob/develop/refinery/core/models.py#L304

Is that a desired behavior?

**Comment by hackdna** [comment]
I've observed this with "[Transcription factor binding during intestinal cell differentiation [TFB]](https://test.stemcellcommons.org/data_sets/79eb4dca-ebdf-428d-9dcd-173265aaaa82/#/files/browse)". Commit: e8b9869

**Comment by jkmarx** [comment]
Resolved previously with https://github.com/refinery-platform/refinery-platform/pull/2959/files
