### ISSUE TITLE
Fix name and location of fadapa.py

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#834]
May be replaced in a few months.

**Comment by mccalluc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;L5xvEtog&#x2F;32-834"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #834</a>

**Comment by jkmarx** [comment]
File is gone.
