### ISSUE TITLE
Why are AnnotatedNodes stored?

### ISSUE THREAD

**Issue by flekschas** [refinery-platform/refinery-platform#844]
Related to #843, #842 and #568 I had a quick look where they are used across Refinery:

```
$ grep -rl 'AnnotatedNode' .
./core/search_indexes.py
./data_set_manager/admin.py
./data_set_manager/migrations/0001_initial.py
./data_set_manager/migrations/0002_auto__add_field_node_analysis_uuid__add_field_node_subanalysis__add_fi.py
./data_set_manager/models.py
./data_set_manager/search_indexes.py
./data_set_manager/utils.py
```

(`pyc` files are excluded)

It turns out that `AnnotatedNodes` are only used 3 times for filtering, during the creating of index data. It looks like the model is never used actively outside the creation of datasets. Maybe I am missing something but my the question is what `AnnotatedNodes` are suppose to be used for.

---

**./core/search_indexes.py**
- [Lines 122-132](https://github.com/parklab/refinery-platform/blob/develop/refinery/core/search_indexes.py#L122-L132)

```
nodes = list(AnnotatedNode.objects.filter(
    study__uuid=study.uuid,
    assay__uuid=assay.uuid,
    node_type__in=Node.FILES
).distinct(
    'node_name',
    'attribute_type',
    'attribute_subtype',
    'attribute_value',
    'attribute_value_unit'
))
```

**./data_set_manager/admin.py**
- [Lines 17-25](https://github.com/parklab/refinery-platform/blob/develop/refinery/data_set_manager/admin.py#L17-L25)

Just for displaying the model in the admin interface.

**./data_set_manager/models.py**
- [Lines 535-655](https://github.com/parklab/refinery-platform/blob/develop/refinery/data_set_manager/models.py#L535-L655)

Just defines the model.

**./data_set_manager/search_indexes.py**
- [Line 58](https://github.com/parklab/refinery-platform/blob/develop/refinery/data_set_manager/search_indexes.py#L58)

```
annotations = AnnotatedNode.objects.filter(node=object)
```

**./data_set_manager/utils.py**

Two methods directly work with `AnnotatedNodes`:
1. `update_annotated_nodes()`
   Executed during the creation of a new dataset (`./data_set_manager/task.py`)
2. `add_annotated_nodes()` & `add_annotated_nodes_selection()` (through _add_annotated_nodes)
   `add_annotated_nodes()` is used nowhere
   `add_annotated_nodes_selection()` is used once in `./analysis_manager/task.py` when `attach_outputs_dataset()` is triggered. 
- [Lines 305-320](https://github.com/parklab/refinery-platform/blob/develop/refinery/data_set_manager/utils.py#L305-L320)

```
if assay_uuid is None:
    counter = AnnotatedNode.objects.filter(
        Q(study__uuid=study_uuid, assay__uuid__isnull=True),
        node_type=node_type).count()
    AnnotatedNode.objects.filter(
        Q(study__uuid=study_uuid, assay__uuid__isnull=True),
        node_type=node_type).delete()
else:
    counter = AnnotatedNode.objects.filter(
        Q(study__uuid=study_uuid, assay__uuid__isnull=True) |
        Q(study__uuid=study_uuid, assay__uuid=assay_uuid),
        node_type=node_type).count()
    AnnotatedNode.objects.filter(
        Q(study__uuid=study_uuid, assay__uuid__isnull=True) |
        Q(study__uuid=study_uuid, assay__uuid=assay_uuid),
        node_type=node_type).delete()
```
- [Lines 330-356](https://github.com/parklab/refinery-platform/blob/develop/refinery/data_set_manager/utils.py#L330-L356)

```
for node_id, node in nodes.iteritems():
    if node["type"] == node_type:
        # save attributes (attribute[1], etc. are based on
        # Attribute.ALL_FIELDS)
        attributes = _get_parent_attributes(nodes, node_id)
        for attribute in attributes:
            counter += 1
            bulk_list.append(
                AnnotatedNode(
                    node_id=node["id"],
                    attribute_id=attribute[0],
                    study=study,
                    assay=assay,
                    node_uuid=node["uuid"],
                    node_file_uuid=node["file_uuid"],
                    node_type=node["type"],
                    node_name=node["name"],
                    attribute_type=attribute[1],
                    attribute_subtype=attribute[2],
                    attribute_value=attribute[3],
                    attribute_value_unit=attribute[4]))
            if len(bulk_list) == MAX_BULK_LIST_SIZE:
                AnnotatedNode.objects.bulk_create(bulk_list)
                bulk_list = []
if len(bulk_list) > 0:
    AnnotatedNode.objects.bulk_create(bulk_list)
    bulk_list = []
```
- [Lines 402-431](https://github.com/parklab/refinery-platform/blob/develop/refinery/data_set_manager/utils.py#L402-L431)

```
for node_id, node in nodes.iteritems():
    if node["type"] == node_type:
        if node_uuids is not None and (node["uuid"] in node_uuids):
            # save attributes (attribute[1], etc. are based on
            # Attribute.ALL_FIELDS)
            attributes = _get_parent_attributes(nodes, node_id)

            for attribute in attributes:
                counter += 1

                bulk_list.append(
                    AnnotatedNode(
                        node_id=node["id"],
                        attribute_id=attribute[0],
                        study=study,
                        assay=assay,
                        node_uuid=node["uuid"],
                        node_file_uuid=node["file_uuid"],
                        node_type=node["type"],
                        node_name=node["name"],
                        attribute_type=attribute[1],
                        attribute_subtype=attribute[2],
                        attribute_value=attribute[3],
                        attribute_value_unit=attribute[4]))
                if len(bulk_list) == MAX_BULK_LIST_SIZE:
                    AnnotatedNode.objects.bulk_create(bulk_list)
                    bulk_list = []
if len(bulk_list) > 0:
    AnnotatedNode.objects.bulk_create(bulk_list)
    bulk_list = []
```

**Comment by ngehlenborg** [comment]
Annotated nodes are stored to speed up retrieval of all attributes associated with a given node. We store this information explicitly because retrieving all attributes associated with a node required tracing all paths from the node to the roots of the experiment/provenance graph. In the current data model this is an extremely expensive operation.

**Comment by jkmarx** [comment]
Since Nils answered this question, I'm closing for now. @flekschas If you have any follow up questions or would like to make an issue, please comment.
