### ISSUE TITLE
Puppet modules should not live in project directory

### ISSUE THREAD

**Issue by drj11** [refinery-platform/refinery-platform#853]
Currently the puppet modules get installed (by `librarian-puppet`) into the `deployment/modules` directory.

This is a bit messy and there is no need for it.

Could/should go somewhere else.

@hackdna suggests `/tmp/modules` but I'm not so sure about that. Is there a standard puppet place?

**Comment by hackdna** [comment]
I've suggested `/tmp/modules` following the code snippet here: http://blog.james-carr.org/2014/05/05/effective-puppet-module-management-in-vagrant/
What would be the downside?

**Comment by drj11** [comment]
We would have to ensure that `/tmp` was preserved across reboots.

`/var/cache/puppet` or `/usr/local/lib/puppet` might be better, but i'm really not that fussed.

**Comment by hackdna** [comment]
[Puppet Modulepath docs](https://docs.puppetlabs.com/puppet/3.6/reference/dirs_modulepath.html) say:
```bash
$confdir/modules:/usr/share/puppet/modules`
```
In our case this translates to:
```bash
vagrant@refinery:~$ puppet config print modulepath
/home/vagrant/.puppet/modules:/usr/share/puppet/modules
```
However:
```bash
vagrant@refinery:~$ ls -al /home/vagrant/.puppet/modules
ls: cannot access /home/vagrant/.puppet/modules: No such file or directory
vagrant@refinery:~$ ls -al /usr/share/puppet/modules
total 8
drwxr-xr-x 2 root root 4096 Feb  5  2015 .
drwxr-xr-x 3 root root 4096 Apr 15  2015 ..
```
So, it looks like `/usr/share/puppet/modules` is the best choice.

**Comment by drj11** [comment]
yay!

`/usr/share/puppet/modules`

**Comment by mccalluc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;dPxHsNY3&#x2F;33-853"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #853</a>

**Comment by hackdna** [comment]
This would also allow to avoid specifying a module path explicitly in `aws.sh` and `Vagrantfile`
