### ISSUE TITLE
Project deployment directory is cluttered with .tmp and .librarian

### ISSUE THREAD

**Issue by drj11** [refinery-platform/refinery-platform#854]
`librarian-puppet` (I think) creates stateful `.tmp` and `.librarian` subdirectories in the `deployment` directory.

These are clutter and should be moved elsewhere.

http://blog.james-carr.org/2014/05/05/effective-puppet-module-management-in-vagrant/ refers.

**Comment by mccalluc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;wKH3lvYW&#x2F;34-854"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #854</a>
