### ISSUE TITLE
Provide status updates for each Galaxy file import

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#878]
There is no progress reported for Galaxy file import which can take a long time. We should refactor `import_analysis_in_galaxy()` and `start_galaxy_analysis()` to create separate galaxy_import tasks for each file like in `get_galaxy_download_tasks()`.

**Comment by mccalluc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;s6fH3OBo&#x2F;37-878"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #878, #879</a>
