### ISSUE TITLE
Merge Analysis().prepare_galaxy() into start_galaxy_analysis()

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#879]

**Comment by jkmarx** [comment]
Ref #878

**Comment by mccalluc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;s6fH3OBo&#x2F;37-878"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #878, #879</a>

**Comment by scottx611x** [comment]
Closing this as we are going to be utilizing the new Tool-based approach witch doesn't use these methods.
