### ISSUE TITLE
Cleanup Python module imports

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#890]
Address circular imports!

Update the Django File Imports to Code Style Guide below, also in wiki.
- [x] Remove all 'import *' and specify files
- [x]  Update local imports to following format
     from .models import WaffleCone
     from .forms import WaffleConeForm
     from core.views import FoodMixin
- [ ] Organize imports according to the follow:
    From Wiki:
     Module imports should be grouped in the following order with blocks separated by a single blank line:
-        standard library imports
-        imports from core Django
-        imports from third party libraries and apps
-        imports from the apps that you created as part of your Django project
-        Use explicit relative imports: from **future** import absolute_import

**Comment by mccalluc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;p83yKDaK&#x2F;39-890"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #890</a>

**Comment by jkmarx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Utilize request library's response.json() instead of json.loads(response.content)](https://trello.com/c/SOiH9zXI/112-utilize-request-library-s-response-json-instead-of-json-loads-response-content)
