### ISSUE TITLE
Add description of backup and recovery on AWS to wiki

### ISSUE THREAD

**Issue by drj11** [refinery-platform/refinery-platform#901]
Add instructions here: https://github.com/parklab/refinery-platform/wiki/Backing-up-a-refinery-instance

There are infinitely complex user requirements here, but we need to make a basic reasonable decision and make it possible for the user to get backups.

Backups can be expensive, so this isn't trivial.

Items to backup: root volume(?), data volume, RDS.

This also implies creating a recovery procedure and testing it to make sure both backup and restore work as required.

https://media.amazonwebservices.com/AWS_Backup_Recovery.pdf

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0dqHQzfq&#x2F;34-prepare-scc-demo-on-aws"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> prepare SCC demo on AWS</a>

**Comment by drj11** [comment]
We have had https://github.com/refinery-platform/refinery-platform/wiki/AWS-backups for a while now.
