### ISSUE TITLE
Update Matrix View in New DataSet View

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#915]
- [ ] Upgrade Matrix View to use new Assay/Files Api, Update pivot assignments
- [ ] Remove other old-code jquery dependencies

**Comment by jkmarx** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Hs21FuIF&#x2F;191-dataset-browser-upgrade-phase-1"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Dataset Browser Upgrade, Phase 1</a>

**Comment by mccalluc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;PIN4qCiV&#x2F;40-915"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #915</a>

**Comment by jkmarx** [comment]
The previous matrix view code was removed and is not in the immediate plans to reintegrate. Will reopen if we decide to recreate the feature.
