### ISSUE TITLE
Distinguish between different attribute annotations

### ISSUE THREAD

**Issue by flekschas** [refinery-platform/refinery-platform#918]
Currently the exploration tool displays all available data set annotations equally. The different types of attributes should be visualized differently and it should be possible to hide certain annotation types.

Relevant Types:
- Characteristics
- Label
- Factor Value
- Material Type (I found only one ontology annotation so it might not be important?)

**Comment by jkmarx** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Hs21FuIF&#x2F;191-dataset-browser-upgrade-phase-1"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Dataset Browser Upgrade, Phase 1</a>

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;P37o9MWh&#x2F;226-data-set-contents-not-displayed-when-re-launching-refinery-on-aws"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Data set contents not displayed when re-launching Refinery on AWS</a>

**Comment by flekschas** [comment]
@hackdna This is a UI issue related to how nodes and rectangles are styled in the exploration vis. Not sure if this is related to AWS at all. :)

**Comment by hackdna** [comment]
Sorry, referenced it by mistake.

**Comment by jkmarx** [comment]
Exploration UI issue
