### ISSUE TITLE
Refactor data-set-nav: don't use rootScope

### ISSUE THREAD

**Issue by flekschas** [refinery-platform/refinery-platform#943]
Currently we're using the root scope to store data for navigating the three special tabs on the data set page: browse, analyze and visualize.

See for example here: https://github.com/parklab/refinery-platform/blob/develop/refinery/ui/source/js/data-set-nav/state.js#L11-L14

While this is technically it can cause trouble in the future. Why?
1. Angular scope's will go away in the future. Avoiding them when they are not needed ensures a smoother transition into the future, i.e. Angular 2.
2. The root scope can indeed be used to store global properties that apply to the whole app but the three tabs only apply to the data set page and are meaningless everywhere else. Hence, the data set page should take care of it.
3. A simple service can manage the active tab just fine and it's easier to find related code. For example, the node-mapping sets `rootScope.mode` so I was wondering what kind of _mode_ this is and where it's actually used. There can be many modes across our app. If instead a service is injected which is called something like `dataSetNavMode` it would immediately apparent what is going on.
4. Like in any language polluting the global scope is bad practice.

**Comment by ngehlenborg** [comment]
Related to #639 (h/t @jkmarx).

**Comment by jkmarx** [comment]
With data set 2, we are no longer using the browse/analyze/visualize tabs.
