### ISSUE TITLE
RepoExplorer: List graph doesn't re-root on page load

### ISSUE THREAD

**Issue by flekschas** [refinery-platform/refinery-platform#961]
When the is reloaded with a specific root / query node in the URL the treemap automatically zooms too that specific node but the list graph doesn't. Normal zooming within the tree map is reflected in the list graph automatically so it must have to do with the initial page load.

**Comment by mccalluc** [comment]
Both the treemap and the list graph are zooming on load now. Checked FF and Chrome on Mac. Closing.

![screen shot 2017-07-18 at 4 40 51 pm](https://user-images.githubusercontent.com/730388/28338727-d8bdb438-6bd7-11e7-99b9-dead4e62e92f.png)
