### ISSUE TITLE
RepoExplorer: Two AND queries don't work as expected

### ISSUE THREAD

**Issue by flekschas** [refinery-platform/refinery-platform#962]
Querying for profiling assay and factor binding assay via an AND query should lead to no results but returns everything.

**Comment by mccalluc** [comment]
I don't see these terms. Have the vocabularies you load changed? Do you think there is still an underlying issue which could be addressed?

**Comment by flekschas** [comment]
`let fixed = 'very likely'; if (fixed) { close(); } else { reopen(); }`
