### ISSUE TITLE
RepoExplorer: initializing with custom root doesn't trigger a query

### ISSUE THREAD

**Issue by flekschas** [refinery-platform/refinery-platform#970]
When the dashboard is loaded with a custom ontology term (e.g. http://192.168.50.50:8000/#/exploration?context=NCIT:C14421&branchId=0), the tree map automatically zooms into that node but the list of data sets is not queried.

**Comment by mccalluc** [comment]
This seems like a duplicate of #961, and if fixed now, I think.
